import { isNull } from 'lodash'

import { tagsCellRenderer } from '../../Table/BusinessPlansTable/schemaHelpers'

const allColumnDefs = (yearColumns: any[]) => [
  {
    autoHeight: true,
    cellClass: 'ag-text-center ag-cell-wrap-text ag-country-cell-text',
    field: 'country.name',
    headerClass: 'ag-text-center',
    headerName: 'Country',
    minWidth: 150,
    resizable: true,
    tooltipField: 'country.name',
  },
  {
    autoHeight: true,
    cellClass: 'ag-text-center ag-cell-wrap-text',
    field: 'project_cluster.code',
    headerClass: 'ag-text-center',
    headerName: 'Cluster',
    minWidth: 70,
    resizable: true,
    tooltipField: 'project_cluster.name',
  },
  {
    autoHeight: true,
    cellClass: 'ag-text-center ag-cell-wrap-text',
    field: 'project_type.code',
    headerClass: 'ag-text-center',
    headerName: 'Type',
    minWidth: 70,
    resizable: true,
    tooltipField: 'project_type.name',
  },
  {
    autoHeight: true,
    cellClass: 'ag-text-center ag-cell-wrap-text',
    field: 'bp_chemical_type.name',
    headerClass: 'ag-text-center',
    headerName: 'Chemical type',
    minWidth: 100,
    resizable: true,
    tooltipField: 'bp_chemical_type.name',
  },
  {
    autoHeight: true,
    cellClass: 'ag-text-center ag-cell-wrap-text',
    field: 'sector.code',
    headerClass: 'ag-text-center',
    headerName: 'Sector',
    minWidth: 70,
    resizable: true,
    tooltipField: 'sector.name',
  },
  {
    autoHeight: true,
    cellClass: 'ag-text-center ag-cell-wrap-text',
    field: 'subsector.code',
    headerClass: 'ag-text-center',
    headerName: 'Subsector',
    minWidth: 100,
    resizable: true,
    tooltipField: 'subsector.name',
  },
  {
    autoHeight: true,

    cellClass: 'ag-cell-wrap-text',
    field: 'title',
    headerClass: 'ag-text-center',
    headerName: 'Title',
    minWidth: 200,
    resizable: true,
    tooltipField: 'title',
  },
  {
    autoHeight: true,
    cellClass: 'ag-substances-cell-content',
    cellRenderer: tagsCellRenderer,
    field: 'substances_display',
    headerClass: 'ag-text-center',
    headerName: 'Substances',
    minWidth: 230,
    resizable: true,
  },
  {
    autoHeight: true,
    cellClass: 'ag-text-center ag-cell-wrap-text',
    field: 'required_by_model',
    headerClass: 'ag-text-center',
    headerName: 'Required by model',
    minWidth: 150,
    resizable: true,
    tooltipField: 'required_by_model',
  },
  {
    autoHeight: true,
    cellClass: 'ag-text-center',
    cellEditor: 'agNumberCellEditor',
    cellEditorParams: {
      allowNullVals: true,
      min: 0,
    },
    editable: true,
    field: 'amount_polyol',
    headerClass: 'ag-text-center',
    headerName: 'Polyol Amount',
    minWidth: 100,
    resizable: true,
    valueGetter: (params: any) => {
      const polyolAmount = params.data.amount_polyol

      return !isNull(polyolAmount) ? parseFloat(polyolAmount).toFixed(2) : null
    },
    wrapText: true,
  },
  ...yearColumns,
  {
    autoHeight: true,
    cellClass: 'ag-text-center',
    field: 'status',
    headerClass: 'ag-text-center',
    headerName: 'Status',
    minWidth: 100,
    resizable: true,
    tooltipField: 'status_display',
  },
  {
    autoHeight: true,
    cellClass: 'ag-text-center',
    field: 'is_multi_year',
    headerClass: 'ag-text-center',
    headerName: 'IND/MYA',
    minWidth: 100,
    resizable: true,
    tooltipField: 'is_multi_year_display',
    valueGetter: ({ data }: any) => (data.is_multi_year ? 'MYA' : 'IND'),
  },
  {
    autoHeight: true,
    cellClass: 'ag-cell-wrap-text',
    field: 'reason_for_exceeding',
    headerClass: 'ag-text-center',
    headerName: 'Reason for Exceeding',
    minWidth: 200,
    resizable: true,
    tooltipField: 'reason_for_exceeding',
  },
  {
    autoHeight: true,
    cellClass: 'ag-cell-wrap-text',
    field: 'remarks',
    headerClass: 'ag-text-center',
    headerName: 'Remarks',
    minWidth: 200,
    resizable: true,
    tooltipField: 'remarks',
  },
  {
    autoHeight: true,
    cellClass: 'ag-cell-wrap-text',
    field: 'comment_secretariat',
    headerClass: 'ag-text-center',
    headerName: 'Comment',
    minWidth: 200,
    resizable: true,
    tooltipField: 'comment_secretariat',
  },
  {
    autoHeight: true,
    cellRenderer: tagsCellRenderer,
    field: 'comment_types',
    headerClass: 'ag-text-center',
    headerName: 'Tags',
    minWidth: 230,
    resizable: true,
  },
]

export { allColumnDefs }
