'use client'
import React, { useContext, useMemo, useRef, useState } from 'react'

import { reduce } from 'lodash'
import { useParams } from 'next/navigation'

import {
  BPDataInterface,
  BpPathParams,
} from '@ors/components/manage/Blocks/BusinessPlans/types'
import TableDateSwitcher, {
  TableDataSelectorValuesType,
} from '@ors/components/manage/Blocks/Table/BusinessPlansTable/TableDateSwitcher'
import Table from '@ors/components/manage/Form/Table'
import BPContext from '@ors/contexts/BusinessPlans/BPContext'
import BPYearRangesContext from '@ors/contexts/BusinessPlans/BPYearRangesContext'
import { debounce } from '@ors/helpers/Utils/Utils'

import {
  allColumnDefs,
  commentsColumnDefs,
  odpColumnDefs,
  valuesColumnDefs,
} from '../../Table/BusinessPlansTable/schema'
import { numberCellRenderer } from '../../Table/BusinessPlansTable/schemaHelpers'

const BP_PER_PAGE = 20

export default function BPDiffTable({
  diffData,
}: {
  diffData: BPDataInterface
}) {
  const form = useRef<any>()
  const params = useParams<BpPathParams>()

  const { period } = params
  const year_start = period.split('-')[0]

  // const { setParams } = useContext(BPContext) as any
  const { yearRanges } = useContext(BPYearRangesContext) as any

  const { loaded, loading, results: results1 } = diffData || {}

  // const results = [
  //   {
  //     id: 20644,
  //     amount_polyol: null,
  //     amount_polyol_old: null,
  //     bp_chemical_type: {
  //       id: 1,
  //       name: 'HCFC',
  //     },

  //     bp_chemical_type_id: 1,
  //     bp_chemical_type_old: {
  //       id: 1,
  //       name: 'HCFC',
  //     },
  //     change_type: 'changed',
  //     comment_secretariat: '',
  //     comment_secretariat_old: '',
  //     comment_types: [],
  //     comment_types_old: [],
  //     country: {
  //       id: 202,
  //       abbr: 'TZ',
  //       has_cp_report: null,
  //       is_a2: false,
  //       iso3: 'TZA',
  //       name: 'United Republic of Tanzania',
  //       name_alt: 'Tanzania',
  //     },
  //     country_id: 14,
  //     country_old: {
  //       id: 14,
  //       abbr: 'AF',
  //       has_cp_report: null,
  //       is_a2: false,
  //       iso3: 'AFG',
  //       name: 'Afghanistan',
  //       name_alt: 'Afghanistan',
  //     },
  //     // country_old: {
  //     //   id: 202,
  //     //   abbr: 'TZ',
  //     //   has_cp_report: null,
  //     //   is_a2: false,
  //     //   iso3: 'TZA',
  //     //   name: 'United Republic of Tanzania',
  //     //   name_alt: 'Tanzania',
  //     // },
  //     initial_id: null,
  //     is_multi_year: true,
  //     is_multi_year_display: 'Multi-Year',
  //     is_multi_year_old: true,
  //     is_updated: false,
  //     legacy_sector_and_subsector: 'HPMP Stage I',
  //     legacy_sector_and_subsector_old:
  //       'Stage 2 - HCFC Phase-out Management Plan (implementation) ',
  //     lvc_status: 'Non-LVC',
  //     // legacy_sector_and_subsector_old: 'HPMP Stage I',
  //     lvc_status_old: 'LVC',
  //     project_cluster: {
  //       id: 28,
  //       category: 'BOTH',
  //       code: 'INS',
  //       name: 'INS',
  //       sort_order: 27,
  //     },
  //     project_cluster_id: 28,
  //     // lvc_status_old: 'Non-LVC',
  //     project_cluster_old: {
  //       id: 19,
  //       category: 'IND',
  //       code: 'CFCIND',
  //       name: 'CFC Individual',
  //       sort_order: 18,
  //     },
  //     // project_cluster_old: {
  //     //   id: 28,
  //     //   category: 'BOTH',
  //     //   code: 'INS',
  //     //   name: 'INS',
  //     //   sort_order: 27,
  //     // },
  //     project_type: {
  //       id: 10,
  //       code: 'PHA',
  //       name: 'Phase Out',
  //       sort_order: 22,
  //     },
  //     project_type_id: 10,
  //     project_type_old: {
  //       id: 10,
  //       code: 'PHA',
  //       name: 'Phase Out',
  //       sort_order: 22,
  //     },
  //     reason_for_exceeding: null,
  //     reason_for_exceeding_old: null,
  //     remarks: null,
  //     remarks_additional: null,
  //     remarks_additional_old: null,
  //     remarks_old: 'UN sanctions and the security situation is challenging',
  //     // remarks_old: null,
  //     required_by_model: 'Approved Multi-Year',
  //     required_by_model_old: 'Approved Multi-Year',
  //     sector: {
  //       id: 24,
  //       code: 'TAS',
  //       name: 'Technical Assistance',
  //       sort_order: 30,
  //     },
  //     sector_old: null,
  //     // sector_old: {
  //     //   id: 24,
  //     //   code: 'TAS',
  //     //   name: 'Technical Assistance',
  //     //   sort_order: 30,
  //     // },
  //     status: 'A',
  //     status_display: 'Approved',
  //     status_display_old: 'Approved',
  //     status_old: 'A',
  //     subsector: {
  //       id: 25,
  //       code: 'FXS',
  //       name: 'Fixed system',
  //       sector_id: 3,
  //       sort_order: 2,
  //     },
  //     subsector_old: null,
  //     // subsector_old: {
  //     //   id: 25,
  //     //   code: 'FXS',
  //     //   name: 'Fixed system',
  //     //   sector_id: 3,
  //     //   sort_order: 2,
  //     // },
  //     substances_display: ['HCFC-22'],
  //     substances_display_old: [],
  //     // substances_display_old: [],
  //     substances_old: [],
  //     title: '-',
  //     title_old: 'Afghanistan HPMP implementation  (Stage II)',
  //     values: [
  //       {
  //         is_after: false,
  //         value_mt: '924.965000000000000',
  //         value_mt_old: null,
  //         value_odp: '2.180000000000000',
  //         value_odp_old: null,
  //         value_usd: '215.265000000000000',
  //         value_usd_old: null,
  //         year: 2023,
  //       },
  //       {
  //         is_after: false,
  //         value_mt: '19.277468388147515',
  //         value_mt_old: '924.965000000000000',
  //         value_odp: '2.180000000000000',
  //         value_odp_old: '2.180000000000000',
  //         value_usd: '15.265000000000000',
  //         value_usd_old: '215.265000000000000',
  //         year: 2024,
  //       },
  //       {
  //         is_after: false,
  //         value_mt: '19.277468388147515',
  //         value_mt_old: '924.965000000000000',
  //         value_odp: '2.180000000000000',
  //         value_odp_old: '2.180000000000000',
  //         value_usd: '15.265000000000000',
  //         value_usd_old: '215.265000000000000',
  //         year: 2025,
  //       },
  //       {
  //         is_after: true,
  //         value_mt: '19.277468388147515',
  //         value_mt_old: '924.965000000000000',
  //         value_odp: '2.180000000000000',
  //         value_odp_old: '2.180000000000000',
  //         value_usd: '15.265000000000000',
  //         value_usd_old: '215.265000000000000',
  //         year: 2025,
  //       },
  //     ],
  //   },
  // ]

  const results = [
    {
      amount_polyol: '20.000000000000000',
      amount_polyol_old: null,
      bp_chemical_type: {
        id: 1,
        name: 'HCFC',
      },
      bp_chemical_type_id: 3,
      bp_chemical_type_old: {
        id: 1,
        name: 'HCFCf',
      },
      change_type: 'changed',
      comment_secretariat:
        'this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment this is a comment',
      comment_secretariat_old: 'this is a comment',
      comment_types: ['Test2', 'Sector', 'Subsector', 'Another test', 'Test 3'],
      comment_types_old: [
        'Test1',
        'Sector',
        'Subsector',
        'Another test',
        'Test 2',
        'Test 3',
      ],
      country: {
        id: 202,
        abbr: 'TZ',
        has_cp_report: null,
        is_a2: false,
        iso3: 'TZA',
        name: 'United Republic of Tanzania',
        name_alt: 'Tanzania',
      },
      country_id: 187,
      country_old: {
        id: 202,
        abbr: 'TZ',
        has_cp_report: null,
        is_a2: false,
        iso3: 'TZA',
        name: 'United Republic of Congo',
        name_alt: 'Tanzania',
      },
      initial_id: 22031,
      is_multi_year: false,
      is_multi_year_old: false,
      legacy_sector_and_subsector: 'PRO',
      legacy_sector_and_subsector_old: 'HPMP Stage I',
      lvc_status: 'Non-LVC',
      lvc_status_old: 'Non-LVC',
      project_cluster: {
        id: 19,
        category: 'IND',
        code: 'CFCIND',
        name: 'CFC Individual',
        sort_order: 18,
      },
      project_cluster_id: 22,
      project_cluster_old: {
        id: 28,
        category: 'BOTH',
        code: 'INS',
        name: 'INS',
        sort_order: 27,
      },
      project_type: {
        id: 10,
        code: 'PHA',
        name: 'Phase Out',
        sort_order: 22,
      },
      project_type_id: 10,
      project_type_old: {
        id: 10,
        code: 'PHA 2',
        name: 'Phase Out',
        sort_order: 22,
      },
      reason_for_exceeding: 'is very exceeding',
      reason_for_exceeding_old: null,
      remarks: 'UNIDO single implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: 'UNIDO single implementing agency',
      required_by_model: 'Approved Multi-Year',
      required_by_model_old: 'Approved Multi-Year',
      sector: {
        id: 24,
        code: 'TAS',
        name: 'Technical Assistance',
        sort_order: 30,
      },
      sector_id: 7,
      sector_old: {
        id: 24,
        code: 'TAS2',
        name: 'Technical Assistance',
        sort_order: 30,
      },
      status: 'A',
      status_display: 'Approved',
      status_display_old: 'Approved',
      status_old: 'A',
      subsector: {
        id: 25,
        code: 'FXS',
        name: 'Fixed system',
        sector_id: 3,
        sort_order: 2,
      },
      subsector_id: 38,
      subsector_old: {
        id: 25,
        code: 'FXS2',
        name: 'Fixed system',
        sector_id: 3,
        sort_order: 2,
      },
      substances: [124, 126],
      substances_display: [
        'HCFC-22',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
      ],
      substances_display_old: [
        'HCFC-22',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
        'HCFC-21',
      ],
      title: '',
      title_old: 'dana-test-2',
      values: [
        {
          is_after: false,
          value_mt: null,
          value_mt_old: '2',
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: '19.277468388147515',
          value_usd: '120.650000000000000',
          value_usd_old: '924.965000000000000',
          year: 2024,
        },
        {
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '544.913000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: '20.000000000000000',
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: 'hei',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 84,
      initial_id: 22051,
      is_multi_year: false,
      is_multi_year_display: 'Multi-Year-fals',
      is_multi_year_display_old: 'Multi-Year',
      is_multi_year_old: true,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding:
        'is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding',
      reason_for_exceeding_old:
        'is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding is very exceeding',
      remarks:
        'UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency2',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old:
        'UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency UNEP lead; UNIDO cooperating implementing agency',
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_display: 'Planned',
      status_display_old: 'Approved',
      status_old: 'A',
      subsector_id: 38,
      substances_display: ['HCFC-22'],
      substances_display_old: ['HCFC-22'],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58816,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58817,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58818,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: '20.000000000000000',
      amount_polyol_old: '20.000000000000000',
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 79,
      initial_id: 22050,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58813,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '32.100000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58814,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58815,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 73,
      initial_id: 22049,
      is_multi_year: true,
      is_multi_year_old: true,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58810,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58811,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '32.100000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58812,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 70,
      initial_id: 22048,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58807,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58808,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58809,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 69,
      initial_id: 22047,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58804,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '32.100000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58805,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58806,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 66,
      initial_id: 22046,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNIDO single implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58801,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58802,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '128.400000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58803,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 52,
      initial_id: 22045,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58798,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '38.520000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58799,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58800,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 47,
      initial_id: 22044,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: 'A',
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58795,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58796,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58797,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '38.520000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 46,
      initial_id: 22043,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58792,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58793,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58794,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 41,
      initial_id: 22042,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58789,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '32.100000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58790,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58791,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 36,
      initial_id: 22041,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58786,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '38.520000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58787,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58788,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 35,
      initial_id: 22040,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNIDO single implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58783,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '107.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58784,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58785,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 34,
      initial_id: 22039,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNIDO lead; UNEP cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58780,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58781,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '74.900000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58782,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 25,
      initial_id: 22038,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58777,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58778,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58779,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 21,
      initial_id: 22037,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage III',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNIDO lead; UNEP cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58774,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '89.880000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58775,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58776,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 19,
      initial_id: 22036,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNEP lead; UNIDO cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58771,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '32.100000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58772,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58773,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 15,
      initial_id: 22035,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP - Stage II',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNIDO lead; UNEP cooperating implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'HPMP - Energy Efficiency',
      required_by_model_old: null,
      sector_id: 7,
      status: 'P',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'HPMP - Energy Efficiency',
      title_old: null,
      values: [
        {
          id: 58768,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58769,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58770,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '0.000000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 3,
      change_type: 'new',
      comment_secretariat: '',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 127,
      initial_id: 22034,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'PRO',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'Non-LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: 'UNIDO single implementing agency',
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'Approved Multi-Year',
      required_by_model_old: null,
      sector_id: 7,
      status: 'A',
      status_old: null,
      subsector_id: 38,
      substances: [124],
      title:
        'Destruction of emissions of HFC-23 generated in the production of HCFC-22 in Quimobasicos',
      title_old: null,
      values: [
        {
          id: 58765,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '526.611000000000000',
          value_usd_old: null,
          year: 2023,
        },
        {
          id: 58766,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '400.588000000000000',
          value_usd_old: null,
          year: 2024,
        },
        {
          id: 58767,
          is_after: true,
          value_mt: null,
          value_mt_old: null,
          value_odp: '0.000000000000000',
          value_odp_old: null,
          value_usd: '2151.400000000000000',
          value_usd_old: null,
          year: 2025,
        },
      ],
    },
    {
      amount_polyol: null,
      amount_polyol_old: null,
      bp_chemical_type_id: 1,
      change_type: 'new',
      comment_secretariat: 'comm',
      comment_secretariat_old: null,
      comment_types: [],
      country_id: 187,
      initial_id: 22032,
      is_multi_year: true,
      is_multi_year_old: null,
      legacy_sector_and_subsector: 'HPMP Stage I',
      legacy_sector_and_subsector_old: null,
      lvc_status: 'Non-LVC',
      lvc_status_old: null,
      project_cluster_id: 22,
      project_type_id: 10,
      reason_for_exceeding: null,
      reason_for_exceeding_old: null,
      remarks: null,
      remarks_additional: null,
      remarks_additional_old: null,
      remarks_old: null,
      required_by_model: 'Approved Multi-Year',
      required_by_model_old: null,
      sector_id: 7,
      status: 'A',
      status_old: null,
      subsector_id: 38,
      substances: [],
      title: 'dana',
      title_old: null,
      values: [
        {
          id: 58761,
          is_after: false,
          value_mt: null,
          value_mt_old: null,
          value_odp: '19.277468388147515',
          value_odp_old: null,
          value_usd: '924.965000000000000',
          value_usd_old: null,
          year: 2024,
        },
      ],
    },
  ]

  const count = results?.length || 0
  const yearRangeSelected = useMemo(
    () => yearRanges.find((item: any) => item.year_start == year_start),
    [yearRanges, year_start],
  )

  const getYearColsValue = (
    value: any,
    year: number,
    isAfterMaxYear: boolean,
  ) =>
    isAfterMaxYear ? value.is_after : value.year === year && !value.is_after

  const yearColumns = useMemo(() => {
    if (!yearRangeSelected) return []

    const valuesUSD = []
    const valuesODP = []
    const valuesMT = []

    for (
      let year = yearRangeSelected.min_year;
      year <= yearRangeSelected.max_year + 1;
      year++
    ) {
      const isAfterMaxYear = year > yearRangeSelected.max_year

      let label = year
      if (isAfterMaxYear) {
        label = `After ${yearRangeSelected.max_year}`
      }

      const valuesCellGetter = (params: any, colIdentifier: string) => {
        const value = params.data.values.find((value: any) =>
          getYearColsValue(value, year, isAfterMaxYear),
        )
        const new_val = value?.[colIdentifier]
        const old_val = value?.[colIdentifier + '_old']

        return {
          new_value: new_val ? parseFloat(new_val).toFixed(2) : '',
          old_value: old_val ? parseFloat(old_val).toFixed(2) : '',
        }
      }

      valuesUSD.push({
        autoHeaderHeight: true,
        autoHeight: true,
        cellClass: 'ag-text-center',
        cellRenderer: numberCellRenderer,
        field: `value_usd_${year}`,
        headerClass: 'ag-text-center',
        headerName: `${label}`,
        minWidth: 80,
        resizable: true,
        valueGetter: (params: any) => valuesCellGetter(params, 'value_usd'),
      }),
        valuesODP.push({
          autoHeaderHeight: true,
          autoHeight: true,
          cellClass: 'ag-text-center',
          cellRenderer: numberCellRenderer,
          field: `value_odp_${year}`,
          headerClass: 'ag-text-center',
          headerName: `${label}`,
          minWidth: 80,
          resizable: true,
          valueGetter: (params: any) => valuesCellGetter(params, 'value_odp'),
        })

      valuesMT.push({
        autoHeaderHeight: true,
        autoHeight: true,
        cellClass: 'ag-text-center',
        cellRenderer: numberCellRenderer,
        field: `value_mt_${year}`,
        headerClass: 'ag-text-center',
        headerName: `${label}`,
        minWidth: 80,
        resizable: true,
        valueGetter: (params: any) => valuesCellGetter(params, 'value_mt'),
      })
    }

    return [
      {
        children: valuesUSD,
        headerName: 'Value ($000)',
      },
      {
        children: valuesODP,
        headerName: 'ODP',
      },
      {
        children: valuesMT,
        headerName: 'MT for HFC',
      },
    ]
  }, [yearRangeSelected])

  const [gridOptions, setGridOptions] =
    useState<TableDataSelectorValuesType>('all')

  const columnDefs = useMemo(() => {
    switch (gridOptions) {
      case 'values':
        return valuesColumnDefs(yearColumns, true)
      case 'odp':
        return odpColumnDefs(yearColumns, true)
      case 'comments':
        return commentsColumnDefs(true)
      default:
        return allColumnDefs(yearColumns, true)
    }
  }, [gridOptions, yearColumns])

  const displayFilters = () => {
    return (
      <div className="bp-table-toolbar mb-4 flex flex-col justify-between gap-4 lg:flex-row lg:items-center">
        <div className="flex gap-4 self-start">
          <TableDateSwitcher
            changeHandler={(event, value) => setGridOptions(value)}
            value={gridOptions}
          />
        </div>
      </div>
    )
  }

  const getPaginationSelectorOpts = (): number[] => {
    const nrResultsOpts = [10, 20, 50, 100]
    const filteredNrResultsOptions = nrResultsOpts.filter(
      (option) => option < count,
    )
    return [...filteredNrResultsOptions, count]
  }
  const paginationPageSizeSelectorOpts = getPaginationSelectorOpts()

  const grid = useRef<any>()

  const autoSizeColumns = () => {
    if (!grid.current.api) return
    grid.current.api.autoSizeColumns(
      reduce(
        columnDefs,
        (acc: Array<string>, column) => {
          acc.push(column.field)
          return acc
        },
        [],
      ),
    )
  }

  return (
    yearRanges &&
    yearRanges.length > 0 && (
      <form ref={form}>
        <Table
          className="bp-diff-table"
          Toolbar={displayFilters}
          columnDefs={[...columnDefs]}
          domLayout="normal"
          enablePagination={true}
          gridRef={grid}
          loaded={loaded}
          loading={loading}
          paginationPageSize={BP_PER_PAGE}
          paginationPageSizeSelector={paginationPageSizeSelectorOpts}
          rowBuffer={50}
          rowCount={count}
          rowData={results}
          rowsVisible={20}
          tooltipShowDelay={200}
          components={{
            agColumnHeader: undefined,
            agTextCellRenderer: undefined,
          }}
          onFirstDataRendered={() => {
            debounce(autoSizeColumns, 0)
          }}
          onPaginationChanged={({ page, rowsPerPage }) => {
            // setParams({
            //   limit: rowsPerPage,
            //   offset: page * rowsPerPage,
            // })
            debounce(autoSizeColumns, 0)
          }}
          onRowDataUpdated={() => {
            debounce(autoSizeColumns, 0)
          }}
          onSortChanged={({ api }) => {
            const ordering = api
              .getColumnState()
              .filter((column) => !!column.sort)
              .map(
                (column) =>
                  (column.sort === 'asc' ? '' : '-') +
                  column.colId.replaceAll('.', '__'),
              )
              .join(',')
            // setParams({ offset: 0, ordering })
          }}
        />
      </form>
    )
  )
}
