services:
  nextjs:
    build:
      context: .
      dockerfile: docker/nextjs.docker
    volumes:
      - nextjs_data:/frontend/.shared

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    volumes:
      - app_data:/.fs
      - nextjs_data:/.next
    depends_on:
      - nextjs
    ports:
      - "3000:80"

volumes:
  app_data:
    driver: local
  nextjs_data:
    driver: local

