x-environment:
  &default-env-vars
  CELERY_BROKER_URL: "amqp://rabbitmq:5672"
  CELERY_RESULT_BACKEND: "redis://redis:6379"

services:
  app:
    build:
      context: .
      dockerfile: docker/dev.docker
    container_name: "mlf.app"
    volumes:
      - ./:/app
      - ./static:/app/static

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    container_name: "mlf.nginx"
    ports:
      - 8080:80

  postgres:
    container_name: "mlf.postgres"

  celery:
    build:
      context: .
      dockerfile: docker/dev.docker
    environment: *default-env-vars
    container_name: "mlf.celery"
    volumes:
      - ./:/app

volumes:
  pg-data:
