version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always

  app:
    image: ghcr.io/multilateralfund/multilateralfund-app:${DOCKER_TAG:-main}
    env_file:
      - .env
    environment:
      - DJANGO_MIGRATE=yes
    volumes:
      - app_data:/app
    expose:
      - 8000
    depends_on:
      - postgres

  nginx:
    image: ghcr.io/multilateralfund/multilateralfund-nginx:${DOCKER_TAG:-main}
    volumes:
      - app_data:/app
    depends_on:
      - app
    ports:
      - "3000:80"

volumes:
  pg-data:
    driver: local
  app_data:
    driver: local
