services:
  app:
    environment:
      # Control how many resources to give the webapp.
      # See full list here https://docs.gunicorn.org/en/stable/settings.html#config
      - GUNICORN_CMD_ARGS=--timeout 60 --workers=4 --threads=2

  nextjs:
    deploy:
      replicas: 4

  nginx:
    environment:
      # Control how many resources to give the nginx
      - NGINX_WORKER_PROCESSES=4

  postfix:
    image: dbck/mailtrap
    container_name: "mlf.mailtrap"
    stdin_open: true
    tty: true
    ports:
    - 81:80