services:
  app:
    build:
      context: .
      dockerfile: docker/dev.docker
    environment:
      - GUNICORN_CMD_ARGS=--workers=2 --threads=2
    mem_limit: 0

  libreoffice:
    build:
      context: .
      dockerfile: docker/libreoffice.docker
    mem_limit: 0

  nextjs:
    build:
      context: .
      dockerfile: docker/nextjs.docker

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker

  clamav:
    mem_limit: 0

  celery:
    profiles:
      - donotstart
    mem_limit: 0
