version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/dev.docker
    container_name: "mlf.app"
    volumes:
      - ./:/app
      - ./static:/app/static

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    container_name: "mlf.nginx"
    ports:
      - 8080:80

  postgres:
    container_name: "mlf.postgres"

volumes:
  pg-data:
