services:
  app:
    build:
      context: .
      dockerfile: docker/dev.docker
    environment:
      - GUNICORN_CMD_ARGS=--workers=2 --threads=2

  nextjs:
    build:
      context: .
      dockerfile: docker/nextjs.docker

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
