version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always

  app:
    image: ghcr.io/multilateralfund/multilateralfund-app:${DOCKER_TAG:-latest}
    env_file:
      - .env
    environment:
      - DJANGO_MIGRATE=yes
    volumes:
      - app_data:/app/.fs
    expose:
      - 8000
    depends_on:
      - postgres

  nextjs:
    image: ghcr.io/multilateralfund/multilateralfund-nextjs:${DOCKER_TAG:-latest}
    volumes:
      - nextjs_data:/frontend/.shared
    expose:
      - 3000

  nginx:
    image: ghcr.io/multilateralfund/multilateralfund-nginx:${DOCKER_TAG:-latest}
    volumes:
      - app_data:/.fs
      - nextjs_data:/.next
    depends_on:
      - app
      - nextjs
    ports:
      - "3000:80"

volumes:
  pg-data:
    driver: local
  app_data:
    driver: local
  nextjs_data:
    driver: local
