version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always

  app:
    build:
      context: .
      dockerfile: docker/app.docker
    volumes:
      - app_volume:/app
      - static_volume:/app/static
    ports:
      - 8000:8000
    command: ["run"]
    restart: always
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: docker/dev.docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000

volumes:
  pg-data:
  static_volume:
  app_volume:
