# Generated by Django 4.2 on 2023-04-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blend_name", models.CharField(max_length=100)),
                ("blend_description", models.TextField(blank=True, null=True)),
                ("blend_odp", models.FloatField(blank=True, null=True)),
                ("blend_gwp", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=100)),
                ("country_m49", models.IntegerField(blank=True, null=True)),
                ("country_iso", models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Substance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("substance_name", models.CharField(max_length=100)),
                ("substance_description", models.TextField(blank=True, null=True)),
                (
                    "substance_formula",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("substance_isomers", models.IntegerField(blank=True, null=True)),
                ("substance_odp", models.FloatField(blank=True, null=True)),
                ("substance_gwp", models.FloatField(blank=True, null=True)),
                ("substance_polyol", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_name", models.CharField(max_length=100)),
                ("usage_description", models.TextField()),
                (
                    "usage_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to="core.usage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlendSubstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.FloatField()),
                (
                    "blend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blend",
                        to="core.blend",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substance",
                        to="core.substance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blend",
            name="blend_substances",
            field=models.ManyToManyField(
                through="core.BlendSubstance", to="core.substance"
            ),
        ),
    ]
