# Generated by Django 4.2 on 2023-04-06 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlendComponents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("component_name", models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.CharField(max_length=64)),
                ("annex", models.CharField(max_length=64)),
                ("name", models.CharField(default="", max_length=128, unique=True)),
                ("name_alt", models.CharField(blank=True, max_length=128, null=True)),
                ("description", models.TextField()),
                ("description_alt", models.TextField(blank=True, null=True)),
                ("is_odp", models.BooleanField(default=True)),
                ("is_gwp", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="substance",
            old_name="substance_description",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="blend",
            name="blend_description",
        ),
        migrations.RemoveField(
            model_name="blend",
            name="blend_gwp",
        ),
        migrations.RemoveField(
            model_name="blend",
            name="blend_name",
        ),
        migrations.RemoveField(
            model_name="blend",
            name="blend_odp",
        ),
        migrations.RemoveField(
            model_name="blend",
            name="blend_substances",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="substance_formula",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="substance_gwp",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="substance_isomers",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="substance_name",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="substance_odp",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="substance_polyol",
        ),
        migrations.AddField(
            model_name="blend",
            name="composition",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="blend",
            name="composition_alt",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="blend",
            name="gwp",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="blend",
            name="is_contained_in_polyols",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blend",
            name="name",
            field=models.CharField(default="test", max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blend",
            name="odp",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="blend",
            name="other_names",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="blend",
            name="sort_order",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="blend",
            name="trade_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="blend",
            name="type",
            field=models.CharField(
                choices=[
                    ("Zeotrope", "Zeotrope"),
                    ("Azeotrope", "Azeotrope"),
                    ("Methyl bromide", "Methyl bromide"),
                    ("Other", "Other"),
                    ("Custom", "Custom"),
                ],
                default="Other",
                max_length=256,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substance",
            name="bromines",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="carbons",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="chlorines",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="fluorines",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="formula",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="gwp",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="gwp_baseline",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="gwp_error_plus_minus",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="hydrogens",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="is_captured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="substance",
            name="is_contained_in_polyols",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substance",
            name="max_odp",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substance",
            name="min_odp",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substance",
            name="name",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substance",
            name="number_of_isomers",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="odp",
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="substance",
            name="sort_order",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="BlendSubstance",
        ),
        migrations.AddField(
            model_name="blendcomponents",
            name="blend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.blend"
            ),
        ),
        migrations.AddField(
            model_name="blendcomponents",
            name="substance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.substance"
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="substances",
                to="core.group",
            ),
        ),
    ]
