# Generated by Django 4.2 on 2023-04-12 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_countryprogrammereport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.RemoveField(
            model_name="country",
            name="m49",
        ),
        migrations.AddField(
            model_name="country",
            name="full_name",
            field=models.CharField(default="test", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="country",
            name="lvc_baseline",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="ozone_unit",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Subregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.region"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="country",
            name="subregion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subregion",
            ),
        ),
    ]
