# Generated by Django 4.2 on 2023-04-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_region_alter_country_options_remove_country_m49_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryprogrammereport",
            name="source",
            field=models.CharField(default="test", max_length=248),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="price",
            name="blend",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.blend",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="substance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.substance",
            ),
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_odp", models.FloatField(blank=True, null=True)),
                ("value_metric", models.FloatField(blank=True, null=True)),
                ("section", models.CharField(max_length=164)),
                (
                    "blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.blend",
                    ),
                ),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.countryprogrammereport",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usage"
                    ),
                ),
            ],
        ),
    ]
