# Generated by Django 4.2 on 2023-04-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_countryprogrammereport_source_alter_price_blend_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countryprogrammereport",
            name="source",
        ),
        migrations.AddField(
            model_name="record",
            name="source",
            field=models.CharField(default="test", max_length=248),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blend",
            name="composition",
            field=models.CharField(
                blank=True,
                help_text="Plain-test description of the composition of the blend.",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blend",
            name="gwp",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Global Warming Potential",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blend",
            name="odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Ozone Depletion Potential",
                max_digits=20,
                null=True,
            ),
        ),
    ]
