# Generated by Django 4.2 on 2023-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_agency_projectsector_projectsubmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blend",
            name="ozone_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blendcomponents",
            name="ozone_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="abbr",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="abbr_alt",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="name_alt",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="ozone_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="ozone_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="abbr",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="ozone_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subregion",
            name="abbr",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="subregion",
            name="ozone_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="ozone_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="substance",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
