# Generated by Django 4.2 on 2023-05-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_blend_ozone_id_blendcomponents_ozone_id_country_abbr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubstanceAltName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("ozone_id", models.IntegerField(blank=True, null=True)),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.substance"
                    ),
                ),
            ],
        ),
    ]
