# Generated by Django 4.2 on 2023-05-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_substancealtname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agency",
            options={"verbose_name_plural": "Agencies"},
        ),
        migrations.AlterField(
            model_name="country",
            name="iso3",
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
