# Generated by Django 4.2 on 2023-05-09 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_agency_options_alter_country_iso3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subregion",
            old_name="ozone_id",
            new_name="import_id",
        ),
        migrations.RemoveField(
            model_name="region",
            name="ozone_id",
        ),
    ]
