# Generated by Django 4.2 on 2023-05-13 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_ozone_id_subregion_import_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Record",
            new_name="CountryProgrammeRecord",
        ),
        migrations.AlterModelOptions(
            name="blendcomponents",
            options={"verbose_name_plural": "Blend Components"},
        ),
    ]
