# Generated by Django 4.2 on 2023-05-18 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_blendaltname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blendcomponents",
            options={"verbose_name_plural": "Blend components"},
        ),
    ]
