# Generated by Django 4.2 on 2023-05-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_blendaltname"),
    ]

    operations = [
        migrations.AddField(
            model_name="usage",
            name="sort_order",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blend",
            name="sort_order",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="substance",
            name="sort_order",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ChemicalUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.blend",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usage"
                    ),
                ),
            ],
        ),
    ]
