# Generated by Django 4.2 on 2023-05-19 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_blendcomponents_options"),
        ("core", "0014_usage_sort_order_alter_blend_sort_order_and_more"),
    ]

    operations = []
