# Generated by Django 4.2 on 2023-05-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_merge_20230519_0742"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsector",
            name="description",
        ),
        migrations.RemoveField(
            model_name="projectsubsector",
            name="description",
        ),
        migrations.AddField(
            model_name="projectsector",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="projectsubsector",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
