# Generated by Django 4.2 on 2023-05-19 08:55

from django.db import migrations, models
import django.db.models.deletion

# please make sure that projectsubmissions table is empty before running this migration


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_merge_20230519_0742"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsubsector",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="subsector",
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="usage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.usage"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usage",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name="ProjectSector",
        ),
        migrations.DeleteModel(
            name="ProjectSubSector",
        ),
    ]
