# Generated by Django 4.2 on 2023-05-22 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_projectsector_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChemicalUsage",
            new_name="ExcludedUsage",
        ),
    ]
