# Generated by Django 4.2 on 2023-05-22 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_projectsubsector_sector_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usage",
            name="description",
        ),
    ]
