# Generated by Django 4.2 on 2023-05-23 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_rename_chemicalusage_excludedusage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="countryprogrammerecord",
            old_name="source",
            new_name="source_file",
        ),
        migrations.RenameField(
            model_name="projectsubmission",
            old_name="source",
            new_name="source_file",
        ),
        migrations.RemoveField(
            model_name="countryprogrammerecord",
            name="usage",
        ),
        migrations.RemoveField(
            model_name="countryprogrammerecord",
            name="value_metric",
        ),
        migrations.RemoveField(
            model_name="countryprogrammerecord",
            name="value_odp",
        ),
        migrations.AddField(
            model_name="countryprogrammerecord",
            name="banned_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="countryprogrammerecord",
            name="exports",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="countryprogrammerecord",
            name="import_quotas",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="countryprogrammerecord",
            name="imports",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="countryprogrammerecord",
            name="manufacturing_blends",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="countryprogrammerecord",
            name="production",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="countryprogrammerecord",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CountryProgrammeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "country_programme_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.countryprogrammerecord",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usage"
                    ),
                ),
            ],
        ),
    ]
