# Generated by Django 4.2 on 2023-05-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_rename_source_countryprogrammerecord_source_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.usage",
            ),
        ),
    ]
