# Generated by Django 4.2 on 2023-05-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_usage_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excludedusage",
            name="blend",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excluded_usages",
                to="core.blend",
            ),
        ),
        migrations.AlterField(
            model_name="excludedusage",
            name="substance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excluded_usages",
                to="core.substance",
            ),
        ),
    ]
