# Generated by Django 4.2 on 2023-05-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_excludedusage_blend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="countryprogrammerecord",
            name="display_name",
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name="substance",
            name="odp",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
