# Generated by Django 4.2 on 2023-05-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_countryprogrammerecord_display_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countryprogrammeusage",
            name="country_programme_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="record_usages",
                to="core.countryprogrammerecord",
            ),
        ),
    ]
