# Generated by Django 4.2 on 2023-06-07 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_countryprogrammeusage_country_programme_record"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=248)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdmColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=248)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdmRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("subtitle", "Subtitle"),
                            ("question", "Question"),
                            ("user_text", "User Text"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        blank=True, max_length=248, null=True, verbose_name="row index"
                    ),
                ),
                ("cp_id", models.IntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                (
                    "parent_row",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.admrow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdmRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_float", models.FloatField(blank=True, null=True)),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("section", models.CharField(max_length=10)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                (
                    "blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.blend",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.admcolumn"
                    ),
                ),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adm_records",
                        to="core.countryprogrammereport",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.admrow"
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
                (
                    "value_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.admchoice",
                    ),
                ),
            ],
        ),
    ]
