# Generated by Django 4.2 on 2023-06-06 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_countryprogrammeusage_country_programme_record"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ("name",), "verbose_name_plural": "Countries"},
        ),
    ]
