# Generated by Django 4.2 on 2023-06-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_admchoice_admcolumn_admrow_admrecord'),
        ('core', '0023_alter_country_options'),
    ]

    operations = [
    ]
