# Generated by Django 4.2 on 2023-06-13 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_country_options"),
        ("core", "0023_countryprogrammeprices"),
    ]

    operations = []
