# Generated by Django 4.2 on 2023-06-13 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_merge_20230613_0814"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countryprogrammeprices",
            options={"verbose_name_plural": "Country programme prices"},
        ),
        migrations.DeleteModel(
            name="Price",
        ),
    ]
