# Generated by Django 4.2 on 2023-06-13 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_countryprogrammerecord_export_quotas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admrow",
            name="cp_id",
        ),
    ]
