# Generated by Django 4.2 on 2023-06-14 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_remove_admrow_cp_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryProgrammePrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("source_file", models.CharField(max_length=248)),
                (
                    "previous_year_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "previous_year_text",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                (
                    "current_year_price",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "current_year_text",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                (
                    "blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.blend",
                    ),
                ),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.countryprogrammereport",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Country programme prices",
            },
        ),
        migrations.DeleteModel(
            name="Price",
        ),
    ]
