# Generated by Django 4.2 on 2023-06-19 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_countryprogrammeprices_delete_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryProgrammeSectionERecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility",
                    models.CharField(
                        help_text="Facility name or identifier", max_length=256
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Total amount generated",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "all_uses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount generated and captured - For all uses",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "feedstock_gc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount generated and captured - For feedstock use in your country",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "destruction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount generated and captured - For destruction",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "feedstock_wpc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for feedstock uses within your country",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "destruction_wpc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount used for feedstock without prior capture",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "generated_emissions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for destruction",
                        max_digits=25,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("source_file", models.CharField(max_length=248)),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.countryprogrammereport",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountryProgrammeSectionDRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "all_uses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for all uses",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "feedstock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for feedstock uses within your country",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "destruction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for destruction",
                        max_digits=25,
                        null=True,
                    ),
                ),
                ("source_file", models.CharField(max_length=248)),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.countryprogrammereport",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
            ],
        ),
    ]
