# Generated by Django 4.2 on 2023-06-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_countryprogrammeprices_delete_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="admchoice",
            name="adm_row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.admrow"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="admrecord",
            name="column",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.admcolumn",
            ),
        ),
    ]
