# Generated by Django 4.2 on 2023-06-22 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_cpemission_cpgeneration_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CountryProgrammePrices",
            new_name="CPPrices",
        ),
        migrations.RenameModel(
            old_name="CountryProgrammeRecord",
            new_name="CPRecord",
        ),
        migrations.RenameModel(
            old_name="CountryProgrammeReport",
            new_name="CPReport",
        ),
        migrations.RenameModel(
            old_name="CountryProgrammeUsage",
            new_name="CPUsage",
        ),
        migrations.AlterModelOptions(
            name="cpemission",
            options={
                "verbose_name": "CP emission",
                "verbose_name_plural": "CP emissions",
            },
        ),
        migrations.AlterModelOptions(
            name="cpgeneration",
            options={
                "verbose_name": "CP generation",
                "verbose_name_plural": "CP generations",
            },
        ),
        migrations.AlterModelOptions(
            name="cpprices",
            options={"verbose_name": "CP price", "verbose_name_plural": "CP prices"},
        ),
        migrations.AlterModelOptions(
            name="cprecord",
            options={"verbose_name": "CP record", "verbose_name_plural": "CP records"},
        ),
        migrations.AlterModelOptions(
            name="cpreport",
            options={"verbose_name": "CP report", "verbose_name_plural": "CP reports"},
        ),
        migrations.AlterModelOptions(
            name="cpusage",
            options={"verbose_name": "CP usage", "verbose_name_plural": "CP usages"},
        ),
        migrations.AlterModelTable(
            name="admchoice",
            table="cp_admchoice",
        ),
        migrations.AlterModelTable(
            name="admcolumn",
            table="cp_admcolumn",
        ),
        migrations.AlterModelTable(
            name="admrecord",
            table="cp_admrecord",
        ),
        migrations.AlterModelTable(
            name="admrow",
            table="cp_admrow",
        ),
        migrations.AlterModelTable(
            name="cpemission",
            table="cp_emission",
        ),
        migrations.AlterModelTable(
            name="cpgeneration",
            table="cp_generation",
        ),
        migrations.AlterModelTable(
            name="cpprices",
            table="cp_prices",
        ),
        migrations.AlterModelTable(
            name="cprecord",
            table="cp_record",
        ),
        migrations.AlterModelTable(
            name="cpreport",
            table="cp_report",
        ),
        migrations.AlterModelTable(
            name="cpusage",
            table="cp_usage",
        ),
    ]
