# Generated by Django 4.2 on 2023-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_rename_countryprogrammeprices_cpprices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpreport",
            name="reporting_email",
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="reporting_entry",
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="submission_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
