# Generated by Django 4.2 on 2023-06-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_cpreport_reporting_email_cpreport_reporting_entry_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpprices",
            name="current_year_text",
        ),
        migrations.RemoveField(
            model_name="cpprices",
            name="previous_year_text",
        ),
        migrations.AlterField(
            model_name="cpprices",
            name="current_year_price",
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AlterField(
            model_name="cpprices",
            name="previous_year_price",
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
    ]
