# Generated by Django 4.2 on 2023-07-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_remove_cpprices_current_year_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blendcomponents",
            name="blend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="core.blend",
            ),
        ),
    ]
