# Generated by Django 4.2 on 2023-07-11 13:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_remove_admrecord_value_bool_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admrow",
            name="parent_row",
        ),
        migrations.AddField(
            model_name="admrow",
            name="level",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admrow",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admrow",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.admrow",
            ),
        ),
        migrations.AddField(
            model_name="admrow",
            name="rght",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admrow",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="admchoice",
            name="adm_row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="core.admrow",
            ),
        ),
        migrations.AlterField(
            model_name="admcolumn",
            name="max_year",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1985)]
            ),
        ),
        migrations.AlterField(
            model_name="admcolumn",
            name="min_year",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1985)]
            ),
        ),
        migrations.AlterField(
            model_name="admrecord",
            name="row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="core.admrow",
            ),
        ),
        migrations.AlterField(
            model_name="admrow",
            name="max_year",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1985)]
            ),
        ),
        migrations.AlterField(
            model_name="admrow",
            name="min_year",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1985)]
            ),
        ),
    ]
