# Generated by Django 4.2 on 2023-07-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_remove_admrow_parent_row_admrow_level_admrow_lft_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("approval_meeting_no", models.IntegerField(blank=True, null=True)),
                ("project_duration", models.IntegerField(blank=True, null=True)),
                (
                    "application",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                ("products_manufactured", models.TextField(blank=True, null=True)),
                ("plan", models.TextField(blank=True, null=True)),
                ("excom_provision", models.TextField(blank=True, null=True)),
                ("technology", models.CharField(blank=True, max_length=256, null=True)),
                ("impact", models.FloatField(blank=True, null=True)),
                ("impact_co2mt", models.FloatField(blank=True, null=True)),
                ("impact_production", models.FloatField(blank=True, null=True)),
                ("impact_prod_co2mt", models.FloatField(blank=True, null=True)),
                ("ods_phasedout", models.FloatField(blank=True, null=True)),
                ("ods_phasedout_co2mt", models.FloatField(blank=True, null=True)),
                (
                    "substance_type",
                    models.CharField(
                        choices=[
                            ("HCFC", "HCFC"),
                            ("HFC", "HFC"),
                            ("HFC_Plus", "HFC_Plus"),
                        ],
                        max_length=256,
                    ),
                ),
                ("hcfc_stage", models.FloatField(blank=True, null=True)),
                ("capital_cost", models.FloatField(blank=True, null=True)),
                ("operating_cost", models.FloatField(blank=True, null=True)),
                ("effectiveness_cost", models.FloatField(blank=True, null=True)),
                ("fund_disbursed", models.FloatField(blank=True, null=True)),
                ("fund_disbursed_13", models.FloatField(blank=True, null=True)),
                ("date_completion", models.DateField(blank=True, null=True)),
                ("date_actual", models.DateField(blank=True, null=True)),
                ("date_comp_revised", models.DateField(blank=True, null=True)),
                ("date_per_agreement", models.DateField(blank=True, null=True)),
                ("umbrella_project", models.BooleanField(default=False)),
                ("loan", models.BooleanField(default=False)),
                ("intersessional_approval", models.BooleanField(default=False)),
                ("retroactive_finance", models.BooleanField(default=False)),
                ("local_ownership", models.BooleanField(default=False)),
                ("export_to", models.FloatField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agency"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("support_13", models.FloatField(default=0, null=True)),
                ("meeting", models.IntegerField()),
                ("interest", models.FloatField(default=0, null=True)),
                ("date", models.DateField()),
                (
                    "fund_type",
                    models.CharField(
                        choices=[
                            ("allocated", "Allocated"),
                            ("transferred", "Transferred"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funds",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectOdsOdp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odp", models.FloatField(blank=True, null=True)),
                ("co2_mt", models.FloatField(blank=True, null=True)),
                ("is_production", models.BooleanField(default=False)),
                ("is_indirect", models.BooleanField(default=False)),
                (
                    "ods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ods",
                        to="core.substance",
                    ),
                ),
                (
                    "ods_replacement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("sort_order", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="agency",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="capital_cost",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="cost_effectivness",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="country",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="date_completion",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="description",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="excom_provision",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="export_to",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="impact",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="intersessional_approval",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="is_HCFC",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="is_HFC",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="loan",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="local_ownership",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="meeting1",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="operating_cost",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="products_manufactured",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="project_duration",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="project_number",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="retroactive_finance",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="status_code",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="subsector",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="title",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="type",
        ),
        migrations.RemoveField(
            model_name="projectsubmission",
            name="umbrella_project",
        ),
        migrations.AddField(
            model_name="projectsector",
            name="sort_order",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectsubsector",
            name="sort_order",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="admrecord",
            name="row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.admrow"
            ),
        ),
        migrations.DeleteModel(
            name="SubmissionOdsOdp",
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.projecttype"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.projectstatus"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="subsector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.projectsubsector"
            ),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="core.project",
            ),
            preserve_default=False,
        ),
    ]
