# Generated by Django 4.2 on 2023-07-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_project_projectfund_projectodsodp_projectstatus_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectstatus",
            options={"verbose_name_plural": "Project statuses"},
        ),
        migrations.RemoveField(
            model_name="projectodsodp",
            name="ods",
        ),
        migrations.AddField(
            model_name="projectfund",
            name="sort_order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectodsodp",
            name="ods_blend",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_ods",
                to="core.blend",
            ),
        ),
        migrations.AddField(
            model_name="projectodsodp",
            name="ods_display_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="projectodsodp",
            name="ods_substance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_ods",
                to="core.substance",
            ),
        ),
        migrations.AddField(
            model_name="projectodsodp",
            name="sort_order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name="project",
            name="local_ownership",
        ),
        migrations.AddField(
            model_name="project",
            name="local_ownership",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectfund",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectfund",
            name="meeting",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="odp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="ods_replacement",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
