# Generated by Django 4.2 on 2023-07-25 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_projectstatus_options_remove_projectodsodp_ods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsubmission",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="core.project",
            ),
        ),
    ]
