# Generated by Django 4.2 on 2023-07-31 08:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_projectsubmission_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectstatus",
            name="color",
            field=colorfield.fields.ColorField(
                default="#CCCCCC", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
