# Generated by Django 4.2 on 2023-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_projectsubmission_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="source_file",
        ),
        migrations.RemoveField(
            model_name="projectodsodp",
            name="is_indirect",
        ),
        migrations.RemoveField(
            model_name="projectodsodp",
            name="is_production",
        ),
        migrations.AddField(
            model_name="project",
            name="project_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectodsodp",
            name="ods_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("production", "Production"),
                    ("indirect", "Indirect"),
                ],
                default="general",
                max_length=256,
            ),
        ),
    ]
