# Generated by Django 4.2 on 2023-07-31 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_projectstatus_color"),
        ("core", "0040_remove_project_source_file_and_more"),
    ]

    operations = []
