# Generated by Django 4.2 on 2023-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_merge_20230731_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="coop_agencies",
            field=models.ManyToManyField(
                related_name="coop_projects", to="core.agency"
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="odp",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
