# Generated by Django 4.2 on 2023-08-22 11:31

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    sub_sector = apps.get_model("core", "ProjectSubSector")
    to_delete = [
        "Tobacco",
        "Production CFC",
        "HCFC Production",
        "Production ODS",
        "Production TCA",
        "Accelerated Production CFC",
        "CFCs/CTC/Halon Accelerated Phase-Out Plan",
        "Production Methyl Bromide",
        "Domestic Refrigeration",
        "Refrigeration Servicing",
        "Foam",
        "Halon",
        "Process Agent",
        "Solvent",
        "KIP",
    ]
    sub_sector.objects.filter(name__in=to_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_projectfile_options_project_date_per_decision_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsubsector",
            name="multi_year",
        ),
        migrations.AddField(
            model_name="project",
            name="mya_subsector",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
