# Generated by Django 4.2 on 2023-08-22 13:50

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_remove_projectsubsector_multi_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/home/kiro/PycharmProjects/ors/.fs/protected_media"
                    )
                ),
                upload_to="project_files/",
            ),
        ),
        migrations.CreateModel(
            name="ProjectProgressReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mtg", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=256)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("num", models.PositiveIntegerField(blank=True, null=True)),
                ("a_n", models.CharField(blank=True, max_length=1, null=True)),
                ("irdx", models.CharField(blank=True, max_length=1, null=True)),
                ("chemical", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "consumption_odp_out_proposal",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "consumption_odp_out_actual",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "production_odp_out_proposal",
                    models.FloatField(blank=True, null=True),
                ),
                ("production_odp_out_actual", models.FloatField(blank=True, null=True)),
                ("date_approved", models.DateField(blank=True, null=True)),
                ("date_first_disbursement", models.DateField(blank=True, null=True)),
                ("date_comp_proposal", models.DateField(blank=True, null=True)),
                ("date_comp_actual", models.DateField(blank=True, null=True)),
                ("funds_approved", models.FloatField(blank=True, null=True)),
                ("funds_adjustment", models.FloatField(blank=True, null=True)),
                ("funds_net", models.FloatField(blank=True, null=True)),
                ("funds_disbursed", models.FloatField(blank=True, null=True)),
                ("percent_disbursed", models.FloatField(blank=True, null=True)),
                ("balance", models.FloatField(blank=True, null=True)),
                ("funds_obligated", models.FloatField(blank=True, null=True)),
                ("funds_current_year", models.FloatField(blank=True, null=True)),
                ("support_approved", models.FloatField(blank=True, null=True)),
                ("support_adjustment", models.FloatField(blank=True, null=True)),
                ("support_disbursed", models.FloatField(blank=True, null=True)),
                ("support_obligated", models.FloatField(blank=True, null=True)),
                ("support_returned", models.FloatField(blank=True, null=True)),
                (
                    "year_approved",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1985)],
                    ),
                ),
                (
                    "year_of_contribution",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1985)],
                    ),
                ),
                (
                    "months_first_disbursement",
                    models.IntegerField(blank=True, null=True),
                ),
                ("months_comp_proposal", models.IntegerField(blank=True, null=True)),
                ("months_comp_plan", models.IntegerField(blank=True, null=True)),
                ("months_comp_actual", models.IntegerField(blank=True, null=True)),
                ("remarks_1", models.TextField(blank=True, null=True)),
                ("remarks_2", models.TextField(blank=True, null=True)),
                (
                    "BP_allocation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "meeting_of_report",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agency"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
                (
                    "latest_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.projectstatus",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_reports",
                        to="core.project",
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.projecttype",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.region"
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.projectsector",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.projectstatus",
                    ),
                ),
            ],
        ),
    ]
