# Generated by Django 4.2 on 2023-08-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_alter_projectfile_file_projectprogressreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "meeting_of_report",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "secretariat_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Secretariat's Comment"
                    ),
                ),
                (
                    "agency_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Agency's Response"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
