# Generated by Django 4.2 on 2023-09-11 22:23

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_projectcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BPChemicalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BusinessPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("cluster", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "year_start",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1985)]
                    ),
                ),
                (
                    "year_end",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1985)]
                    ),
                ),
                (
                    "hcfc_status",
                    models.CharField(
                        choices=[
                            ("LVC", "LVC"),
                            ("Non-LVC", "Non-LVC"),
                            ("Regional", "Regional"),
                            ("Undefined", "Undefined"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "amount_polyol",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "sector_subsector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bp_type",
                    models.CharField(
                        choices=[
                            ("A", "Approved"),
                            ("P", "Planned"),
                            ("U", "Undefined"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_multi_year", models.BooleanField(default=False)),
                ("reason_for_exceding", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("remarks_additional", models.TextField(blank=True, null=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agency"
                    ),
                ),
                ("blends", models.ManyToManyField(to="core.blend")),
                (
                    "bp_chemical_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bpchemicaltype",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.projecttype",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.projectsector",
                    ),
                ),
                (
                    "subsector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.projectsubsector",
                    ),
                ),
                ("substances", models.ManyToManyField(to="core.substance")),
            ],
        ),
        migrations.CreateModel(
            name="BPValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1985)]
                    ),
                ),
                (
                    "value_usd",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "value_odp",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "value_mt",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "business_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.businessplan",
                    ),
                ),
            ],
        ),
    ]
