# Generated by Django 4.2 on 2023-09-18 08:14

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_bpchemicaltype_alter_projectfile_file_businessplan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BPRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "required_by_model",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lvc_status",
                    models.CharField(
                        choices=[
                            ("LVC", "LVC"),
                            ("Non-LVC", "Non-LVC"),
                            ("Regional", "Regional"),
                            ("Undefined", "Undefined"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "amount_polyol",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "sector_subsector",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bp_type",
                    models.CharField(
                        choices=[
                            ("A", "Approved"),
                            ("P", "Planned"),
                            ("U", "Undefined"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_multi_year", models.BooleanField(default=False)),
                ("reason_for_exceding", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("remarks_additional", models.TextField(blank=True, null=True)),
                ("blends", models.ManyToManyField(to="core.blend")),
                (
                    "bp_chemical_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bpchemicaltype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BPRecordValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1985)]
                    ),
                ),
                (
                    "value_usd",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "value_odp",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "value_mt",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "bp_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bprecord"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="amount_polyol",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="blends",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="bp_chemical_type",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="bp_type",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="country",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="hcfc_status",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="is_multi_year",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="project_type",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="reason_for_exceding",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="remarks_additional",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="sector_subsector",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="subsector",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="substances",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="title",
        ),
        migrations.AddField(
            model_name="businessplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted", "Submitted"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Draft",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/.fs/protected_media")
                ),
                upload_to="project_files/",
            ),
        ),
        migrations.DeleteModel(
            name="BPValue",
        ),
        migrations.AddField(
            model_name="bprecord",
            name="business_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.businessplan"
            ),
        ),
        migrations.AddField(
            model_name="bprecord",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.country"
            ),
        ),
        migrations.AddField(
            model_name="bprecord",
            name="project_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.projecttype"
            ),
        ),
        migrations.AddField(
            model_name="bprecord",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.projectsector",
            ),
        ),
        migrations.AddField(
            model_name="bprecord",
            name="subsector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.projectsubsector",
            ),
        ),
        migrations.AddField(
            model_name="bprecord",
            name="substances",
            field=models.ManyToManyField(to="core.substance"),
        ),
    ]
