# Generated by Django 4.2 on 2023-10-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_bprecord_bprecordvalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blend",
            name="displayed_in_all",
            field=models.BooleanField(
                default=True, help_text="Controls all-years visibility."
            ),
        ),
        migrations.AddField(
            model_name="blend",
            name="displayed_in_latest_format",
            field=models.BooleanField(
                default=True, help_text="Controls current-year visibility."
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="displayed_in_all",
            field=models.BooleanField(
                default=True, help_text="Controls all-years visibility."
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="displayed_in_latest_format",
            field=models.BooleanField(
                default=True, help_text="Controls current-year visibility."
            ),
        ),
        migrations.AddField(
            model_name="usage",
            name="displayed_in_latest_format",
            field=models.BooleanField(
                default=True, help_text="Controls current-year visibility."
            ),
        ),
        migrations.AlterField(
            model_name="cprecord",
            name="country_programme_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cprecords",
                to="core.cpreport",
            ),
        ),
    ]
