# Generated by Django 4.2 on 2023-10-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_blend_displayed_in_all_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admcolumn",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.admcolumn",
            ),
        ),
    ]
