# Generated by Django 4.2 on 2023-10-12 12:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_admcolumn_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_year",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1985)]
                    ),
                ),
                (
                    "max_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1985)],
                    ),
                ),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="admcolumn",
            name="max_year",
        ),
        migrations.RemoveField(
            model_name="admcolumn",
            name="min_year",
        ),
        migrations.RemoveField(
            model_name="admrow",
            name="max_year",
        ),
        migrations.RemoveField(
            model_name="admrow",
            name="min_year",
        ),
        migrations.RemoveField(
            model_name="excludedusage",
            name="end_year",
        ),
        migrations.RemoveField(
            model_name="excludedusage",
            name="start_year",
        ),
        migrations.RemoveField(
            model_name="usage",
            name="displayed_in_latest_format",
        ),
        migrations.AlterField(
            model_name="usage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.usage",
            ),
        ),
        migrations.CreateModel(
            name="CPReportFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(max_length=10)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                (
                    "time_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.timeframe"
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usage"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="admcolumn",
            name="time_frame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.timeframe",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="admrow",
            name="time_frame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.timeframe",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="excludedusage",
            name="time_frame",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.timeframe",
            ),
            preserve_default=False,
        ),
    ]
