# Generated by Django 4.2 on 2023-10-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_timeframe_remove_admcolumn_max_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blend",
            name="displayed_in_all",
            field=models.BooleanField(
                default=False, help_text="Controls all-years visibility."
            ),
        ),
        migrations.AlterField(
            model_name="blend",
            name="displayed_in_latest_format",
            field=models.BooleanField(
                default=False, help_text="Controls current-year visibility."
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="displayed_in_all",
            field=models.BooleanField(
                default=False, help_text="Controls all-years visibility."
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="displayed_in_latest_format",
            field=models.BooleanField(
                default=False, help_text="Controls current-year visibility."
            ),
        ),
    ]
