# Generated by Django 4.2 on 2023-10-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_delaycategory_learnedlessoncategory_metaproject_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delaycategory",
            options={"verbose_name_plural": "Delay categories"},
        ),
        migrations.AlterModelOptions(
            name="learnedlessoncategory",
            options={"verbose_name_plural": "Learned lesson categories"},
        ),
        migrations.AlterModelOptions(
            name="pcrlearnedlessons",
            options={"verbose_name_plural": "Learned lessons"},
        ),
        migrations.AddField(
            model_name="cpreport",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("final", "Final")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
