# Generated by Django 4.2 on 2023-11-08 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_delaycategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPRecordArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                ("section", models.CharField(max_length=164)),
                (
                    "imports",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "import_quotas",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "exports",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "export_quotas",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "production",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                (
                    "manufacturing_blends",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=25, null=True
                    ),
                ),
                ("banned_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("source_file", models.CharField(max_length=248)),
                (
                    "blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.blend",
                    ),
                ),
            ],
            options={
                "verbose_name": "CP record archive",
                "verbose_name_plural": "CP records archive",
                "db_table": "cp_record_archive",
            },
        ),
        migrations.AddField(
            model_name="cpreport",
            name="version",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="country_programme_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cpemissions",
                to="core.cpreport",
            ),
        ),
        migrations.AlterField(
            model_name="cpgeneration",
            name="country_programme_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cpgenerations",
                to="core.cpreport",
            ),
        ),
        migrations.AlterField(
            model_name="cpprices",
            name="country_programme_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="core.cpreport",
            ),
        ),
        migrations.CreateModel(
            name="CPUsageArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=15, max_digits=25)),
                (
                    "country_programme_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_usages",
                        to="core.cprecordarchive",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.usage"
                    ),
                ),
            ],
            options={
                "verbose_name": "CP usage archive",
                "verbose_name_plural": "CP usages archive",
                "db_table": "cp_usage_archive",
            },
        ),
        migrations.CreateModel(
            name="CPReportArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=248)),
                ("year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("final", "Final")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("version", models.FloatField(default=1)),
                (
                    "reporting_entry",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                (
                    "reporting_email",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date of creation of the report archive",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.country"
                    ),
                ),
            ],
            options={
                "verbose_name": "CP report archive",
                "verbose_name_plural": "CP reports archive",
                "db_table": "cp_report_archive",
            },
        ),
        migrations.AddField(
            model_name="cprecordarchive",
            name="country_programme_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cprecords",
                to="core.cpreportarchive",
            ),
        ),
        migrations.AddField(
            model_name="cprecordarchive",
            name="substance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.substance",
            ),
        ),
        migrations.CreateModel(
            name="CPPricesArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("source_file", models.CharField(max_length=248)),
                (
                    "previous_year_price",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                (
                    "current_year_price",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                (
                    "blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.blend",
                    ),
                ),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cpreportarchive",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
            ],
            options={
                "verbose_name": "CP price archive",
                "verbose_name_plural": "CP prices archive",
                "db_table": "cp_prices_archive",
            },
        ),
        migrations.CreateModel(
            name="CPGenerationArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "all_uses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for all uses",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "feedstock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for feedstock uses within your country",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "destruction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for destruction",
                        max_digits=25,
                        null=True,
                    ),
                ),
                ("source_file", models.CharField(max_length=248)),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cpreportarchive",
                    ),
                ),
            ],
            options={
                "verbose_name": "CP generation archive",
                "verbose_name_plural": "CP generations archive",
                "db_table": "cp_generation_archive",
            },
        ),
        migrations.CreateModel(
            name="CPEmissionArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility",
                    models.CharField(
                        help_text="Facility name or identifier", max_length=256
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Total amount generated",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "all_uses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount generated and captured - For all uses",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "feedstock_gc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount generated and captured - For feedstock use in your country",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "destruction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount generated and captured - For destruction",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "feedstock_wpc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for feedstock uses within your country",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "destruction_wpc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount used for feedstock without prior capture",
                        max_digits=25,
                        null=True,
                    ),
                ),
                (
                    "generated_emissions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Captured for destruction",
                        max_digits=25,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("source_file", models.CharField(max_length=248)),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cpreportarchive",
                    ),
                ),
            ],
            options={
                "verbose_name": "CP emission archive",
                "verbose_name_plural": "CP emissions archive",
                "db_table": "cp_emission_archive",
            },
        ),
    ]
