# Generated by Django 4.2 on 2023-11-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_cprecordarchive_cpreport_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Decisions",
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("open", "Open"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Meetings",
            },
        ),
        migrations.CreateModel(
            name="ProjectCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("substance_type", models.CharField(max_length=255)),
                ("sort_order", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectRBMMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RBMMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "RBM Measure",
                "verbose_name_plural": "RBM Measures",
            },
        ),
        migrations.RenameField(
            model_name="project",
            old_name="fund_disbursed_13",
            new_name="fund_disbursed_psc",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="number",
            new_name="serial_number",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="ods_phasedout",
            new_name="substance_phasedout",
        ),
        migrations.RenameField(
            model_name="projectfund",
            old_name="support_13",
            new_name="support_psc",
        ),
        migrations.RenameField(
            model_name="submissionamount",
            old_name="amount_13",
            new_name="amount_psc",
        ),
        migrations.RemoveField(
            model_name="project",
            name="approval_meeting_no",
        ),
        migrations.RemoveField(
            model_name="project",
            name="decisions",
        ),
        migrations.RemoveField(
            model_name="submissionamount",
            name="submission",
        ),
        migrations.AddField(
            model_name="metaproject",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="agency_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="contingency_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="correspondance_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="date_approved",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="date_of_revision",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="date_received",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="funds_allocated",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="incomplete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="issue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="issue_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="plus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="programme_officer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="reviewed_mfs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="revision_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="source_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="submission_category",
            field=models.CharField(
                choices=[
                    ("bilateral cooperation", "Bilateral cooperation"),
                    ("investment project", "Investment project"),
                    ("work programme amendment", "Work programme amendment"),
                    (
                        "other doc: cpg, policy paper, business plan",
                        "Other doc: CPG, policy paper, business plan",
                    ),
                ],
                max_length=164,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="submission_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="submission_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="substance_category",
            field=models.CharField(
                blank=True,
                choices=[("consumption", "Consumption"), ("production", "Production")],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="support_cost_13",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="total_fund_approved",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="total_fund_transferred",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="total_grant",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="total_psc_cost",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="total_psc_transferred",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="tranche",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="withdrawn",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submissionamount",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProjectSubmission",
        ),
        migrations.AddField(
            model_name="projectrbmmeasure",
            name="measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_measures",
                to="core.rbmmeasure",
            ),
        ),
        migrations.AddField(
            model_name="projectrbmmeasure",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rbm_measures",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.meeting"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="approval_meeting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_projects",
                to="core.meeting",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.projectcluster",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="decision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.decision",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meeting_transf",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferred_projects",
                to="core.meeting",
            ),
        ),
    ]
