# Generated by Django 4.2 on 2023-11-15 10:42

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_cprecordarchive_cpreport_version_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bprecord",
            old_name="reason_for_exceding",
            new_name="reason_for_exceeding",
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/home/kiro/PycharmProjects/ors/.fs/protected_media"
                    )
                ),
                upload_to="project_files/",
            ),
        ),
    ]
