# Generated by Django 4.2 on 2023-11-15 11:10

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_cprecordarchive_cpreport_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath(
                        "/home/kiro/PycharmProjects/ors/.fs/protected_media"
                    )
                ),
                upload_to="project_files/",
            ),
        ),
        migrations.CreateModel(
            name="AdmRecordArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("section", models.CharField(max_length=10)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=248, null=True),
                ),
                (
                    "blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.blend",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.admcolumn",
                    ),
                ),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adm_records",
                        to="core.cpreportarchive",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.admrow"
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
                (
                    "value_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.admchoice",
                    ),
                ),
            ],
            options={
                "db_table": "cp_admrecord_archive",
            },
        ),
    ]
