# Generated by Django 4.2 on 2023-11-22 07:24

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_alter_projectfile_file_admrecordarchive"),
    ]

    operations = [
        migrations.AddField(
            model_name="admchoice",
            name="text_label",
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
        migrations.AddField(
            model_name="admchoice",
            name="with_text",
            field=models.BooleanField(default=False),
        ),
    ]
