# Generated by Django 4.2 on 2023-11-17 09:14

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    BusinessPlan = apps.get_model("core", "BusinessPlan")
    db_alias = schema_editor.connection.alias
    for bp in BusinessPlan.objects.using(db_alias).all():
        bp.agencies.add(bp.agency)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_alter_projectfile_file_admrecordarchive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bprecord",
            old_name="reason_for_exceding",
            new_name="reason_for_exceeding",
        ),
        migrations.AddField(
            model_name="businessplan",
            name="agencies",
            field=models.ManyToManyField(to="core.agency"),
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="businessplan",
            name="agency",
        ),
    ]
