# Generated by Django 4.2 on 2023-11-21 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_alter_projectfile_file_admrecordarchive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bprecord",
            old_name="reason_for_exceding",
            new_name="reason_for_exceeding",
        ),
    ]
