# Generated by Django 4.2 on 2023-11-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_decision_meeting_projectcluster_projectrbmmeasure_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="substance_category",
        ),
        migrations.AddField(
            model_name="project",
            name="compliance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Energy Efficieny", "Energy Efficieny"),
                    ("Non-Energey Efficiency", "Non-Energey Efficiency"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
