# Generated by Django 4.2 on 2023-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0058_rename_reason_for_exceding_bprecord_reason_for_exceeding_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="businessplan",
            name="source_file",
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
    ]
