# Generated by Django 4.2 on 2023-11-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_remove_project_substance_category_project_compliance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="substance_type",
            field=models.CharField(
                choices=[
                    ("HCFC", "HCFC"),
                    ("HFC", "HFC"),
                    ("BOTH", "Both"),
                    ("HFC_Plus", "HFC_Plus"),
                ],
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="projectcluster",
            name="substance_type",
            field=models.CharField(
                choices=[
                    ("HCFC", "HCFC"),
                    ("HFC", "HFC"),
                    ("BOTH", "Both"),
                    ("HFC_Plus", "HFC_Plus"),
                ],
                max_length=255,
            ),
        ),
    ]
