# Generated by Django 4.2 on 2023-11-27 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_admchoice_text_label_admchoice_with_text_and_more"),
        ("core", "0058_rename_reason_for_exceding_bprecord_reason_for_exceeding"),
    ]

    operations = []
