# Generated by Django 4.2 on 2023-11-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_alter_project_substance_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="support_cost_13",
            new_name="support_cost_psc",
        ),
        migrations.AddField(
            model_name="rbmmeasure",
            name="sort_order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectfund",
            name="meeting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="rbmmeasure",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
