# Generated by Django 4.2 on 2023-12-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_decision_meeting_projectcluster_projectrbmmeasure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="subsector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.projectsubsector",
            ),
        ),
    ]
