# Generated by Django 4.2 on 2023-11-19 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_alter_projectfile_file_admrecordarchive"),
        ("core", "0060_rename_support_cost_13_project_support_cost_psc_and_more"),
    ]

    operations = []
