# Generated by Django 4.2 on 2023-12-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_alter_project_subsector"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="generated_code",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
