# Generated by Django 4.2 on 2023-11-20 13:21

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_merge_20231119_2142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="meeting_transf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferred_projects",
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="projectcomment",
            name="meeting_of_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PurePosixPath("/app/.fs/protected_media")
                ),
                upload_to="project_files/",
            ),
        ),
        migrations.AlterField(
            model_name="submissionamount",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission_amounts",
                to="core.project",
            ),
        ),
    ]
