# Generated by Django 4.2 on 2023-12-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_project_generated_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="subregion",
        ),
        migrations.AddField(
            model_name="country",
            name="import_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("Country", "Country"),
                    ("Region", "Region"),
                    ("Subregion", "Subregion"),
                ],
                default="Country",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.country",
            ),
        ),
    ]
