# Generated by Django 4.2 on 2023-12-19 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_remove_subregion_region_remove_country_subregion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.projectsector",
            ),
        ),
    ]
