# Generated by Django 4.2 on 2023-12-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_alter_project_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="additional_funding",
            field=models.BooleanField(default=False),
        ),
    ]
