# Generated by Django 4.2 on 2023-12-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_project_additional_funding"),
    ]

    operations = [
        migrations.AddField(
            model_name="blend",
            name="cp_report_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="substance",
            name="cp_report_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
