# Generated by Django 4.2 on 2024-01-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_alter_project_substance_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="substance_type",
            field=models.CharField(
                choices=[
                    ("CFC", "CFC"),
                    ("HCFC", "HCFC"),
                    ("HFC", "HFC"),
                    ("BOTH", "Both"),
                    ("Methyl Bromide", "Methyl Bromide"),
                    ("HFC_Plus", "HFC_Plus"),
                ],
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="projectcluster",
            name="substance_type",
            field=models.CharField(
                choices=[
                    ("CFC", "CFC"),
                    ("HCFC", "HCFC"),
                    ("HFC", "HFC"),
                    ("BOTH", "Both"),
                    ("Methyl Bromide", "Methyl Bromide"),
                    ("HFC_Plus", "HFC_Plus"),
                ],
                max_length=255,
            ),
        ),
    ]
