# Generated by Django 4.2 on 2024-01-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_remove_projectcluster_substance_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admcolumn",
            name="alt_display_name",
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
    ]
