# Generated by Django 4.2 on 2024-02-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0070_admcolumn_alt_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="meta_serial_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="serial_number_legacy",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
