# Generated by Django 4.2 on 2024-02-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_project_serial_number_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="blend",
            name="sort_order_sectionC",
            field=models.FloatField(
                blank=True, help_text="Sort order for section C", null=True
            ),
        ),
        migrations.AddField(
            model_name="substance",
            name="sort_order_sectionC",
            field=models.FloatField(
                blank=True, help_text="Sort order for section C", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blend",
            name="sort_order",
            field=models.FloatField(
                blank=True, help_text="General sort order", null=True
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="sort_order",
            field=models.FloatField(
                blank=True, help_text="General sort order", null=True
            ),
        ),
    ]
