# Generated by Django 4.2 on 2024-02-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_blend_sort_order_sectionc_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CPReportFormat",
            new_name="CPReportFormatColumn",
        ),
        migrations.RemoveField(
            model_name="blend",
            name="displayed_in_all",
        ),
        migrations.RemoveField(
            model_name="blend",
            name="displayed_in_latest_format",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="displayed_in_all",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="displayed_in_latest_format",
        ),
        migrations.RemoveField(
            model_name="substance",
            name="sort_order_sectionC",
        ),
        migrations.CreateModel(
            name="CPReportFormatRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(max_length=10)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                (
                    "blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.blend",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.substance",
                    ),
                ),
                (
                    "time_frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.timeframe"
                    ),
                ),
            ],
        ),
    ]
