# Generated by Django 4.2 on 2024-03-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_rename_cpreportformat_cpreportformatcolumn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmEmptyImmutableCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(max_length=10)),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immutable_cells",
                        to="core.admcolumn",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immutable_cells",
                        to="core.admrow",
                    ),
                ),
            ],
        ),
    ]
