# Generated by Django 4.2 on 2024-03-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_admemptyimmutablecell"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_a2",
            field=models.BooleanField(default=False),
        ),
    ]
