# Generated by Django 4.2 on 2024-03-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_country_is_a2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bprecord",
            old_name="sector_subsector",
            new_name="legacy_sector_and_subsector",
        ),
        migrations.AddField(
            model_name="bprecord",
            name="legacy_project_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bprecord",
            name="project_cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.projectcluster",
            ),
        ),
    ]
