# Generated by Django 4.2 on 2024-03-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_country_is_a2"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpreportformatcolumn",
            name="header_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
