# Generated by Django 4.2 on 2024-03-21 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_cpreportformatcolumn_header_name"),
        (
            "core",
            "0076_rename_sector_subsector_bprecord_legacy_sector_and_subsector_and_more",
        ),
    ]

    operations = []
