# Generated by Django 4.2 on 2024-03-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_merge_20240321_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="blend",
            name="is_legacy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blend",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
