# Generated by Django 4.2 on 2024-04-03 06:37

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_cpreport_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_agency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_country_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_secretariat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_stakeholder",
            field=models.BooleanField(default=False),
        ),
    ]
