# Generated by Django 4.2 on 2024-04-04 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_cpreport_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpreport",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who created the report",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_cp_reports",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cpreport",
            name="event_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="last_updated_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who last updated the report",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_cp_reports",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who created the report",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_cp_reports_archive",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="event_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="last_updated_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who last updated the report",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_cp_reports_archive",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cpreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date of creation of the report"
            ),
        ),
        migrations.AlterField(
            model_name="cpreport",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("final", "Final")],
                default="final",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cpreportarchive",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date of creation of the report"
            ),
        ),
        migrations.AlterField(
            model_name="cpreportarchive",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("final", "Final")],
                default="final",
                max_length=10,
            ),
        ),
    ]
