# Generated by Django 4.2 on 2024-04-12 11:22

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_country_programme_reported_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpreport",
            name="comment_country",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_secretariat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_country",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_secretariat",
            field=models.TextField(blank=True, null=True),
        ),
    ]
