# Generated by Django 4.2 on 2024-04-11 07:06

import core.models.country_programme
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_country_programme_reported_sections"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.country_programme.CPFile.upload_path
                    ),
                ),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpfiles",
                        to="core.cpreport",
                    ),
                ),
            ],
        ),
    ]
