# Generated by Django 4.2 on 2024-04-15 10:03

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_cpreport_comment_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpreport",
            name="last_updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date when the report was last updated"
            ),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="last_updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date when the report was last updated"
            ),
        ),
    ]
