# Generated by Django 4.2 on 2024-04-17 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_blend_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpreport",
            name="event_description",
        ),
        migrations.RemoveField(
            model_name="cpreport",
            name="last_updated_by",
        ),
        migrations.RemoveField(
            model_name="cpreportarchive",
            name="event_description",
        ),
        migrations.RemoveField(
            model_name="cpreportarchive",
            name="last_updated_by",
        ),
        migrations.CreateModel(
            name="CPHistoryArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of creation of the event"
                    ),
                ),
                ("event_description", models.TextField(blank=True, null=True)),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cphistory",
                        to="core.cpreportarchive",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated the report",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_cp_reports_archive",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CPHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of creation of the event"
                    ),
                ),
                ("event_description", models.TextField(blank=True, null=True)),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cphistory",
                        to="core.cpreport",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated the report",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_cp_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
