# Generated by Django 4.2 on 2024-04-17 14:52

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_remove_cpreport_event_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPReportSectionsArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reported_section_a", models.BooleanField(default=False)),
                ("reported_section_b", models.BooleanField(default=False)),
                ("reported_section_c", models.BooleanField(default=False)),
                ("reported_section_d", models.BooleanField(default=False)),
                ("reported_section_e", models.BooleanField(default=False)),
                ("reported_section_f", models.BooleanField(default=False)),
                (
                    "country_programme_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpreportedsections",
                        to="core.cpreportarchive",
                    ),
                ),
            ],
        ),
    ]
