# Generated by Django 4.2 on 2024-04-11 13:54

import core.models.base_country_programme
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_remove_cpreport_event_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPFileArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.base_country_programme.AbstractCPFile.upload_path
                    ),
                ),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpfiles",
                        to="core.cpreportarchive",
                    ),
                ),
            ],
            options={
                "verbose_name": "CP file archive",
                "verbose_name_plural": "CP files archive",
                "db_table": "cp_file_archive",
            },
        ),
        migrations.CreateModel(
            name="CPFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.base_country_programme.AbstractCPFile.upload_path
                    ),
                ),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpfiles",
                        to="core.cpreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "CP file",
                "verbose_name_plural": "CP files",
                "db_table": "cp_file",
            },
        ),
    ]
