# Generated by Django 4.2.11 on 2024-04-22 10:37

import core.models.country_programme
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_remove_cpreport_event_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of file upload"
                    ),
                ),
                ("year", models.IntegerField()),
                ("filename", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.country_programme.CPFile.upload_path
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpfiles",
                        to="core.country",
                    ),
                ),
            ],
        ),
    ]
