# Generated by Django 4.2 on 2024-04-18 10:13

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_cpreportsectionsarchive"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CPHistoryArchive",
        ),
    ]
