# Generated by Django 4.2 on 2024-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_cpreportsectionsarchive"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CPHistoryArchive",
        ),
        migrations.AddField(
            model_name="cphistory",
            name="report_version",
            field=models.FloatField(default=1),
        ),
    ]
