# Generated by Django 4.2.11 on 2024-04-23 06:40

import core.models.country_programme
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_delete_cphistoryarchive"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of file upload"
                    ),
                ),
                ("year", models.IntegerField()),
                ("filename", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PurePosixPath("/app/.fs/protected_media")
                        ),
                        upload_to=core.models.country_programme.CPFile.upload_path,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpfiles",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="cpfile",
            constraint=models.UniqueConstraint(
                fields=("country", "year", "filename"),
                name="unique_country_year_filename",
            ),
        ),
    ]
