# Generated by Django 4.2 on 2024-04-23 09:45

import core.models.country_programme
import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_cpfile_cpfile_unique_country_year_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="cphistory",
            name="reporting_officer_email",
            field=models.EmailField(blank=True, max_length=248),
        ),
        migrations.AddField(
            model_name="cphistory",
            name="reporting_officer_name",
            field=models.CharField(blank=True, max_length=248),
        ),
    ]
