# Generated by Django 4.2.11 on 2024-04-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_cphistory_reporting_officer_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpreport",
            name="comment_country",
        ),
        migrations.RemoveField(
            model_name="cpreport",
            name="comment_secretariat",
        ),
        migrations.RemoveField(
            model_name="cpreportarchive",
            name="comment_country",
        ),
        migrations.RemoveField(
            model_name="cpreportarchive",
            name="comment_secretariat",
        ),
        migrations.CreateModel(
            name="CPCommentArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("section_a", "Section A"),
                            ("section_b", "Section B"),
                            ("section_c", "Section C"),
                            ("section_d", "Section D"),
                            ("section_e", "Section E"),
                            ("section_f", "Section F"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("comment_country", "Comment Country"),
                            ("comment_secretariat", "Comment Secretariat"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpcomments",
                        to="core.cpreportarchive",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CPComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("section_a", "Section A"),
                            ("section_b", "Section B"),
                            ("section_c", "Section C"),
                            ("section_d", "Section D"),
                            ("section_e", "Section E"),
                            ("section_f", "Section F"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("comment_country", "Comment Country"),
                            ("comment_secretariat", "Comment Secretariat"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "country_programme_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpcomments",
                        to="core.cpreport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
