# Generated by Django 4.2.11 on 2024-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_cphistory_reporting_officer_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cpreport",
            name="comment_country",
        ),
        migrations.RemoveField(
            model_name="cpreport",
            name="comment_secretariat",
        ),
        migrations.RemoveField(
            model_name="cpreportarchive",
            name="comment_country",
        ),
        migrations.RemoveField(
            model_name="cpreportarchive",
            name="comment_secretariat",
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_country_section_a",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_country_section_b",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_country_section_c",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_country_section_d",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_country_section_e",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_country_section_f",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_secretariat_section_a",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_secretariat_section_b",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_secretariat_section_c",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_secretariat_section_d",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_secretariat_section_e",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreport",
            name="comment_secretariat_section_f",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_country_section_a",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_country_section_b",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_country_section_c",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_country_section_d",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_country_section_e",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_country_section_f",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_secretariat_section_a",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_secretariat_section_b",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_secretariat_section_c",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_secretariat_section_d",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_secretariat_section_e",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="comment_secretariat_section_f",
            field=models.TextField(blank=True, null=True),
        ),
    ]
