# Generated by Django 4.2 on 2024-04-24 15:32

import core.models.country_programme
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_cphistory_reporting_officer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpreport",
            name="version_created_by",
            field=models.ForeignKey(
                default=None,
                help_text="User who created this report version",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_cp_reports_version",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="version_created_by",
            field=models.ForeignKey(
                default=None,
                help_text="User who created this archived report version",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_cp_reports_archive_version",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
