# Generated by Django 4.2 on 2024-04-26 09:47

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F


def migrate_addresses(apps, schema_editor):
    CPReport = apps.get_model("core", "CPReport")
    CPReportArchive = apps.get_model("core", "CPReportArchive")

    CPReport.objects.update(version_created_by=F("created_by"))
    CPReportArchive.objects.update(version_created_by=F("created_by"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_remove_cpreport_comment_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpreport",
            name="version_created_by",
            field=models.ForeignKey(
                default=None,
                help_text="User who created this report version",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_cp_reports_version",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cpreportarchive",
            name="version_created_by",
            field=models.ForeignKey(
                default=None,
                help_text="User who created this archived report version",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_cp_reports_archive_version",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_addresses, migrations.RunPython.noop),
    ]
