# Generated by Django 4.2.11 on 2024-05-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_cpreport_version_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="consumption_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="country",
            name="consumption_group",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
