# Generated by Django 4.2.11 on 2024-05-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_country_consumption_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted", "Submitted"),
                    ("Need Changes", "Need Changes"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Draft",
                max_length=32,
            ),
        ),
    ]
