# Generated by Django 4.2.11 on 2024-05-23 12:07

import core.models.business_plan
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_alter_businessplan_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessplan",
            name="comment_agency",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="businessplan",
            name="comment_secretariat",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="BPFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of file upload"
                    ),
                ),
                (
                    "year_start",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1985)]
                    ),
                ),
                (
                    "year_end",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1985)]
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PurePosixPath("/app/.fs/protected_media")
                        ),
                        upload_to=core.models.business_plan.BPFile.upload_path,
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bpfiles",
                        to="core.agency",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="bpfile",
            constraint=models.UniqueConstraint(
                fields=("agency", "year_start", "year_end", "filename"),
                name="unique_agency_years_filename",
            ),
        ),
    ]
