# Generated by Django 4.2.11 on 2024-05-28 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_businessplan_comment_agency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessplan",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="BPHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of creation of the event"
                    ),
                ),
                ("event_description", models.TextField(blank=True)),
                ("bp_version", models.FloatField(default=1)),
                (
                    "business_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bphistory",
                        to="core.businessplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who updated the business plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_bp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
