# Generated by Django 4.2.11 on 2024-05-30 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_businessplan_version_bphistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessplan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date of creation of the business plan",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businessplan",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the business plan",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_business_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessplan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date of business plan last update", null=True
            ),
        ),
        migrations.AddField(
            model_name="businessplan",
            name="updated_by",
            field=models.ForeignKey(
                help_text="User who last updated the business plan",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_business_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
