# Generated by Django 4.2.11 on 2024-06-12 10:43

import core.models.business_plan
import core.models.country_programme
import core.models.replenishment
import core.models.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_businessplan_created_at_businessplan_created_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=5, max_digits=20)),
                ("date", models.DateField()),
                ("number", models.CharField(max_length=128, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="core.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("payment_for_year", models.CharField(max_length=16)),
                ("gain_or_loss", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "amount_local_currency",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                ("amount_usd", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Replenishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name="businessplan",
            name="feedback_file",
            field=models.FileField(
                blank=True,
                storage=core.models.utils.get_protected_storage,
                upload_to=core.models.business_plan.BusinessPlan.upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="cpfile",
            name="file",
            field=models.FileField(
                storage=core.models.utils.get_protected_storage,
                upload_to=core.models.country_programme.CPFile.upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file",
            field=models.FileField(
                storage=core.models.utils.get_protected_storage,
                upload_to="project_files/",
            ),
        ),
        migrations.CreateModel(
            name="PaymentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of payment file upload"
                    ),
                ),
                ("filename", models.CharField(max_length=128)),
                (
                    "file",
                    models.FileField(
                        storage=core.models.utils.get_protected_storage,
                        upload_to=core.models.replenishment.PaymentFile.upload_path,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("Bank Statement", "Bank Statement"),
                            ("Promissory Note", "Promissory Note"),
                        ],
                        default="Bank Statement",
                        max_length=32,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_files",
                        to="core.payment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="replenishment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="core.replenishment",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of invoice file upload"
                    ),
                ),
                ("filename", models.CharField(max_length=128)),
                (
                    "file",
                    models.FileField(
                        storage=core.models.utils.get_protected_storage,
                        upload_to=core.models.replenishment.InvoiceFile.upload_path,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("Invoice", "Invoice")],
                        default="Invoice",
                        max_length=16,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_files",
                        to="core.invoice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="replenishment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="core.replenishment",
            ),
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_in_local_currency", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=5, max_digits=20)),
                ("currency_of_payment", models.CharField(max_length=16)),
                (
                    "exchange_rate_six_months_prior",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                (
                    "bilateral_assistance_amount",
                    models.DecimalField(decimal_places=5, default=0, max_digits=20),
                ),
                (
                    "un_scale_of_assessment",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                (
                    "edited_scale_of_assessment",
                    models.DecimalField(decimal_places=5, max_digits=20, null=True),
                ),
                (
                    "average_contributor_inflation_rate",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                (
                    "edited_qualifies_for_fixed_rate_mechanism",
                    models.BooleanField(default=False),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="core.country",
                    ),
                ),
                (
                    "replenishment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributions",
                        to="core.replenishment",
                    ),
                ),
            ],
        ),
    ]
