# Generated by Django 4.2.11 on 2024-06-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_invoice_payment_replenishment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "agreed_contributions",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "cash_payments",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "bilateral_assistance",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "promissory_notes",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "outstanding_contributions",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="contribution",
            constraint=models.UniqueConstraint(
                fields=("replenishment", "country"), name="unique_replenishment_country"
            ),
        ),
        migrations.AddConstraint(
            model_name="replenishment",
            constraint=models.UniqueConstraint(
                fields=("start_year",), name="unique_start_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="replenishment",
            constraint=models.UniqueConstraint(
                fields=("end_year",), name="unique_end_year"
            ),
        ),
        migrations.AddField(
            model_name="contributionstatus",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributions_status",
                to="core.country",
            ),
        ),
        migrations.AddConstraint(
            model_name="contributionstatus",
            constraint=models.UniqueConstraint(
                fields=("country", "year"), name="unique_country_year"
            ),
        ),
    ]
