# Generated by Django 4.2.11 on 2024-07-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_invoice_payment_replenishment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blendaltname",
            name="blend",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alt_names",
                to="core.blend",
            ),
        ),
        migrations.AlterField(
            model_name="substancealtname",
            name="substance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alt_names",
                to="core.substance",
            ),
        ),
    ]
