# Generated by Django 4.2.11 on 2024-07-01 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_invoice_payment_replenishment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="substance",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the substance",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_substancess",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="substance",
            name="is_contained_in_polyols",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="substance",
            name="max_odp",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="substance",
            name="min_odp",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
