# Generated by Django 4.2.11 on 2024-07-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_contributionstatus_disputedcontribution_fermgainloss_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bprecord",
            name="bp_type",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="comment_agency",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="comment_secretariat",
        ),
        migrations.AddField(
            model_name="bprecord",
            name="comment_agency",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bprecord",
            name="comment_secretariat",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bprecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Approved"),
                    ("P", "Planned"),
                    ("R", "Rejected"),
                    ("U", "Undefined"),
                ],
                default="U",
                max_length=16,
            ),
        ),
    ]
