# Generated by Django 4.2.11 on 2024-07-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_contributionstatus_disputedcontribution_fermgainloss_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualContributionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agreed_contributions",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "cash_payments",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "bilateral_assistance",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "promissory_notes",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "outstanding_contributions",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                ("year", models.IntegerField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annual_contributions_status",
                        to="core.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TriennialContributionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agreed_contributions",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "cash_payments",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "bilateral_assistance",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "promissory_notes",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "outstanding_contributions",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triennial_contributions_status",
                        to="core.country",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Contribution",
            new_name="ScaleOfAssessment",
        ),
        migrations.DeleteModel(
            name="ContributionStatus",
        ),
        migrations.AddConstraint(
            model_name="triennialcontributionstatus",
            constraint=models.UniqueConstraint(
                fields=("country", "start_year", "end_year"),
                name="unique_country_start_year_end_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="annualcontributionstatus",
            constraint=models.UniqueConstraint(
                fields=("country", "year"), name="unique_country_year"
            ),
        ),
    ]
