# Generated by Django 4.2.11 on 2024-07-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_annualcontributionstatus_triennialcontributionstatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                ("undp", models.DecimalField(decimal_places=15, max_digits=30)),
                ("unep", models.DecimalField(decimal_places=15, max_digits=30)),
                ("unido", models.DecimalField(decimal_places=15, max_digits=30)),
                ("world_bank", models.DecimalField(decimal_places=15, max_digits=30)),
                (
                    "staff_contracts",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
                (
                    "treasury_fees",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
                (
                    "monitoring_fees",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
                (
                    "technical_audit",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
                (
                    "information_strategy",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "interest_earned",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
                (
                    "miscellaneous_income",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
