# Generated by Django 4.2.11 on 2024-07-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_externalallocation_externalincome"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryCEITStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.IntegerField()),
                ("end_year", models.ImageField(blank=True, null=True, upload_to="")),
                ("is_ceit", models.BooleanField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ceit_statuses",
                        to="core.country",
                    ),
                ),
            ],
        ),
    ]
