# Generated by Django 4.2.11 on 2024-07-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_externalallocation_externalincome"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScaleOfAssessmentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("is_final", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="scaleofassessment",
            name="unique_replenishment_country",
        ),
        migrations.RemoveField(
            model_name="scaleofassessment",
            name="replenishment",
        ),
        migrations.AddField(
            model_name="scaleofassessmentversion",
            name="replenishment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scales_of_assessment_versions",
                to="core.replenishment",
            ),
        ),
        migrations.AddField(
            model_name="scaleofassessment",
            name="version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scales_of_assessment",
                to="core.scaleofassessmentversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="scaleofassessment",
            constraint=models.UniqueConstraint(
                fields=("version", "country"), name="unique_version_country"
            ),
        ),
        migrations.AddConstraint(
            model_name="scaleofassessmentversion",
            constraint=models.UniqueConstraint(
                fields=("replenishment", "version"), name="unique_replenishment_version"
            ),
        ),
    ]
