# Generated by Django 4.2.11 on 2024-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_scaleofassessmentversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scaleofassessmentversion",
            name="decision_number",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="scaleofassessmentversion",
            name="meeting_number",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="scaleofassessment",
            name="un_scale_of_assessment",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
