# Generated by Django 4.2.11 on 2024-07-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_countryceitstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="date",
            new_name="date_of_issuance",
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="date_sent_out",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
