# Generated by Django 4.2.11 on 2024-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0104_rename_date_invoice_date_of_issuance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countryceitstatus",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
