# Generated by Django 4.2.11 on 2024-07-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_alter_countryceitstatus_end_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount_local_currency",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="amount_usd",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="gain_or_loss",
        ),
        migrations.AddField(
            model_name="payment",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="ferm_gain_or_loss",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_for_year",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="payment",
            name="replenishment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="core.replenishment",
            ),
        ),
    ]
