# Generated by Django 4.2.11 on 2024-07-24 09:15

# This migration is modified, because of a Django bug, the constraint is added before the field is created.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_remove_bprecord_bp_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScaleOfAssessmentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                ("is_final", models.BooleanField(default=False)),
                ("meeting_number", models.CharField(default="", max_length=32)),
                ("decision_number", models.CharField(default="", max_length=32)),
                ("comment", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="scaleofassessment",
            name="unique_replenishment_country",
        ),
        migrations.RemoveField(
            model_name="scaleofassessment",
            name="replenishment",
        ),
        migrations.AlterField(
            model_name="scaleofassessment",
            name="un_scale_of_assessment",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name="scaleofassessmentversion",
            name="replenishment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scales_of_assessment_versions",
                to="core.replenishment",
            ),
        ),
        migrations.AddField(
            model_name="scaleofassessment",
            name="version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scales_of_assessment",
                to="core.scaleofassessmentversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="scaleofassessmentversion",
            constraint=models.UniqueConstraint(
                fields=("replenishment", "version"), name="unique_replenishment_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="scaleofassessment",
            constraint=models.UniqueConstraint(
                fields=("version", "country"), name="unique_version_country"
            ),
        ),
    ]
