# Generated by Django 4.2.11 on 2024-07-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_remove_bprecord_bp_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bprecord",
            name="blends",
        ),
    ]
