# Generated by Django 4.2.11 on 2024-07-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_rename_amount_local_currency_payment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency", "Agency"),
                    ("country_user", "Country user"),
                    ("secretariat", "Secretariat"),
                    ("stakeholder", "Stakeholder"),
                    ("treasurer", "Treasurer"),
                ],
                max_length=50,
            ),
        ),
    ]
