# Generated by Django 4.2.11 on 2024-07-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_alter_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bprecord",
            name="blends",
        ),
    ]
