# Generated by Django 4.2.11 on 2024-07-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessplan",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="agency_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency_inputter", "Agency inputter"),
                    ("agency_submitter", "Agency submitter"),
                ],
                max_length=50,
            ),
        ),
    ]
