# Generated by Django 4.2.11 on 2024-07-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_remove_bprecord_blends"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessplan",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency_inputter", "Agency inputter"),
                    ("agency_submitter", "Agency submitter"),
                    ("country_user", "Country user"),
                    ("secretariat", "Secretariat"),
                    ("stakeholder", "Stakeholder"),
                    ("treasurer", "Treasurer"),
                ],
                max_length=50,
            ),
        ),
    ]
