# Generated by Django 4.2.11 on 2024-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_businessplan_name_user_agency_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("Agency Draft", "Agency Draft"),
                    ("Secretariat Draft", "Secretariat Draft"),
                    ("Submitted", "Submitted"),
                    ("Need Changes", "Need Changes"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Agency Draft",
                max_length=32,
            ),
        ),
    ]
