# Generated by Django 4.2.11 on 2024-07-31 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_alter_businessplan_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="disputedcontribution",
            name="unique_year",
        ),
        migrations.AddField(
            model_name="disputedcontribution",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="disputedcontribution",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="disputed_contributions",
                to="core.country",
            ),
        ),
        migrations.AddConstraint(
            model_name="disputedcontribution",
            constraint=models.UniqueConstraint(
                fields=("country", "year"), name="unique_disputed_country_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="disputedcontribution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("country", None)),
                fields=("year",),
                name="unique_year",
            ),
        ),
    ]
