# Generated by Django 4.2.11 on 2024-07-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_alter_businessplan_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BPRecord",
            new_name="BPActivity",
        ),
        migrations.RenameModel(
            old_name="BPRecordValue",
            new_name="BPActivityValue",
        ),
    ]
