# Generated by Django 4.2.11 on 2024-08-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_rename_bprecord_bpactivity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bpactivity",
            options={"verbose_name_plural": "Bp activities"},
        ),
        migrations.RenameField(
            model_name="bpactivityvalue",
            old_name="bp_record",
            new_name="bp_activity",
        ),
        migrations.AlterField(
            model_name="bpactivity",
            name="business_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="core.businessplan",
            ),
        ),
    ]
