# Generated by Django 4.2.11 on 2024-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_alter_bpactivity_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="bpactivity",
            name="comment_types",
            field=models.ManyToManyField(blank=True, to="core.commenttype"),
        ),
    ]
