# Generated by Django 4.2.11 on 2024-08-05 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_commenttype_bpactivity_comment_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsector",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the sector",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_sectors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectsector",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                help_text="Custom sector created by user, not from the official list.",
            ),
        ),
        migrations.AddField(
            model_name="projectsubsector",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the subsector",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_subsectors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectsubsector",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                help_text="Custom sector created by user, not from the official list.",
            ),
        ),
    ]
