# Generated by Django 4.2.11 on 2024-08-06 10:47

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    BusinessPlan = apps.get_model("core", "BusinessPlan")
    db_alias = schema_editor.connection.alias

    # Delete all business plans and related activities/activity values
    BusinessPlan.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_projectsector_created_by_projectsector_is_custom_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AddField(
            model_name="bpactivityvalue",
            name="is_after",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="bpactivityvalue",
            constraint=models.UniqueConstraint(
                fields=("bp_activity", "year", "is_after"),
                name="unique_activity_year_is_after",
            ),
        ),
    ]
