# Generated by Django 4.2.11 on 2024-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_bpactivityvalue_is_after_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessplan",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="bphistory",
            name="bp_version",
            field=models.IntegerField(default=1),
        ),
    ]
