# Generated by Django 4.2.11 on 2024-08-09 06:42

import core.import_data.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_bpactivityvalue_is_after_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessplan",
            name="is_latest",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="bphistory",
            name="bp_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="businessplan",
            name="created_by",
            field=models.ForeignKey(
                default=core.import_data.utils.get_import_user_id,
                help_text="User who created the business plan",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_business_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="businessplan",
            name="updated_by",
            field=models.ForeignKey(
                default=core.import_data.utils.get_import_user_id,
                help_text="User who last updated the business plan",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_business_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
