# Generated by Django 4.2.11 on 2024-08-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0119_businessplan_is_latest_alter_bphistory_bp_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="bpactivity",
            name="initial_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bpactivity",
            name="is_updated",
            field=models.BooleanField(default=False),
        ),
    ]
