# Generated by Django 4.2.11 on 2024-08-16 10:59

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    CPHistory = apps.get_model("core", "CPHistory")
    distinct_report_versions = (
        CPHistory.objects.order_by("country_programme_report", "report_version")
        .distinct("country_programme_report", "report_version")
        .values_list("country_programme_report_id", "report_version")
    )
    for report, version in distinct_report_versions:
        history_group = CPHistory.objects.filter(
            country_programme_report_id=report, report_version=version
        )
        final_transition = history_group.filter(
            event_description__in=[
                "Status changed from draft to final",
                "Status updated from draft to final",
            ]
        ).first()
        if final_transition:
            history_group = history_group.filter(
                created_at__gte=final_transition.created_at
            )

        history_group.update(event_in_draft=False)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_bpactivity_initial_id_bpactivity_is_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="cphistory",
            name="event_in_draft",
            field=models.BooleanField(
                default=True,
                help_text="Indicate whether history entry was created while in Draft",
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
