# Generated by Django 4.2.11 on 2024-08-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0121_cphistory_event_in_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpprices",
            name="is_fob",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cpprices",
            name="is_retail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cppricesarchive",
            name="is_fob",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cppricesarchive",
            name="is_retail",
            field=models.BooleanField(default=False),
        ),
    ]
