# Generated by Django 4.2.11 on 2024-08-19 15:26

import core.models.replenishment
import core.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0121_cphistory_event_in_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="scaleofassessmentversion",
            name="decision_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models.utils.get_protected_storage,
                upload_to=core.models.replenishment.ScaleOfAssessmentVersion.upload_path,
            ),
        ),
    ]
