# Generated by Django 4.2.11 on 2024-08-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0122_scaleofassessmentversion_decision_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpprices",
            name="is_fob",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cpprices",
            name="is_retail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cppricesarchive",
            name="is_fob",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cppricesarchive",
            name="is_retail",
            field=models.BooleanField(default=False),
        ),
    ]
