# Generated by Django 4.2.11 on 2024-08-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0123_cpprices_is_fob_cpprices_is_retail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalincome",
            name="_singleton",
        ),
        # These defaults are only used for the migration to work
        migrations.AddField(
            model_name="externalincome",
            name="end_year",
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="externalincome",
            name="start_year",
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="externalincome",
            constraint=models.UniqueConstraint(
                fields=("start_year",), name="unique_start_year_external_income"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalincome",
            constraint=models.UniqueConstraint(
                fields=("end_year",), name="unique_end_year_external_income"
            ),
        ),
    ]
