# Generated by Django 4.2.11 on 2024-08-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0123_cpprices_is_fob_cpprices_is_retail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalincome",
            name="_singleton",
        ),
        # These defaults are only for the migration to work, they won't
        # be needed when reimporting the data
        migrations.AddField(
            model_name="externalincome",
            name="end_year",
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="externalincome",
            name="start_year",
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
