# Generated by Django 4.2.11 on 2024-08-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0127_alter_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="code",
            new_name="legacy_code",
        ),
        migrations.AddField(
            model_name="project",
            name="bp_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="core.bpactivity",
            ),
        ),
    ]
