# Generated by Django 4.2.11 on 2024-08-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0127_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="invoices",
            field=models.ManyToManyField(related_name="payments", to="core.invoice"),
        ),
    ]
