# Generated by Django 4.2.11 on 2024-09-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0128_payment_invoices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="replenishment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="core.replenishment",
            ),
        ),
    ]
