# Generated by Django 4.2.11 on 2024-08-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0128_rename_code_project_legacy_code_project_bp_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="generated_code",
            new_name="code",
        ),
    ]
