# Generated by Django 4.2.11 on 2024-09-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0132_alter_payment_invoices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cphistory",
            options={"ordering": ["-created_at"], "verbose_name_plural": "CP history"},
        ),
    ]
