# Generated by Django 4.2.11 on 2024-09-11 14:19

from django.db import migrations


def update_draft_history_for_final_versions(apps, schema_editor):
    """
    Due to a bug, when creating a FINAL version without going through DRAFT first,
    the resulting history entry was created with event_in_draft == True.
    This data migration corrects that for already-created versions.
    """
    CPReport = apps.get_model("core", "CPReportArchive")
    CPHistory = apps.get_model("core", "CPHistory")

    # Only updating the 2023 FINAL reports as these are being edited at the time of
    # executing this migration and older reports do not have histories.
    distinct_report_versions = (
        CPHistory.objects.select_related("cp_reports")
        .filter(
            country_programme_report__year=2023,
            country_programme_report__status=CPReport.CPReportStatus.FINAL,
        )
        .order_by("country_programme_report", "report_version")
        .distinct("country_programme_report", "report_version")
        .values_list("country_programme_report_id", "report_version")
    )
    for report_id, version in distinct_report_versions:
        history_group = CPHistory.objects.filter(
            country_programme_report_id=report_id, report_version=version
        ).order_by("-created_at")
        last_transition = history_group.first()
        if last_transition and last_transition.event_in_draft:
            last_transition.event_in_draft = False
            last_transition.save(update_fields=["event_in_draft"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0133_alter_cphistory_options"),
    ]

    operations = [
        migrations.RunPython(
            update_draft_history_for_final_versions, migrations.RunPython.noop
        ),
    ]
