# Generated by Django 4.2.11 on 2024-09-12 09:24

from datetime import timedelta

from django.db import migrations


def update_archives_created_at(apps, schema_editor):
    """
    `created_at` dates for archived reports were incorrect due to the original date
    being overwritten at archive creation.

    This data migration attempts to fix this for existing archives by using the dates
    from the report histories.

    Logically assumes that report archives can only be in FINAL mode.
    """
    CPReportArchive = apps.get_model("core", "CPReportArchive")
    CPHistory = apps.get_models("core", "CPHistory")

    for archive in CPReportArchive.objects.all():
        try:
            latest_version_history = CPHistory.objects.filter(
                country_programme_report__country_id=archive.country_id,
                country_programme_report__year=archive.year,
                report_version=archive.version,
            ).latest("created_at")
        except:
            # Pretty hard to use DoesNotExist without fully initialized models
            continue
        if archive.created_at - latest_version_history.created_at > timedelta(seconds=1):
            archive.created_at = latest_version_history.created_at
            archive.save(update_fields=["created_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0134_update_draft_history_for_final_versions"),
    ]

    operations = [
        migrations.RunPython(
            update_archives_created_at, migrations.RunPython.noop
        ),
    ]
