# Generated by Django 4.2.11 on 2024-09-23 13:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0137_fermgainloss_year_alter_fermgainloss_country_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="externalincome",
            name="unique_start_year_external_income",
        ),
        migrations.RemoveConstraint(
            model_name="externalincome",
            name="unique_end_year_external_income",
        ),
        migrations.AddField(
            model_name="externalincome",
            name="agency_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="externalincome",
            name="interest_earned",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalincome",
            name="miscellaneous_income",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
    ]
