# Generated by Django 4.2.11 on 2024-09-23 11:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0137_fermgainloss_year_alter_fermgainloss_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalincome",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agency_incomes",
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="externalincome",
            name="interest_earned",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalincome",
            name="miscellaneous_income",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
    ]
