# Generated by Django 4.2.11 on 2024-09-24 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0138_remove_externalincome_unique_start_year_external_income_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIncomeAnnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "interest_earned",
                    models.DecimalField(
                        decimal_places=15, default=Decimal("0"), max_digits=30
                    ),
                ),
                (
                    "miscellaneous_income",
                    models.DecimalField(
                        decimal_places=15, default=Decimal("0"), max_digits=30
                    ),
                ),
                ("agency_name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="externalincome",
            name="agency_name",
        ),
    ]
