# Generated by Django 4.2.11 on 2024-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0139_externalincomeannual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scaleofassessment",
            name="opted_for_ferm",
            field=models.BooleanField(null=True),
        ),
    ]
