# Generated by Django 4.2.11 on 2024-09-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0140_scaleofassessment_opted_for_ferm"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_arrears",
            field=models.BooleanField(default=False),
        ),
    ]
