# Generated by Django 4.2.11 on 2024-10-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0141_invoice_is_arrears"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW final_reports_view AS
            WITH draft_reports AS
            (SELECT CONCAT(cp_report.country_id, '_', cp_report.year, '_', cp_report.version-1) AS cntr_year
            FROM cp_report
            WHERE status='draft')
            (SELECT cp_report.id,
                    cp_report.created_at,
                    cp_report.name,
                    cp_report.year,
                    cp_report.status,
                    cp_report.version,
                    cp_report.reporting_entry,
                    cp_report.reporting_email,
                    cp_report.submission_date,
                    cp_report.comment,
                    cp_report.country_id,
                    cp_report.created_by_id,
                    cp_report.version_created_by_id,
                    FALSE AS is_archive
            FROM cp_report
            WHERE cp_report.status='final')
            UNION
            (SELECT cp_report_archive.id,
                    cp_report_archive.created_at,
                    cp_report_archive.name,
                    cp_report_archive.year,
                    cp_report_archive.status,
                    cp_report_archive.version,
                    cp_report_archive.reporting_entry,
                    cp_report_archive.reporting_email,
                    cp_report_archive.submission_date,
                    cp_report_archive.comment,
                    cp_report_archive.country_id,
                    cp_report_archive.created_by_id,
                    cp_report_archive.version_created_by_id,
                    TRUE AS is_archive
            FROM cp_report_archive
            WHERE (concat(cp_report_archive.country_id, '_', cp_report_archive.year, '_', cp_report_archive.version) in
                        (SELECT cntr_year
                        FROM draft_reports)))
            """,
            reverse_sql="DROP VIEW final_reports_view",
        )
    ]
