# Generated by Django 4.2.11 on 2024-09-30 11:25

from django.db import migrations


def forwards_func(apps, schema_editor):
    Country = apps.get_model("core", "Country")
    vatican = Country.objects.filter(name_alt="Holy See").first()
    if vatican:
        vatican.name_alt = "Vatican"
        vatican.save()


def backwards_func(apps, schema_editor):
    Country = apps.get_model("core", "Country")
    vatican = Country.objects.filter(name_alt="Vatican").first()
    if vatican:
        vatican.name_alt = "Holy See"
        vatican.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0141_invoice_is_arrears"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
