# Generated by Django 4.2.11 on 2024-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0142_holy_see_to_vatican"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalincomeannual",
            name="interest_earned_quarter_1",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="externalincomeannual",
            name="interest_earned_quarter_2",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="externalincomeannual",
            name="interest_earned_quarter_3",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="externalincomeannual",
            name="interest_earned_quarter_4",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=30, null=True
            ),
        ),
    ]
