# Generated by Django 4.2.11 on 2024-10-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0142_create_view_for_final_reports"),
        ("core", "0143_externalincomeannual_interest_earned_quarter_1_and_more"),
    ]

    operations = []
