# Generated by Django 4.2.11 on 2024-10-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0145_finalreportsview"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partially_paid", "Partially paid"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
