# Generated by Django 4.2.11 on 2024-10-04 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0146_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="country_programme_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cpemissions",
                to="core.cpreportarchive",
            ),
        ),
        migrations.AlterField(
            model_name="cpgenerationarchive",
            name="country_programme_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cpgenerations",
                to="core.cpreportarchive",
            ),
        ),
        migrations.AlterField(
            model_name="cppricesarchive",
            name="country_programme_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="core.cpreportarchive",
            ),
        ),
    ]
