# Generated by Django 4.2.11 on 2024-10-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0146_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="USD", max_length=64),
        ),
    ]
