# Generated by Django 4.2.11 on 2024-10-07 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Payment = apps.get_model("core", "Payment")
    for p in Payment.objects.all():
        p.payment_for_years = p.payment_for_year.split(",")
        p.save()


def backwards_func(apps, schema_editor):
    Payment = apps.get_model("core", "Payment")
    for p in Payment.objects.all():
        p.payment_for_year = ",".join(p.payment_for_years)
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0148_alter_cpemissionarchive_country_programme_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_for_year",
            field=models.CharField(max_length=64, blank=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_for_years",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10), default=list, size=None
            ),
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.RemoveField(
            model_name="payment",
            name="payment_for_year",
        ),
    ]
