# Generated by Django 4.2.11 on 2024-10-11 08:01

from django.db import migrations
from django.db.models import F


def forwards_func(apps, schema_editor):
    BPActivity = apps.get_model("core", "BPActivity")
    db_alias = schema_editor.connection.alias

    # Set initial_id=id for all activities
    BPActivity.objects.using(db_alias).update(initial_id=F("id"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0149_payment_payment_for_years"),
    ]

    operations = [migrations.RunPython(forwards_func, migrations.RunPython.noop)]
