# Generated by Django 4.2.11 on 2024-10-11 13:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    ExternalAllocation = apps.get_model("core", "ExternalAllocation")

    # Simply mark existing ExternalAllocation objects as legacy
    ExternalAllocation.objects.update(is_legacy=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0150_set_activity_initial_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalallocation",
            name="_singleton",
        ),
        migrations.AddField(
            model_name="externalallocation",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="externalallocation",
            name="is_legacy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="externalallocation",
            name="meeting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.meeting",
            ),
        ),
        migrations.AddField(
            model_name="externalallocation",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="externalallocation",
            name="information_strategy",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalallocation",
            name="monitoring_fees",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalallocation",
            name="staff_contracts",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalallocation",
            name="technical_audit",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalallocation",
            name="treasury_fees",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalallocation",
            name="undp",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalallocation",
            name="unep",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalallocation",
            name="unido",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="externalallocation",
            name="world_bank",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
