# Generated by Django 4.2.11 on 2024-10-14 15:57

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    ScaleOfAssessment = apps.get_model("core", "ScaleOfAssessment")
    Payment = apps.get_model("core", "Payment")

    # Only mark Payments with single year as ferm/not ferm based on SoA
    for payment in Payment.objects.all():
        years_list = [
            int(year)
            for year in payment.payment_for_years
            if year not in ["deferred", "arrears"]
        ]
        if len(years_list) == 1:
            s = ScaleOfAssessment.objects.filter(
                version__replenishment__start_year__lte=years_list[0],
                version__replenishment__end_year__gte=years_list[0],
                version__is_final=True,
                country=payment.country,
            ).first()
            if s and s.opted_for_ferm is not None:
                payment.is_ferm = s.opted_for_ferm
                payment.save(update_fields=["is_ferm"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0152_remove_externalincomeannual_interest_earned_quarter_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="is_ferm",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
