# Generated by Django 4.2.11 on 2024-10-15 07:58

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    ScaleOfAssessment = apps.get_model("core", "ScaleOfAssessment")
    Invoice = apps.get_model("core", "Invoice")

    # Only mark Invoices that are not arrears
    for invoice in Invoice.objects.all():
        if invoice.year and not invoice.is_arrears:
            s = ScaleOfAssessment.objects.filter(
                version__replenishment__start_year__lte=invoice.year,
                version__replenishment__end_year__gte=invoice.year,
                version__is_final=True,
                country=invoice.country,
            ).first()
            if s and s.opted_for_ferm is not None:
                invoice.is_ferm = s.opted_for_ferm
                invoice.save(update_fields=["is_ferm"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0153_payment_is_ferm"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_ferm",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
