# Generated by Django 4.2.11 on 2024-10-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0154_invoice_is_ferm"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualcontributionstatus",
            name="bilateral_assistance_decision_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="annualcontributionstatus",
            name="bilateral_assistance_meeting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.meeting",
            ),
        ),
        migrations.AddField(
            model_name="disputedcontribution",
            name="decision_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="disputedcontribution",
            name="meeting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.meeting",
            ),
        ),
        migrations.AddField(
            model_name="triennialcontributionstatus",
            name="bilateral_assistance_decision_number",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="triennialcontributionstatus",
            name="bilateral_assistance_meeting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.meeting",
            ),
        ),
    ]
