# Generated by Django 4.2.11 on 2024-10-21 11:27

import core.models.replenishment
import core.models.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0155_annualcontributionstatus_bilateral_assistance_decision_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusOfTheFundFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(null=True)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of file upload"
                    ),
                ),
                ("filename", models.CharField(max_length=128)),
                (
                    "file",
                    models.FileField(
                        storage=core.models.utils.get_protected_storage,
                        upload_to=core.models.replenishment.StatusOfTheFundFile.upload_path,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.meeting",
                    ),
                ),
            ],
        ),
    ]
