# Generated by Django 4.2.11 on 2024-10-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0156_statusofthefundfile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="amount_assessed",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="invoices",
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="core.invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_received",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
