# Generated by Django 4.2.11 on 2024-10-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0157_rename_amount_payment_amount_assessed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount_local_currency",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
