# Generated by Django 4.2.11 on 2024-10-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0158_payment_amount_local_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("partially_paid", "Partially paid"), ("paid", "Paid")],
                default="paid",
                max_length=20,
            ),
        ),
    ]
