# Generated by Django 4.2.11 on 2024-10-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0160_rename_amount_invoice_amount_local_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="amount_local_currency",
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
