# Generated by Django 4.2.11 on 2024-10-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0161_alter_invoice_amount_local_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(max_length=128),
        ),
    ]
