# Generated by Django 4.2.11 on 2024-10-28 13:25

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Agency = apps.get_model("core", "Agency")
    ExternalIncomeAnnual = apps.get_model("core", "ExternalIncomeAnnual")

    agencies = []
    external_income_agencies_set = set(
        ExternalIncomeAnnual.objects.values_list("agency_name", flat=True)
    ) - set([""])
    # Update agencies that exist
    Agency.objects.filter(name__in=external_income_agencies_set).update(
        is_for_replenishment=True
    )

    existing_agencies_set = set(Agency.objects.values_list("name", flat=True))

    # Create agencies that don't exist
    for name in external_income_agencies_set - existing_agencies_set:
        agency_type = "National"
        is_for_replenishment = True
        if name in ["Treasurer (Cash Pool)", "UNIDO", "UNDP", "UNEP", "World Bank"]:
            agency_type = "Agency"

        agencies.append(
            Agency(
                name=name,
                agency_type=agency_type,
                is_for_replenishment=is_for_replenishment,
            )
        )

    Agency.objects.bulk_create(agencies, update_conflicts=False)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0162_alter_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="is_for_replenishment",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
