# Generated by Django 4.2.11 on 2024-10-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0163_agency_is_for_replenishment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="disputedcontribution",
            name="unique_disputed_country_year",
        ),
        migrations.RemoveConstraint(
            model_name="disputedcontribution",
            name="unique_year",
        ),
    ]
