# Generated by Django 4.2.11 on 2024-10-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0164_remove_disputedcontribution_unique_disputed_country_year_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="externalallocation",
            name="decision_number",
            field=models.CharField(default="", max_length=32),
        ),
    ]
