# Generated by Django 4.2.11 on 2024-11-07 08:48

import core.models.business_plan
import core.models.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0165_externalallocation_decision_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessplan",
            name="feedback_file",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="feedback_filename",
        ),
        migrations.CreateModel(
            name="BPFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of file upload"
                    ),
                ),
                (
                    "year_start",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1985)]
                    ),
                ),
                (
                    "year_end",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1985)]
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        storage=core.models.utils.get_protected_storage,
                        upload_to=core.models.business_plan.BPFile.upload_path,
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.agency"
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="bpfile",
            constraint=models.UniqueConstraint(
                fields=("agency", "year_start", "year_end", "filename"),
                name="unique_business_plan_filename",
            ),
        ),
    ]
