# Generated by Django 4.2.11 on 2024-11-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0166_alter_payment_invoice"),
        ("core", "0166_remove_businessplan_feedback_file_and_more"),
    ]

    operations = []
