# Generated by Django 4.2.16 on 2024-11-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0167_merge_20241107_0927"),
    ]

    operations = [
        migrations.AddField(
            model_name="bphistory",
            name="event_in_draft",
            field=models.BooleanField(
                default=True,
                help_text="Indicate whether history entry was created while in Draft",
            ),
        ),
        migrations.AlterField(
            model_name="businessplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("Agency Draft", "Agency Draft"),
                    ("Secretariat Draft", "Secretariat Draft"),
                    ("Submitted for review", "Submitted for review"),
                    ("Submitted", "Submitted"),
                    ("Need Changes", "Need Changes"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Agency Draft",
                max_length=32,
            ),
        ),
    ]
