# Generated by Django 4.2.16 on 2024-11-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0169_bphistory_event_in_draft_alter_businessplan_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bphistory",
            name="event_in_draft",
        ),
        migrations.AlterField(
            model_name="businessplan",
            name="status",
            field=models.CharField(
                choices=[("Consolidated", "Consolidated"), ("Endorsed", "Endorsed")],
                default="Endorsed",
                max_length=32,
            ),
        ),
    ]
