# Generated by Django 4.2.16 on 2024-11-22 07:18

from django.db import migrations


def forwards_func(apps, schema_editor):
    BusinessPlan = apps.get_model("core", "BusinessPlan")
    db_alias = schema_editor.connection.alias

    # Set status=Endorsed for all BPs
    BusinessPlan.objects.using(db_alias).update(status="Endorsed")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0170_remove_bphistory_event_in_draft_and_more"),
    ]

    operations = [migrations.RunPython(forwards_func, migrations.RunPython.noop)]
