# Generated by Django 4.2.16 on 2024-11-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0171_set_bp_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bphistory",
            name="bp_version",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="is_latest",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="version",
        ),
    ]
