# Generated by Django 4.2.16 on 2024-11-25 09:37

from django.db import migrations


def forwards_func(apps, schema_editor):
    BusinessPlan = apps.get_model("core", "BusinessPlan")
    db_alias = schema_editor.connection.alias

    # Delete old BPs, keep only latest version
    BusinessPlan.objects.using(db_alias).filter(is_latest=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0171_set_bp_status"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="bphistory",
            name="bp_version",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="is_latest",
        ),
        migrations.RemoveField(
            model_name="businessplan",
            name="version",
        ),
    ]
