# Generated by Django 4.2.16 on 2024-12-02 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0172_remove_bphistory_bp_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualcontributionstatus",
            name="bilateral_assistance_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="externalincomeannual",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="externalincomeannual",
            name="meeting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.meeting",
            ),
        ),
        migrations.AddField(
            model_name="triennialcontributionstatus",
            name="bilateral_assistance_comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
