# Generated by Django 4.2.16 on 2024-11-27 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0172_remove_bphistory_bp_version_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessplan",
            name="agency",
        ),
        migrations.AddField(
            model_name="bpactivity",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.agency",
            ),
        ),
    ]
