# Generated by Django 4.2.16 on 2024-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0173_remove_businessplan_agency_bpactivity_agency"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bpfile",
            name="unique_business_plan_filename",
        ),
        migrations.RemoveField(
            model_name="bpfile",
            name="agency",
        ),
        migrations.AddField(
            model_name="bpfile",
            name="status",
            field=models.CharField(
                choices=[("Consolidated", "Consolidated"), ("Endorsed", "Endorsed")],
                default="Endorsed",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="bpfile",
            constraint=models.UniqueConstraint(
                fields=("status", "year_start", "year_end", "filename"),
                name="unique_business_plan_filename",
            ),
        ),
    ]
