# Generated by Django 4.2.16 on 2024-12-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0173_annualcontributionstatus_bilateral_assistance_comment_and_more"),
        ("core", "0174_remove_bpfile_unique_business_plan_filename_and_more"),
    ]

    operations = []
