# Generated by Django 4.2.16 on 2024-12-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0175_merge_20241202_1526"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bpactivity",
            name="comment_types",
        ),
        migrations.RemoveField(
            model_name="bpactivity",
            name="is_updated",
        ),
        migrations.AddField(
            model_name="businessplan",
            name="decision_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessplan",
            name="meeting_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bpfile",
            name="status",
            field=models.CharField(
                choices=[("Submitted", "Submitted"), ("Endorsed", "Endorsed")],
                default="Endorsed",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="businessplan",
            name="status",
            field=models.CharField(
                choices=[("Submitted", "Submitted"), ("Endorsed", "Endorsed")],
                default="Endorsed",
                max_length=32,
            ),
        ),
        migrations.DeleteModel(
            name="CommentType",
        ),
    ]
