# Generated by Django 4.2.16 on 2024-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0176_remove_bpactivity_comment_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bpactivity",
            name="lvc_status",
            field=models.CharField(
                choices=[
                    ("LVC", "LVC"),
                    ("Non-LVC", "Non-LVC"),
                    ("Regional", "Regional"),
                    ("Global", "Global"),
                    ("NDR", "NDR"),
                    ("Undefined", "Undefined"),
                ],
                max_length=32,
            ),
        ),
    ]
