# Generated by Django 4.2.16 on 2024-12-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0178_alter_bpactivity_bp_chemical_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bpactivity",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Approved"),
                    ("P", "Planned"),
                    ("R", "Rejected"),
                    ("U", "Undefined"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="bpactivity",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
