# Generated by Django 4.2.16 on 2025-03-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0181_alter_bpactivity_status_alter_bpactivity_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency_inputter", "Agency inputter"),
                    ("agency_submitter", "Agency submitter"),
                    ("country_user", "Country user"),
                    ("country_submitter", "Country submitter"),
                    ("secretariat", "Secretariat"),
                    ("viewer", "Viewer"),
                    ("stakeholder", "Stakeholder"),
                    ("treasurer", "Treasurer"),
                    ("cp_viewer", "Country Programme Viewer"),
                ],
                max_length=50,
            ),
        ),
    ]
