# Generated by Django 4.2.17 on 2025-03-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0183_decision_title_meeting_end_date_meeting_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="internal_api_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="decision",
            name="number",
            field=models.CharField(
                blank=True, default="", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="number",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
