# Generated by Django 4.2.17 on 2025-03-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0184_meeting_internal_api_id_alter_decision_number_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW triennial_contributions_view AS
            SELECT 
                tcs.*,
                CASE 
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - start_year = 0 
                        THEN agreed_contributions / 3
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - start_year = 1 
                        THEN (agreed_contributions * 2) / 3
                    ELSE agreed_contributions
                END as current_agreed_contributions,
                CASE 
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - start_year = 0 
                        THEN outstanding_contributions - (agreed_contributions * 2/3)
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - start_year = 1 
                        THEN outstanding_contributions - (agreed_contributions / 3)
                    ELSE outstanding_contributions
                END as current_outstanding_contributions
            FROM core_triennialcontributionstatus tcs;
            """,
            reverse_sql="DROP VIEW IF EXISTS triennial_contributions_view;",
        )
    ]
