# Generated by Django 4.2.17 on 2025-03-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0185_create_triennial_contribution_status_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="TriennialContributionView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agreed_contributions",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "cash_payments",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "bilateral_assistance",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "promissory_notes",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "outstanding_contributions",
                    models.DecimalField(decimal_places=15, default=0, max_digits=30),
                ),
                (
                    "bilateral_assistance_decision_number",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "bilateral_assistance_comment",
                    models.TextField(blank=True, default=""),
                ),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                (
                    "current_agreed_contributions",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
                (
                    "current_outstanding_contributions",
                    models.DecimalField(decimal_places=15, max_digits=30),
                ),
            ],
            options={
                "db_table": "triennial_contributions_view",
                "managed": False,
            },
        ),
    ]
