# Generated by Django 4.2.17 on 2025-04-22 15:14

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


def create_submission_statuses(apps, schema_editor):
    ProjectSubmissionStatus = apps.get_model("core", "ProjectSubmissionStatus")
    project_statuses = [
        "Draft",
        "Submitted",
        "Recommended",
        "Approved",
        "Withdrawn",
    ]

    for status in project_statuses:
        ProjectSubmissionStatus.objects.get_or_create(name=status)


def assign_draft_submission_status(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    ProjectSubmissionStatus = apps.get_model("core", "ProjectSubmissionStatus")
    draft_status = ProjectSubmissionStatus.objects.get(name="Draft")
    Project.objects.filter(submission_status__isnull=True).update(
        submission_status=draft_status
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0186_triennialcontributionview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSubmissionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#CCCCCC", image_field=None, max_length=18, samples=None
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project submission statuses",
            },
        ),
        migrations.RunPython(create_submission_statuses, migrations.RunPython.noop),
        migrations.RenameField(
            model_name="project",
            old_name="approval_meeting",
            new_name="meeting",
        ),
        migrations.AlterField(
            model_name="project",
            name="meeting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="core.meeting",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_fund",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="submission_status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.projectsubmissionstatus",
            ),
        ),
        migrations.RunPython(assign_draft_submission_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="submission_status",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.projectsubmissionstatus",
            ),
        ),
    ]
