# Generated by Django 4.2.17 on 2025-04-24 11:09

from django.db import migrations
import os


def forward_modify_project_submission_status_and_status(apps, schema_editor):
    if os.getenv("PYTEST_CURRENT_TEST"):  # Skip if running pytest
        return

    Project = apps.get_model("core", "Project")
    ProjectSubmissionStatus = apps.get_model("core", "ProjectSubmissionStatus")
    ProjectStatus = apps.get_model("core", "ProjectStatus")

    approved_statuses_codes = [
        "CLO",
        "COM",
        "FIN",
        "NEW",
        "ONG",
        "TRF",
    ]
    old_submission_statuses_in_project_status = [
        "NEWSUB",
        "UNK",
    ]

    # Create new N/A project status
    na_status = ProjectStatus.objects.create(
        name="N/A",
        code="NA",
        color="#CCCCCC",
    )

    # Replace old submission statuses in project status with N/A
    Project.objects.filter(
        status__code__in=old_submission_statuses_in_project_status
    ).update(
        status=na_status,
    )

    # Delete old submission statuses in project status
    ProjectStatus.objects.filter(code__in=["UNK", "NEWSUB"]).delete()

    # Assign the correct submission status to projects with approved statuses
    approved_submission_status = ProjectSubmissionStatus.objects.get(
        name="Approved",
    )
    Project.objects.filter(status__code__in=approved_statuses_codes).update(
        submission_status=approved_submission_status,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0187_projectsubmissionstatus_and_more"),
    ]

    operations = [
        migrations.RunPython(
            forward_modify_project_submission_status_and_status,
            reverse_code=migrations.RunPython.noop,
            atomic=False,
        ),
    ]
