# Generated by Django 4.2.17 on 2025-04-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0188_modify_project_submission_status_and_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-date_actual", "country__name", "serial_number"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="coop_agencies",
            field=models.ManyToManyField(
                blank=True, related_name="coop_projects", to="core.agency"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="submission_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bilateral cooperation", "Bilateral cooperation"),
                    ("investment project", "Investment project"),
                    ("work programme amendment", "Work programme amendment"),
                    (
                        "other doc: cpg, policy paper, business plan",
                        "Other doc: CPG, policy paper, business plan",
                    ),
                ],
                max_length=164,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="substance_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CFC", "CFC"),
                    ("HCFC", "HCFC"),
                    ("HFC", "HFC"),
                    ("BOTH", "Both"),
                    ("Methyl Bromide", "Methyl Bromide"),
                    ("HFC_Plus", "HFC_Plus"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
