# Generated by Django 4.2.17 on 2025-04-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0189_alter_project_options_alter_project_coop_agencies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="lead_agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead_projects",
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.decision",
            ),
        ),
    ]
