# Generated by Django 4.2.17 on 2025-04-28 14:07

import os

from django.db import migrations, models


def set_filename_for_existing_files(apps, schema_editor):
    ProjectFile = apps.get_model("core", "ProjectFile")
    for project_file in ProjectFile.objects.all():
        project_file.filename = os.path.basename(project_file.file.name)
        project_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0190_project_lead_agency_alter_project_decision"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="filename",
            field=models.CharField(
                default="test", max_length=100, null=True, blank=True
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_filename_for_existing_files,
            reverse_code=migrations.RunPython.noop,
            atomic=False,
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="filename",
            field=models.CharField(
                default="test", max_length=100, null=True, blank=True
            ),
        ),
    ]
