# Generated by Django 4.2.17 on 2025-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0191_projectfile_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalallocation",
            name="is_dashboard_only",
            field=models.BooleanField(default=False),
        ),
    ]
