# Generated by Django 4.2.17 on 2025-05-06 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0192_externalallocation_is_dashboard_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="filename",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="projectrbmmeasure",
            name="measure",
            field=models.ForeignKey(
                help_text="Results-Based Management measure to be used for this project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_measures",
                to="core.rbmmeasure",
            ),
        ),
        migrations.CreateModel(
            name="ProjectClusterTypeSectorFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_type_sector_fields",
                        to="core.projectcluster",
                    ),
                ),
                (
                    "fields",
                    models.ManyToManyField(
                        blank=True,
                        help_text="List of fields that should be filled in the project for this combination of cluster, type and sector",
                        related_name="cluster_type_sector_fields",
                        to="core.projectfield",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_type_sector_fields",
                        to="core.projectsector",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cluster_type_sector_fields",
                        to="core.projecttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project cluster type sector fields",
                "unique_together": {("cluster", "type", "sector")},
            },
        ),
    ]
