# Generated by Django 4.2.17 on 2025-05-06 12:46

import core.models.replenishment
import core.models.utils
from django.db import migrations, models
import django.db.models.deletion
import django_clamd.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0193_projectfield_alter_projectfile_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicefile",
            name="file",
            field=models.FileField(
                storage=core.models.utils.get_protected_storage,
                upload_to=core.models.replenishment.InvoiceFile.upload_path,
                validators=[django_clamd.validators.validate_file_infection],
            ),
        ),
        migrations.AlterField(
            model_name="paymentfile",
            name="file",
            field=models.FileField(
                storage=core.models.utils.get_protected_storage,
                upload_to=core.models.replenishment.PaymentFile.upload_path,
                validators=[django_clamd.validators.validate_file_infection],
            ),
        ),
        migrations.AlterField(
            model_name="scaleofassessmentversion",
            name="decision_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models.utils.get_protected_storage,
                upload_to=core.models.replenishment.ScaleOfAssessmentVersion.upload_path,
                validators=[django_clamd.validators.validate_file_infection],
            ),
        ),
        migrations.AlterField(
            model_name="statusofthefundfile",
            name="file",
            field=models.FileField(
                storage=core.models.utils.get_protected_storage,
                upload_to=core.models.replenishment.StatusOfTheFundFile.upload_path,
                validators=[django_clamd.validators.validate_file_infection],
            ),
        ),
        migrations.CreateModel(
            name="BilateralAssistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=15, max_digits=30)),
                ("decision_number", models.CharField(blank=True, max_length=32)),
                ("comment", models.TextField(blank=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bilateral_assistances",
                        to="core.country",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.meeting",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["country", "year"],
                        name="core_bilate_country_21a77a_idx",
                    )
                ],
            },
        ),
    ]
