# Generated by Django 4.2.17 on 2025-05-06 12:48

from django.db import migrations


def migrate_bilateral_assistance(apps, schema_editor):
    AnnualContributionStatus = apps.get_model("core", "AnnualContributionStatus")
    BilateralAssistance = apps.get_model("core", "BilateralAssistance")

    for contribution in AnnualContributionStatus.objects.all():
        if contribution.bilateral_assistance:
            BilateralAssistance.objects.create(
                country=contribution.country,
                year=contribution.year,
                amount=contribution.bilateral_assistance,
                meeting=contribution.bilateral_assistance_meeting,
                decision_number=contribution.bilateral_assistance_decision_number,
                comment=contribution.bilateral_assistance_comment,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0194_bilateral_assistance_model"),
    ]

    operations = [
        migrations.RunPython(
            migrate_bilateral_assistance, reverse_code=migrations.RunPython.noop
        ),
    ]
