# Generated by Django 4.2.17 on 2025-05-07 06:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def process_tranche_field(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    projects_with_null_tranche = Project.objects.filter(tranche="")
    for project in projects_with_null_tranche:
        project.tranche = None

    Project.objects.bulk_update(projects_with_null_tranche, ["tranche"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0195_populate_bilateral_assistance_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ad_hoc_pcr",
            field=models.BooleanField(blank=True, help_text="Ad-hoc PCR", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="aggregated_consumption",
            field=models.FloatField(
                blank=True,
                help_text="The field is the aggregated consumption of all enterprises",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="baseline",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="cost_effectiveness",
            field=models.FloatField(
                blank=True, help_text="Cost effectiveness (US$/ Kg) (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cost_effectiveness_co2",
            field=models.FloatField(
                blank=True,
                help_text="Cost effectiveness (US$/ CO2-ep) (MYA)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="destruction_tehnology",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="funding_window",
            field=models.CharField(
                blank=True, help_text="Funding window", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Annex group of substances",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="core.group",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="individual_consideration",
            field=models.BooleanField(
                blank=True,
                help_text="Blanket or Individual consideration. This field is needed for analyses at the recommendation stage for QA unit. And it is for MLFS users to select at the review stage.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_lvc",
            field=models.BooleanField(
                blank=True,
                help_text="The field to be derived but with the option change the value for the KIP (As an example).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_sme",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_end_date",
            field=models.DateField(blank=True, help_text="End date (MYA)", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_phase_out_co2_eq_t",
            field=models.FloatField(
                blank=True, help_text="Phase out (CO2-eq t) (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_phase_out_mt",
            field=models.FloatField(
                blank=True, help_text="Phase out (Mt) (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_phase_out_odp_t",
            field=models.FloatField(
                blank=True, help_text="Phase out (ODP t) (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_project_funding",
            field=models.FloatField(
                blank=True, help_text="Project Funding (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_start_date",
            field=models.DateField(blank=True, help_text="Start date (MYA)", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_support_cost",
            field=models.FloatField(
                blank=True, help_text="Support Cost (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pcr_waived",
            field=models.BooleanField(blank=True, help_text="PCR waived", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="production_control_type",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="starting_point",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="targets",
            field=models.FloatField(
                blank=True,
                help_text="Targets for the MYA project. The field is the aggregated consumption of all enterprises",
                null=True,
            ),
        ),
        migrations.RunPython(
            process_tranche_field,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="project",
            name="tranche",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="ods_replacement",
            field=models.CharField(
                blank=True,
                help_text="Replacement technology/ies",
                max_length=256,
                null=True,
            ),
        ),
    ]
