# Generated by Django 4.2.17 on 2025-05-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0185_create_triennial_contribution_status_view"),
        ("core", "0196_project_ad_hoc_pcr_project_aggregated_consumption_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW triennial_contributions_view AS
            WITH disputed_sums AS (
                SELECT 
                    tcs.country_id,
                    tcs.start_year,
                    tcs.end_year,
                    SUM(dc.amount) as disputed_total
                FROM core_triennialcontributionstatus tcs
                LEFT JOIN core_disputedcontribution dc 
                    ON dc.country_id = tcs.country_id 
                    AND dc.year BETWEEN tcs.start_year AND tcs.end_year
                GROUP BY 
                    tcs.country_id,
                    tcs.start_year,
                    tcs.end_year
            )
            SELECT 
                tcs.*,
                CASE 
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - tcs.start_year = 0 
                        THEN tcs.agreed_contributions - COALESCE(ds.disputed_total, 0) * 2/3
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - tcs.start_year = 1 
                        THEN tcs.agreed_contributions - COALESCE(ds.disputed_total, 0) * 1/3
                    ELSE tcs.agreed_contributions
                END as current_agreed_contributions,
                CASE 
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - tcs.start_year = 0 
                        THEN tcs.outstanding_contributions - (tcs.agreed_contributions * 2/3)
                             - COALESCE(ds.disputed_total * 2/3, 0)
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - tcs.start_year = 1 
                        THEN tcs.outstanding_contributions - (tcs.agreed_contributions / 3)
                             - COALESCE(ds.disputed_total / 3, 0)
                    ELSE tcs.outstanding_contributions
                END as current_outstanding_contributions
            FROM core_triennialcontributionstatus tcs
            LEFT JOIN disputed_sums ds 
                ON tcs.country_id = ds.country_id 
                AND tcs.start_year = ds.start_year 
                AND tcs.end_year = ds.end_year;
            """,
            reverse_sql="""
            CREATE OR REPLACE VIEW triennial_contributions_view AS
            SELECT 
                tcs.*,
                CASE 
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - start_year = 0 
                        THEN agreed_contributions / 3
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - start_year = 1 
                        THEN (agreed_contributions * 2) / 3
                    ELSE agreed_contributions
                END as current_agreed_contributions,
                CASE 
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - start_year = 0 
                        THEN outstanding_contributions - (agreed_contributions * 2/3)
                    WHEN EXTRACT(YEAR FROM CURRENT_DATE) - start_year = 1 
                        THEN outstanding_contributions - (agreed_contributions / 3)
                    ELSE outstanding_contributions
                END as current_outstanding_contributions
            FROM core_triennialcontributionstatus tcs;
            """
        )
    ]