# Generated by Django 4.2.17 on 2025-05-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0197_adjust_triennial_contributions_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectodsodp",
            name="phase_out_mt",
            field=models.FloatField(blank=True, help_text="Phase out (Mt)", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="destruction_tehnology",
            field=models.CharField(
                blank=True,
                choices=[("D1", "D1"), ("D2", "D2")],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="individual_consideration",
            field=models.BooleanField(
                blank=True,
                help_text="\n            Blanket or Individual consideration.\n            This field is needed for analyses at the recommendation stage for QA unit.\n            And it is for MLFS users to select at the review stage.\n        ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="production_control_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reduction", "Reduction"),
                    ("closure", "Closure"),
                    (
                        "switch_to_production_for_feedstock_uses",
                        "Switch to production for feedstock uses",
                    ),
                    (
                        "conversion_to_non_controlled_substance",
                        "Conversion to non-controlled substance",
                    ),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="co2_mt",
            field=models.FloatField(
                blank=True, help_text="Phase out (CO2-eq t)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="odp",
            field=models.FloatField(
                blank=True, help_text="Phase out (ODP t)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="ods_substance",
            field=models.ForeignKey(
                blank=True,
                help_text="Substance - baseline technology",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_ods",
                to="core.substance",
            ),
        ),
    ]
