# Generated by Django 4.2.17 on 2025-05-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0197_adjust_triennial_contributions_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="subsectors",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="core.projectsubsector"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="individual_consideration",
            field=models.BooleanField(
                blank=True,
                help_text="\n            Blanket or Individual consideration.\n            This field is needed for analyses at the recommendation stage for QA unit.\n            And it is for MLFS users to select at the review stage.\n        ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="subsector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_old",
                to="core.projectsubsector",
            ),
        ),
    ]
