# Generated by Django 4.2.17 on 2025-05-08 08:26

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    Migrates data from the old 'subsector' ForeignKey to the new 'subsectors' ManyToManyField.
    """
    Project = apps.get_model("core", "Project")
    for project in Project.objects.all():
        if project.subsector:
            project.subsectors.add(project.subsector)


def backwards_func(apps, schema_editor):
    """
    Reverts data from 'subsectors' ManyToManyField back to 'subsector' ForeignKey.
    """
    Project = apps.get_model("core", "Project")
    for project in Project.objects.all():
        if project.subsectors.exists():
            # Assign the first related subsector back to the old ForeignKey
            project.subsector = project.subsectors.first()
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0197_project_subsectors_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=backwards_func),
    ]
