# Generated by Django 4.2.17 on 2025-05-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0198_projectodsodp_phase_out_mt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ban_of_equipment",
            field=models.IntegerField(
                blank=True, help_text="Ban of equipment", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ban_of_substances",
            field=models.IntegerField(
                blank=True, help_text="Ban of substances", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="capacity_building_programmes",
            field=models.BooleanField(
                blank=True,
                help_text='\n            Capacity building programmes for technicians, end-users, operators,\n            consultants, procurement officers and other Government entities",\n        ',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="certification_system_for_technicians",
            field=models.BooleanField(
                blank=True,
                help_text="Certification system for technicians established or further enhanced",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ee_demonstration_project",
            field=models.BooleanField(
                blank=True, help_text="EE demonstration project included", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_imp_exp_licensing",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of import/export licensing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_quota_systems",
            field=models.BooleanField(
                blank=True, help_text="Establishment of quota systems", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="kwh_year_saved",
            field=models.FloatField(blank=True, help_text="kWh/year saved", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_commercial_ac",
            field=models.BooleanField(
                blank=True, help_text="MEPS developed for commercial AC", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_commercial_refrigeration",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for commercial refrigeration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_domestic_refrigeration",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for domestic refrigeration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_residential_ac",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for residential air-conditioning",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_enterprises",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_enterprises_assisted",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises assisted", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_customs_officers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female customs officers trained",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_nou_personnel_supported",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female NOU personnel supported",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_technicians_certified",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians certified",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_technicians_trained",
            field=models.IntegerField(
                blank=True, help_text="Number of female technicians trained", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_trainers_trained",
            field=models.IntegerField(
                blank=True, help_text="Number of female trainers trained", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of production lines assisted (MYA)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_tools_sets_distributed",
            field=models.IntegerField(
                blank=True, help_text="Number of tools sets distributed", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_training_institutions_newly_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of training institutions newly assisted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="operation_of_reclamation_scheme",
            field=models.BooleanField(
                blank=True, help_text="Operation of reclamation scheme", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="operation_of_recovery_and_recycling_scheme",
            field=models.BooleanField(
                blank=True,
                help_text="Operation of recovery and recycling scheme",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_co2_eq_t",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (CO2-eq tonnes)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_mt",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (Metric tonnes)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_destroyed",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Destroyed)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_emitted",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Emitted)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_generated",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Generated)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_generation_rate",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (by product generation rate)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_customs_officers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of customs officers trained",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_nou_personnnel_supported",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of NOU personnel supported",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_technicians_certified",
            field=models.IntegerField(
                blank=True, help_text="Total number of technicians certified", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_technicians_trained",
            field=models.IntegerField(
                blank=True, help_text="Total number of technicians trained", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_trainers_trained",
            field=models.IntegerField(
                blank=True, help_text="Total number of trainers trained", null=True
            ),
        ),
    ]
