# Generated by Django 4.2.17 on 2025-05-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0199_auto_20250508_0826"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="subsector",
        ),
    ]
