# Generated by Django 4.2.17 on 2025-05-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0199_project_ban_of_equipment_project_ban_of_substances_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="destruction_tehnology",
            new_name="destruction_technology",
        ),
    ]
