# Generated by Django 4.2.17 on 2025-05-13 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0200_remove_project_subsector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="destruction_tehnology",
        ),
        migrations.RemoveField(
            model_name="projectfield",
            name="name",
        ),
        migrations.AddField(
            model_name="project",
            name="ban_of_equipment",
            field=models.IntegerField(
                blank=True, help_text="Ban of equipment", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ban_of_substances",
            field=models.IntegerField(
                blank=True, help_text="Ban of substances", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="capacity_building_programmes",
            field=models.BooleanField(
                blank=True,
                help_text='\n            Capacity building programmes for technicians, end-users, operators,\n            consultants, procurement officers and other Government entities",\n        ',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="certification_system_for_technicians",
            field=models.BooleanField(
                blank=True,
                help_text="Certification system for technicians established or further enhanced",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="checklist_regulations",
            field=models.CharField(
                blank=True,
                choices=[("pr1", "PR1"), ("pr2", "PR2"), ("pr3", "PR3")],
                help_text="Checklist of regulations or policies enacted",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="destruction_technology",
            field=models.CharField(
                blank=True,
                choices=[("D1", "D1"), ("D2", "D2")],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ee_demonstration_project",
            field=models.BooleanField(
                blank=True, help_text="EE demonstration project included", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_imp_exp_licensing",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of import/export licensing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_quota_systems",
            field=models.BooleanField(
                blank=True, help_text="Establishment of quota systems", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="kwh_year_saved",
            field=models.FloatField(blank=True, help_text="kWh/year saved", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_commercial_ac",
            field=models.BooleanField(
                blank=True, help_text="MEPS developed for commercial AC", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_commercial_refrigeration",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for commercial refrigeration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_domestic_refrigeration",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for domestic refrigeration",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_residential_ac",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for residential air-conditioning",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_enterprises",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_enterprises_assisted",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises assisted", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_customs_officers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female customs officers trained",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_nou_personnel_supported",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female NOU personnel supported",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_technicians_certified",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians certified",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_technicians_trained",
            field=models.IntegerField(
                blank=True, help_text="Number of female technicians trained", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_trainers_trained",
            field=models.IntegerField(
                blank=True, help_text="Number of female trainers trained", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of production lines assisted (MYA)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_tools_sets_distributed",
            field=models.IntegerField(
                blank=True, help_text="Number of tools sets distributed", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_training_institutions_newly_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of training institutions newly assisted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="operation_of_reclamation_scheme",
            field=models.BooleanField(
                blank=True, help_text="Operation of reclamation scheme", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="operation_of_recovery_and_recycling_scheme",
            field=models.BooleanField(
                blank=True,
                help_text="Operation of recovery and recycling scheme",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_co2_eq_t",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (CO2-eq tonnes)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_mt",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (Metric tonnes)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_destroyed",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Destroyed)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_emitted",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Emitted)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_generated",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Generated)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_generation_rate",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (by product generation rate)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_customs_officers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of customs officers trained",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_nou_personnnel_supported",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of NOU personnel supported",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_technicians_certified",
            field=models.IntegerField(
                blank=True, help_text="Total number of technicians certified", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_technicians_trained",
            field=models.IntegerField(
                blank=True, help_text="Total number of technicians trained", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_trainers_trained",
            field=models.IntegerField(
                blank=True, help_text="Total number of trainers trained", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectfield",
            name="data_type",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectfield",
            name="import_name",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectfield",
            name="label",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectfield",
            name="section",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="projectfield",
            name="table",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectodsodp",
            name="phase_out_mt",
            field=models.FloatField(blank=True, help_text="Phase out (Mt)", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost_effectiveness_co2",
            field=models.FloatField(
                blank=True,
                help_text="Cost effectiveness (US$/ CO2-eq) (MYA)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="production_control_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reduction", "Reduction"),
                    ("closure", "Closure"),
                    (
                        "switch_to_production_for_feedstock_uses",
                        "Switch to production for feedstock uses",
                    ),
                    (
                        "conversion_to_non_controlled_substance",
                        "Conversion to non-controlled substance",
                    ),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="co2_mt",
            field=models.FloatField(
                blank=True, help_text="Phase out (CO2-eq t)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="odp",
            field=models.FloatField(
                blank=True, help_text="Phase out (ODP t)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="ods_substance",
            field=models.ForeignKey(
                blank=True,
                help_text="Substance - baseline technology",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_ods",
                to="core.substance",
            ),
        ),
    ]
