# Generated by Django 4.2.17 on 2025-05-16 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0201_remove_project_destruction_tehnology_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="latest_project",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is an archive project, this field will be set to the latest project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archive_projects",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="version",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="project",
            name="version_created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User who created this project version",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_projects_version",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="legacy_code",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("latest_project__isnull", True)),
                fields=("legacy_code",),
                name="unique_legacy_code_when_latest_project_is_none",
            ),
        ),
    ]
