# Generated by Django 4.2.17 on 2025-05-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0202_project_date_created_project_latest_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectfield",
            name="field_name",
        ),
        migrations.AddField(
            model_name="projectfield",
            name="read_field_name",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectfield",
            name="write_field_name",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
