# Generated by Django 4.2.17 on 2025-05-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0203_remove_projectfield_field_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSpecificFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_specific_fields",
                        to="core.projectcluster",
                    ),
                ),
                (
                    "fields",
                    models.ManyToManyField(
                        blank=True,
                        help_text="List of fields that should be filled in the project for this combination of cluster, type and sector",
                        related_name="project_specific_fields",
                        to="core.projectfield",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_specific_fields",
                        to="core.projectsector",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_specific_fields",
                        to="core.projecttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project cluster type sector fields",
                "unique_together": {("cluster", "type", "sector")},
            },
        ),
        migrations.DeleteModel(
            name="ProjectClusterTypeSectorFields",
        ),
    ]
