# Generated by Django 4.2.17 on 2025-05-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0204_projectspecificfields_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectspecificfields",
            options={"verbose_name_plural": "Project specific fields"},
        ),
        migrations.AddField(
            model_name="metaproject",
            name="lead_agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency_inputter", "Agency inputter"),
                    ("agency_submitter", "Agency submitter"),
                    ("country_user", "Country user"),
                    ("country_submitter", "Country submitter"),
                    ("secretariat", "Secretariat"),
                    ("viewer", "Viewer"),
                    ("stakeholder", "Stakeholder"),
                    ("treasurer", "Treasurer"),
                    ("cp_viewer", "Country Programme Viewer"),
                    ("secretariat_viewer", "Secretariat Viewer"),
                    ("secretariat_v1_v2_edit_access", "Secretariat V1 V2 Edit Access"),
                    ("secretariat_v3_edit_access", "Secretariat V3 Edit Access"),
                    (
                        "secretariat_production_v1_v2_edit_access",
                        "Secretariat Production V1 V2 Edit Access",
                    ),
                    (
                        "secretariat_production_v3_edit_access",
                        "Secretariat Production V3 Edit Access",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
