# Generated by Django 4.2.17 on 2025-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0205_alter_projectspecificfields_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP VIEW all_emissions_view",
            reverse_sql="""
            CREATE VIEW all_emissions_view AS
            WITH all_emissions AS (
                    (SELECT cp_emission.id,
                            cp_emission.facility,
                            cp_emission.total,
                            cp_emission.all_uses,
                            cp_emission.feedstock_gc,
                            cp_emission.destruction,
                            cp_emission.feedstock_wpc,
                            cp_emission.destruction_wpc,
                            cp_emission.generated_emissions,
                            cp_emission.remarks,
                            cp_emission.country_programme_report_id,
                            cp_emission.source_file,
                            cpr.country_id,
                            cpr.version,
                            cpr.created_at,
                            cpr.year,
                            cpr.status,
                            FALSE AS is_archive
                    FROM cp_emission
                    JOIN cp_report AS cpr ON cp_emission.country_programme_report_id = cpr.id)
                UNION
                    (SELECT cp_emission_archive.id,
                            cp_emission_archive.facility,
                            cp_emission_archive.total,
                            cp_emission_archive.all_uses,
                            cp_emission_archive.feedstock_gc,
                            cp_emission_archive.destruction,
                            cp_emission_archive.feedstock_wpc,
                            cp_emission_archive.destruction_wpc,
                            cp_emission_archive.generated_emissions,
                            cp_emission_archive.remarks,
                            cp_emission_archive.country_programme_report_id,
                            cp_emission_archive.source_file,
                            cpr.country_id,
                            cpr.version,
                            cpr.created_at,
                            cpr.year,
                            cpr.status,
                            TRUE AS is_archive
                    FROM cp_emission_archive
                    JOIN cp_report_archive AS cpr ON cp_emission_archive.country_programme_report_id = cpr.id))
            SELECT all_emissions.id,
                all_emissions.facility,
                all_emissions.total,
                all_emissions.all_uses,
                all_emissions.feedstock_gc,
                all_emissions.destruction,
                all_emissions.feedstock_wpc,
                all_emissions.destruction_wpc,
                all_emissions.generated_emissions,
                all_emissions.remarks,
                all_emissions.country_programme_report_id,
                all_emissions.source_file,
                all_emissions.country_id,
                c.name AS country_name,
                all_emissions.version as report_version,
                all_emissions.year as report_year,
                all_emissions.created_at as report_created_at,
                all_emissions.status as report_status,
                all_emissions.is_archive
            FROM all_emissions
            JOIN core_country AS c ON all_emissions.country_id = c.id
            """,
        ),
        migrations.RunSQL(
            sql="DROP VIEW all_generations_view",
            reverse_sql="""
            CREATE VIEW all_generations_view AS
            WITH all_generations AS (
                    (SELECT cp_generation.id,
                            cp_generation.all_uses,
                            cp_generation.feedstock,
                            cp_generation.destruction,
                            cp_generation.country_programme_report_id,
                            cp_generation.source_file,
                            cpr.country_id,
                            cpr.version,
                            cpr.created_at,
                            cpr.year,
                            cpr.status,
                            FALSE AS is_archive
                    FROM cp_generation
                    JOIN cp_report AS cpr ON cp_generation.country_programme_report_id = cpr.id)
                UNION
                    (SELECT cp_generation_archive.id,
                            cp_generation_archive.all_uses,
                            cp_generation_archive.feedstock,
                            cp_generation_archive.destruction,
                            cp_generation_archive.country_programme_report_id,
                            cp_generation_archive.source_file,
                            cpr.country_id,
                            cpr.version,
                            cpr.created_at,
                            cpr.year,
                            cpr.status,
                            TRUE AS is_archive
                    FROM cp_generation_archive
                    JOIN cp_report_archive AS cpr ON cp_generation_archive.country_programme_report_id = cpr.id))
            SELECT all_generations.id,
                all_generations.all_uses,
                all_generations.feedstock,
                all_generations.destruction,
                all_generations.country_programme_report_id,
                all_generations.source_file,
                all_generations.country_id,
                c.name AS country_name,
                all_generations.version as report_version,
                all_generations.year as report_year,
                all_generations.created_at as report_created_at,
                all_generations.status as report_status,
                all_generations.is_archive
            FROM all_generations
            JOIN core_country AS c ON all_generations.country_id = c.id
            """,
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="all_uses",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured - For all uses",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="destruction",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured - For destruction",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="destruction_wpc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount used for feedstock without prior capture",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="feedstock_gc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured - For feedstock use in your country",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="feedstock_wpc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for feedstock uses within your country",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="generated_emissions",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for destruction",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Total amount generated",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="all_uses",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured - For all uses",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="destruction",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured - For destruction",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="destruction_wpc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount used for feedstock without prior capture",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="feedstock_gc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured - For feedstock use in your country",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="feedstock_wpc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for feedstock uses within your country",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="generated_emissions",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for destruction",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Total amount generated",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpgeneration",
            name="all_uses",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for all uses",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpgeneration",
            name="destruction",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for destruction",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpgeneration",
            name="feedstock",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for feedstock uses within your country",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpgenerationarchive",
            name="all_uses",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for all uses",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpgenerationarchive",
            name="destruction",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for destruction",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpgenerationarchive",
            name="feedstock",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Captured for feedstock uses within your country",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.RunSQL(
            sql="""
            CREATE VIEW all_emissions_view AS
            WITH all_emissions AS (
                    (SELECT cp_emission.id,
                            cp_emission.facility,
                            cp_emission.total,
                            cp_emission.all_uses,
                            cp_emission.feedstock_gc,
                            cp_emission.destruction,
                            cp_emission.feedstock_wpc,
                            cp_emission.destruction_wpc,
                            cp_emission.generated_emissions,
                            cp_emission.remarks,
                            cp_emission.country_programme_report_id,
                            cp_emission.source_file,
                            cpr.country_id,
                            cpr.version,
                            cpr.created_at,
                            cpr.year,
                            cpr.status,
                            FALSE AS is_archive
                    FROM cp_emission
                    JOIN cp_report AS cpr ON cp_emission.country_programme_report_id = cpr.id)
                UNION
                    (SELECT cp_emission_archive.id,
                            cp_emission_archive.facility,
                            cp_emission_archive.total,
                            cp_emission_archive.all_uses,
                            cp_emission_archive.feedstock_gc,
                            cp_emission_archive.destruction,
                            cp_emission_archive.feedstock_wpc,
                            cp_emission_archive.destruction_wpc,
                            cp_emission_archive.generated_emissions,
                            cp_emission_archive.remarks,
                            cp_emission_archive.country_programme_report_id,
                            cp_emission_archive.source_file,
                            cpr.country_id,
                            cpr.version,
                            cpr.created_at,
                            cpr.year,
                            cpr.status,
                            TRUE AS is_archive
                    FROM cp_emission_archive
                    JOIN cp_report_archive AS cpr ON cp_emission_archive.country_programme_report_id = cpr.id))
            SELECT all_emissions.id,
                all_emissions.facility,
                all_emissions.total,
                all_emissions.all_uses,
                all_emissions.feedstock_gc,
                all_emissions.destruction,
                all_emissions.feedstock_wpc,
                all_emissions.destruction_wpc,
                all_emissions.generated_emissions,
                all_emissions.remarks,
                all_emissions.country_programme_report_id,
                all_emissions.source_file,
                all_emissions.country_id,
                c.name AS country_name,
                all_emissions.version as report_version,
                all_emissions.year as report_year,
                all_emissions.created_at as report_created_at,
                all_emissions.status as report_status,
                all_emissions.is_archive
            FROM all_emissions
            JOIN core_country AS c ON all_emissions.country_id = c.id
            """,
            reverse_sql="DROP VIEW all_emissions_view",
        ),
        migrations.RunSQL(
            sql="""
            CREATE VIEW all_generations_view AS
            WITH all_generations AS (
                    (SELECT cp_generation.id,
                            cp_generation.all_uses,
                            cp_generation.feedstock,
                            cp_generation.destruction,
                            cp_generation.country_programme_report_id,
                            cp_generation.source_file,
                            cpr.country_id,
                            cpr.version,
                            cpr.created_at,
                            cpr.year,
                            cpr.status,
                            FALSE AS is_archive
                    FROM cp_generation
                    JOIN cp_report AS cpr ON cp_generation.country_programme_report_id = cpr.id)
                UNION
                    (SELECT cp_generation_archive.id,
                            cp_generation_archive.all_uses,
                            cp_generation_archive.feedstock,
                            cp_generation_archive.destruction,
                            cp_generation_archive.country_programme_report_id,
                            cp_generation_archive.source_file,
                            cpr.country_id,
                            cpr.version,
                            cpr.created_at,
                            cpr.year,
                            cpr.status,
                            TRUE AS is_archive
                    FROM cp_generation_archive
                    JOIN cp_report_archive AS cpr ON cp_generation_archive.country_programme_report_id = cpr.id))
            SELECT all_generations.id,
                all_generations.all_uses,
                all_generations.feedstock,
                all_generations.destruction,
                all_generations.country_programme_report_id,
                all_generations.source_file,
                all_generations.country_id,
                c.name AS country_name,
                all_generations.version as report_version,
                all_generations.year as report_year,
                all_generations.created_at as report_created_at,
                all_generations.status as report_status,
                all_generations.is_archive
            FROM all_generations
            JOIN core_country AS c ON all_generations.country_id = c.id
            """,
            reverse_sql="DROP VIEW all_generations_view",
        ),
    ]
