# Generated by Django 4.2.17 on 2025-05-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0206_alter_cpemission_all_uses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Creation date"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_history",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who updated the project",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project history",
                "ordering": ["-created_at"],
            },
        ),
    ]
