# Generated by Django 4.2.17 on 2025-06-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0207_projecthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcluster",
            name="group",
            field=models.CharField(
                blank=True,
                help_text="\n            Dashboard group. If value is Production, projects with this cluster will be considered\n            as production projects\n        ",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meta_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="core.metaproject",
            ),
        ),
    ]
