# Generated by Django 4.2.17 on 2025-06-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0208_projectcluster_group_alter_project_meta_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectComponents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="projects",
                to="core.projectcomponents",
            ),
        ),
    ]
