# Generated by Django 4.2.17 on 2025-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0209_projectcomponents_project_component"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency_inputter", "Agency inputter"),
                    ("agency_submitter", "Agency submitter"),
                    ("country_user", "Country user"),
                    ("country_submitter", "Country submitter"),
                    ("secretariat", "Secretariat"),
                    ("viewer", "Viewer"),
                    ("stakeholder", "Stakeholder"),
                    ("treasurer", "Treasurer"),
                    ("cp_viewer", "Country Programme Viewer"),
                    ("secretariat_viewer", "Secretariat Viewer"),
                    ("secretariat_v1_v2_edit_access", "Secretariat V1 V2 Edit Access"),
                    ("secretariat_v3_edit_access", "Secretariat V3 Edit Access"),
                    (
                        "secretariat_production_v1_v2_edit_access",
                        "Secretariat Production V1 V2 Edit Access",
                    ),
                    (
                        "secretariat_production_v3_edit_access",
                        "Secretariat Production V3 Edit Access",
                    ),
                    ("bp_viewer", "Business Plan Viewer"),
                    ("bp_editor", "Business Plan Editor"),
                ],
                max_length=50,
            ),
        ),
    ]
