# Generated by Django 4.2.17 on 2025-06-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0210_alter_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bpactivity",
            name="comment_secretariat",
        ),
    ]
