# Generated by Django 4.2.17 on 2025-06-17 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0212_remove_bpactivity_remarks_additional"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="bp_activity_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="bp_decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bp_projects",
                to="core.decision",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="bp_meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bp_projects",
                to="core.meeting",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="bp_year_end",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="bp_year_start",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="bp_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="core.bpactivity",
            ),
        ),
    ]
