# Generated by Django 4.2.17 on 2025-06-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0213_project_bp_activity_title_project_bp_decision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ban_of_equipment_actual",
            field=models.IntegerField(
                blank=True, help_text="Ban of equipment (actual)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ban_of_substances_actual",
            field=models.IntegerField(
                blank=True, help_text="Ban of substances (actual)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="capacity_building_programmes_actual",
            field=models.BooleanField(
                blank=True,
                help_text='\n            Capacity building programmes for technicians, end-users, operators,\n            consultants, procurement officers and other Government entities (actual)",\n        ',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="certification_system_for_technicians_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Certification system for technicians established or further enhanced (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="checklist_regulations_actual",
            field=models.CharField(
                blank=True,
                choices=[("pr1", "PR1"), ("pr2", "PR2"), ("pr3", "PR3")],
                help_text="Checklist of regulations or policies enacted (actual)",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ee_demonstration_project_actual",
            field=models.BooleanField(
                blank=True,
                help_text="EE demonstration project included (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_imp_exp_licensing_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of import/export licensing (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_quota_systems_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment of quota systems (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="kwh_year_saved_actual",
            field=models.FloatField(
                blank=True, help_text="kWh/year saved (actual)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_commercial_ac_actual",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for commercial AC (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_commercial_refrigeration_actual",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for commercial refrigeration (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_domestic_refrigeration_actual",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for domestic refrigeration (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meps_developed_residential_ac_actual",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for residential air-conditioning (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_enterprises_assisted_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of enterprises assisted (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_customs_officers_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female customs officers trained (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_nou_personnel_supported_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female NOU personnel supported (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_technicians_certified_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians certified (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_technicians_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians trained (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_female_trainers_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female trainers trained (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_tools_sets_distributed_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of tools sets distributed (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_training_institutions_newly_assisted_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of training institutions newly assisted (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="operation_of_reclamation_scheme_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Operation of reclamation scheme (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="operation_of_recovery_and_recycling_scheme_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Operation of recovery and recycling scheme (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_co2_eq_t_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (CO2-eq tonnes) (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_mt_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (Metric tonnes) (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_destroyed_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Destroyed) (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_emitted_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Emitted) (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_generated_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Generated) (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="quantity_hfc_23_by_product_generation_rate_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (by product generation rate) (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_customs_officers_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of customs officers trained (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_nou_personnel_supported_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of NOU personnel supported (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_technicians_certified_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of technicians certified (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_technicians_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of technicians trained (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_number_of_trainers_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of trainers trained (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectfield",
            name="is_actual",
            field=models.BooleanField(
                default=False,
                help_text="If True, the field is used for actual data, otherwise for planned data",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ban_of_equipment",
            field=models.IntegerField(
                blank=True, help_text="Ban of equipment (planned)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ban_of_substances",
            field=models.IntegerField(
                blank=True, help_text="Ban of substances (planned)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="capacity_building_programmes",
            field=models.BooleanField(
                blank=True,
                help_text='\n            Capacity building programmes for technicians, end-users, operators,\n            consultants, procurement officers and other Government entities (planned)",\n        ',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="certification_system_for_technicians",
            field=models.BooleanField(
                blank=True,
                help_text="Certification system for technicians established or further enhanced (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="checklist_regulations",
            field=models.CharField(
                blank=True,
                choices=[("pr1", "PR1"), ("pr2", "PR2"), ("pr3", "PR3")],
                help_text="Checklist of regulations or policies enacted (planned)",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ee_demonstration_project",
            field=models.BooleanField(
                blank=True,
                help_text="EE demonstration project included (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="establishment_of_imp_exp_licensing",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of import/export licensing (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="establishment_of_quota_systems",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment of quota systems (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="kwh_year_saved",
            field=models.FloatField(
                blank=True, help_text="kWh/year saved (planned)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_commercial_ac",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for commercial AC (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_commercial_refrigeration",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for commercial refrigeration (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_domestic_refrigeration",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for domestic refrigeration (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_residential_ac",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS developed for residential air-conditioning (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_enterprises_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of enterprises assisted (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_customs_officers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female customs officers trained (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_nou_personnel_supported",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female NOU personnel supported (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_technicians_certified",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians certified (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_technicians_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians trained (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_trainers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female trainers trained (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_tools_sets_distributed",
            field=models.IntegerField(
                blank=True,
                help_text="Number of tools sets distributed (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_training_institutions_newly_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of training institutions newly assisted (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="operation_of_reclamation_scheme",
            field=models.BooleanField(
                blank=True,
                help_text="Operation of reclamation scheme (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="operation_of_recovery_and_recycling_scheme",
            field=models.BooleanField(
                blank=True,
                help_text="Operation of recovery and recycling scheme (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_co2_eq_t",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (CO2-eq tonnes) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_mt",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (Metric tonnes) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_destroyed",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Destroyed) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_emitted",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Emitted) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_generated",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (Generated) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_generation_rate",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product (by product generation rate) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_customs_officers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of customs officers trained (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_nou_personnnel_supported",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of NOU personnel supported (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_technicians_certified",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of technicians certified (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_technicians_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of technicians trained (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_trainers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of trainers trained (planned)",
                null=True,
            ),
        ),
    ]
