# Generated by Django 4.2.17 on 2025-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0213_project_bp_activity_title_project_bp_decision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectodsodp",
            name="ods_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("production", "Production"),
                    ("indirect", "Indirect"),
                    ("other", "Other type"),
                ],
                default="general",
                max_length=256,
            ),
        ),
    ]
