# Generated by Django 4.2.17 on 2025-07-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0214_project_ban_of_equipment_actual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectodsodp",
            name="ods_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("production", "Production"),
                    ("indirect", "Indirect"),
                    ("other", "Other type"),
                ],
                default="general",
                max_length=256,
            ),
        ),
    ]
