# Generated by Django 4.2.17 on 2025-07-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0215_alter_projectodsodp_ods_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="total_number_of_nou_personnnel_supported",
            new_name="total_number_of_nou_personnel_supported",
        ),
    ]
