# Generated by Django 4.2.17 on 2025-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0216_rename_total_number_of_nou_personnnel_supported_project_total_number_of_nou_personnel_supported",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfield",
            name="sort_order",
            field=models.IntegerField(
                default=0, help_text="Sort order of the field in the project form"
            ),
        ),
    ]
