# Generated by Django 4.2.17 on 2025-07-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0217_projectfield_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="bp_activity_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
