# Generated by Django 4.2.17 on 2025-07-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0218_project_bp_activity_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="bp_activity_title",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bp_decision",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bp_meeting",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bp_year_end",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bp_year_start",
        ),
    ]
