# Generated by Django 4.2.17 on 2025-07-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0218_metaproject_date_created_metaproject_date_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="production",
            field=models.BooleanField(
                default=False,
                help_text="If the project is a production project, it will be used for production analysis",
            ),
        ),
        migrations.AddField(
            model_name="projectcluster",
            name="production",
            field=models.BooleanField(
                default=False,
                help_text="\n            If True, projects with this cluster will be considered as production projects.\n            If Null, the cluster allows both values.\n        ",
                null=True,
            ),
        ),
    ]
