# Generated by Django 4.2.17 on 2025-07-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0219_project_production_projectcluster_production"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="bp_activity_title",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bp_decision",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bp_meeting",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bp_year_end",
        ),
        migrations.RemoveField(
            model_name="project",
            name="bp_year_start",
        ),
        migrations.AddField(
            model_name="project",
            name="bp_activity_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
