# Generated by Django 4.2.17 on 2025-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0220_project_bp_activity_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectodsodp",
            name="ods_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "General"),
                    ("production", "Production"),
                    ("indirect", "Indirect"),
                    ("other", "Other type"),
                ],
                max_length=256,
                null=True,
            ),
        ),
    ]
