# Generated by Django 4.2.17 on 2025-07-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0221_alter_projectodsodp_ods_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfield",
            name="editable_in_versions",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of project versions where the field is editable. Values: 1,2,3",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="projectfield",
            name="visible_in_versions",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of project versions where the field is visible. Values: 1,2,3",
                max_length=255,
            ),
        ),
    ]
