# Generated by Django 4.2.17 on 2025-07-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0222_projectfield_editable_in_versions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="lead_agency_submitting_on_behalf",
            field=models.BooleanField(
                default=False,
                help_text="True if the user is the lead agency submitting on behalf of a cooperating agency.",
            ),
        ),
    ]
