# Generated by Django 4.2.17 on 2025-07-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0223_project_lead_agency_submitting_on_behalf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="lead_agency",
        ),
    ]
