# Generated by Django 4.2.17 on 2025-07-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0225_projectsubsector_sectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsubsector",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                help_text="\n        Deprecated: replaced by sectors. Kept for now to ensure no issues arise at import",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.projectsector",
            ),
        ),
    ]
