# Generated by Django 4.2.17 on 2025-07-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0226_alter_projectsubsector_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="bpchemicaltype",
            name="obsolete",
            field=models.BooleanField(
                default=False,
                help_text="If True, the chemical type is obsolete and should not be used in new entries",
            ),
        ),
        migrations.AddField(
            model_name="projectcluster",
            name="obsolete",
            field=models.BooleanField(
                default=False,
                help_text="If True, the cluster is obsolete and should not be used for new entries.",
            ),
        ),
        migrations.AddField(
            model_name="projectsector",
            name="obsolete",
            field=models.BooleanField(
                default=False,
                help_text="If True, the sector is obsolete and should not be used for new entries.",
            ),
        ),
        migrations.AddField(
            model_name="projecttype",
            name="obsolete",
            field=models.BooleanField(
                default=False,
                help_text="If True, the type is obsolete and should not be used for new entries.",
            ),
        ),
        migrations.AlterField(
            model_name="bpactivity",
            name="lvc_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LVC", "LVC"),
                    ("Non-LVC", "Non-LVC"),
                    ("Regional", "Regional"),
                    ("Global", "Global"),
                    ("Undefined", "Undefined"),
                ],
                max_length=32,
            ),
        ),
    ]
