# Generated by Django 4.2.17 on 2025-08-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0227_bpchemicaltype_obsolete_projectcluster_obsolete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="meeting_approved",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_approved",
                to="core.meeting",
            ),
        ),
    ]
