# Generated by Django 4.2.17 on 2025-08-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0228_project_meeting_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpemission",
            name="stored_at_end_of_year",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount stored at the end of the year (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cpemission",
            name="stored_at_start_of_year",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount stored at the beginning of the year (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cpemissionarchive",
            name="stored_at_end_of_year",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount stored at the end of the year (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cpemissionarchive",
            name="stored_at_start_of_year",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount stored at the beginning of the year (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cpgeneration",
            name="other_uses_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Production for exempted essential, critical, high-ambient-temperature or other uses within your country - Quantity",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cpgeneration",
            name="other_uses_remarks",
            field=models.TextField(
                blank=True,
                help_text="Production for exempted essential, critical, high-ambient-temperature or other uses within your country - Decision / type of use or remarks",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cpgenerationarchive",
            name="other_uses_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Production for exempted essential, critical, high-ambient-temperature or other uses within your country - Quantity",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cpgenerationarchive",
            name="other_uses_remarks",
            field=models.TextField(
                blank=True,
                help_text="Production for exempted essential, critical, high-ambient-temperature or other uses within your country - Decision / type of use or remarks",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="all_uses",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured (tonnes) - For uses excluding feedstocks",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="destruction",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured (tonnes) - For destruction",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="destruction_wpc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount destroyed in the facility without prior capture (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="feedstock_gc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured (tonnes) - For feedstock use in your country",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="feedstock_wpc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount used for feedstock without prior capture (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="generated_emissions",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount of generated emissions (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemission",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Total amount generated (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="all_uses",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured (tonnes) - For uses excluding feedstocks",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="destruction",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured (tonnes) - For destruction",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="destruction_wpc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount destroyed in the facility without prior capture (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="feedstock_gc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount generated and captured (tonnes) - For feedstock use in your country",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="feedstock_wpc",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount used for feedstock without prior capture (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="generated_emissions",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount of generated emissions (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpemissionarchive",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Total amount generated (tonnes)",
                max_digits=25,
                null=True,
            ),
        ),
    ]
