# Generated by Django 4.2.17 on 2025-09-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0229_cpemission_stored_at_end_of_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEnterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="System-generated set of letters and numbers identifying the enterprise",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "enterprise",
                    models.CharField(
                        help_text="Name of the enterprise", max_length=256
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Name of the city where the enterprise is located",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="Name of applications",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "local_ownership",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of Article 5 ownership of the enterprise",
                        null=True,
                    ),
                ),
                (
                    "export_to_non_a5",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of produce exported to non-A5 countries",
                        null=True,
                    ),
                ),
                (
                    "capital_cost_approved",
                    models.FloatField(
                        blank=True,
                        help_text="Capital cost approved/allocated for the enterprise (US $)",
                        null=True,
                    ),
                ),
                (
                    "operating_cost_approved",
                    models.FloatField(
                        blank=True,
                        help_text="Operating cost approved/allocated for enterprise (US $)",
                        null=True,
                    ),
                ),
                (
                    "funds_disbursed",
                    models.FloatField(
                        blank=True,
                        help_text="Funds disbursed for the enterprise (US $)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Approval", "Pending Approval"),
                            ("Approved", "Approved"),
                        ],
                        default="Pending Approval",
                        max_length=64,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Any remark on the enterprise", null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprises",
                        to="core.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectEnterpriseOdsOdp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase_out_mt",
                    models.FloatField(
                        blank=True,
                        help_text="\n        Amount of the controlled substance to be phased out (mt)\n        (Phase out (mt))\n    ",
                        null=True,
                    ),
                ),
                (
                    "ods_replacement",
                    models.CharField(
                        blank=True,
                        help_text="\n        Name of alternative technology or chemical\n        Replacement technology\n        ",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "ods_replacement_phase_in",
                    models.CharField(
                        blank=True,
                        help_text="\n            Amount of alternative 1 being used in place of controlled chemical 1\n            (Replacement technology phased in (mt))\n        ",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        help_text="Enterprise linked to this ODS/ODP entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ods_odp",
                        to="core.projectenterprise",
                    ),
                ),
                (
                    "ods_blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projectenterprise_ods",
                        to="core.blend",
                    ),
                ),
                (
                    "ods_substance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Substance - baseline technology",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projectenterprise_ods",
                        to="core.substance",
                    ),
                ),
            ],
        ),
    ]
