# Generated by Django 4.2.17 on 2025-09-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0230_projectenterprise_projectenterpriseodsodp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectenterpriseodsodp",
            name="ods_replacement_phase_in",
            field=models.FloatField(
                blank=True,
                help_text="\n            Amount of alternative 1 being used in place of controlled chemical 1\n            (Replacement technology phased in (mt))\n        ",
                null=True,
            ),
        ),
    ]
