# Generated by Django 4.2.17 on 2025-09-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0231_alter_projectenterpriseodsodp_ods_replacement_phase_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectenterprise",
            name="application",
        ),
        migrations.RemoveField(
            model_name="projectenterprise",
            name="code",
        ),
        migrations.RemoveField(
            model_name="projectenterprise",
            name="export_to_non_a5",
        ),
        migrations.RemoveField(
            model_name="projectenterprise",
            name="local_ownership",
        ),
        migrations.RemoveField(
            model_name="projectenterprise",
            name="location",
        ),
        migrations.RemoveField(
            model_name="projectenterprise",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="projectenterpriseodsodp",
            name="enterprise",
        ),
        migrations.AddField(
            model_name="projectenterpriseodsodp",
            name="project_enterprise",
            field=models.ForeignKey(
                help_text="ProjectEnterprise linked to this ODS/ODP entry",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ods_odp",
                to="core.projectenterprise",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="System-generated set of letters and numbers identifying the enterprise",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the enterprise", max_length=256
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Name of the city where the enterprise is located",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="Name of applications",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "local_ownership",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of Article 5 ownership of the enterprise",
                        null=True,
                    ),
                ),
                (
                    "export_to_non_a5",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of produce exported to non-A5 countries",
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Any remark on the enterprise", null=True
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Country where the enterprise is located",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enterprises",
                        to="core.country",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="enterprise",
            field=models.ForeignKey(
                help_text="Enterprise linked to this project enterprise entry",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_enterprises",
                to="core.enterprise",
            ),
        ),
    ]
