# Generated by Django 4.2.17 on 2025-09-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0232_remove_projectenterprise_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="approved_enterprise",
            field=models.ForeignKey(
                blank=True,
                help_text="If status is 'Pending', link to the approved enterpris (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_enterprises",
                to="core.enterprise",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                ],
                default="Pending Approval",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="approved_project_enterprise",
            field=models.ForeignKey(
                blank=True,
                help_text="If status is 'Pending', link to the approved project enterprise (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_project_enterprises",
                to="core.projectenterprise",
            ),
        ),
    ]
