# Generated by Django 4.2.17 on 2025-09-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0232_remove_projectenterprise_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="post_excom_decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_excom_projects",
                to="core.decision",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="post_excom_meeting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_excom_projects",
                to="core.meeting",
            ),
        ),
    ]
