# Generated by Django 4.2.17 on 2026-01-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0233_user_is_external_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="country",
            name="modules",
            field=models.ManyToManyField(blank=True, to="core.module"),
        ),
    ]
