# Generated by Django 4.2.17 on 2025-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0233_enterprise_approved_enterprise_enterprise_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="approved_enterprise",
        ),
        migrations.RemoveField(
            model_name="projectenterprise",
            name="approved_project_enterprise",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="agencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agencies associated with the enterprise",
                related_name="enterprises",
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                    ("Obsolete", "Obsolete"),
                ],
                default="Pending Approval",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Approval", "Pending Approval"),
                    ("Approved", "Approved"),
                    ("Obsolete", "Obsolete"),
                ],
                default="Pending Approval",
                max_length=64,
            ),
        ),
    ]
