# Generated by Django 4.2.17 on 2025-09-22 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0235_project_post_excom_decision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bpactivity",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bpactivity",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
