# Generated by Django 4.2.17 on 2025-09-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0236_bpactivity_date_created_bpactivity_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaproject",
            name="aggregated_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Aggregated consumption",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="baseline",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Baseline",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="cost_effectiveness_co2",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ CO2-ep)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="cost_effectiveness_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ Kg)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_aggregated_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Aggregated consumption",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_baseline",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Baseline",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_cost_effectiveness_co2",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ CO2-ep)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_cost_effectiveness_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ Kg)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_end_date",
            field=models.DateTimeField(
                blank=True, help_text="End date (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_number_of_enterprises",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_number_of_enterprises_assisted",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises assisted", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True, help_text="Number of Production Lines assisted", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_pahse_out_mt",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase out (Mt) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_phase_out_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase out (ODP t) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_project_funding",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Project Funding (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_start_date",
            field=models.DateTimeField(
                blank=True, help_text="Start date (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_starting_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Starting point",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_support_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Support Cost (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_targets",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Targets",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="end_date",
            field=models.DateTimeField(
                blank=True, help_text="End date (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="number_of_enterprises",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="number_of_enterprises_assisted",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises assisted", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True, help_text="Number of Production Lines assisted", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="pahse_out_mt",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase out (Mt) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="phase_out_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase out (ODP t) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="project_funding",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Project Funding (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="start_date",
            field=models.DateTimeField(
                blank=True, help_text="Start date (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="starting_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Starting point",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="support_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Support Cost (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="targets",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Targets",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="workflow_state",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Final", "Final")],
                default="Final",
                max_length=255,
            ),
        ),
    ]
