# Generated by Django 4.2.17 on 2025-09-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0236_bpactivity_date_created_bpactivity_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="fund_transferred",
            field=models.FloatField(
                blank=True, help_text="Fund transferred", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="psc_transferred",
            field=models.FloatField(
                blank=True, help_text="Project support cost transferred", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="transfer_decision",
            field=models.ForeignKey(
                blank=True,
                help_text="The decision to transfer the project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_decision_projects",
                to="core.decision",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="transfer_excom_provision",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="transfer_meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="The meeting at which the project is transferred",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_meeting_projects",
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meeting_transf",
            field=models.ForeignKey(
                blank=True,
                help_text="Old meeting field used for transferred projects.Should be removed in the future.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferred_projects",
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_fund_transferred",
            field=models.FloatField(
                blank=True,
                help_text="Old field used for transferred projects. Should be removed in the future.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_psc_transferred",
            field=models.FloatField(
                blank=True,
                help_text="Old field used for transferred projects. Should be removed in the future.",
                null=True,
            ),
        ),
    ]
