# Generated by Django 4.2.17 on 2025-09-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0239_metaproject_aggregated_consumption_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="aggregated_consumption",
        ),
        migrations.RemoveField(
            model_name="project",
            name="baseline",
        ),
        migrations.RemoveField(
            model_name="project",
            name="cost_effectiveness",
        ),
        migrations.RemoveField(
            model_name="project",
            name="cost_effectiveness_co2",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_phase_out_co2_eq_t",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_phase_out_mt",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_phase_out_odp_t",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_project_funding",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_start_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_support_cost",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number_of_enterprises",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number_of_production_lines_assisted",
        ),
        migrations.RemoveField(
            model_name="project",
            name="starting_point",
        ),
        migrations.RemoveField(
            model_name="project",
            name="targets",
        ),
        migrations.AlterField(
            model_name="project",
            name="additional_funding",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="agency_remarks",
            field=models.TextField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="application",
            field=models.CharField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="capital_cost",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="compliance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Energy Efficieny", "Energy Efficieny"),
                    ("Non-Energey Efficiency", "Non-Energey Efficiency"),
                ],
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="contingency_cost",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="coop_agencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                related_name="coop_projects",
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="correspondance_no",
            field=models.IntegerField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_actual",
            field=models.DateField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_comp_revised",
            field=models.DateField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_of_revision",
            field=models.DateField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_per_agreement",
            field=models.DateField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_per_decision",
            field=models.DateField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_received",
            field=models.DateField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="effectiveness_cost",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="export_to",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="fund_disbursed",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="fund_disbursed_psc",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funds_allocated",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="hcfc_stage",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="impact",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="impact_co2mt",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="impact_prod_co2mt",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="impact_production",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="incomplete",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="intersessional_approval",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="issue",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="issue_description",
            field=models.TextField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="loan",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="local_ownership",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meeting_transf",
            field=models.ForeignKey(
                blank=True,
                help_text="Old meeting field used for transferred projects.Should be removed in the future.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferred_projects",
                to="core.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="mya_code",
            field=models.CharField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="mya_subsector",
            field=models.CharField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="national_agency",
            field=models.CharField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ods_phasedout_co2mt",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="operating_cost",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="plan",
            field=models.TextField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="plus",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="products_manufactured",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_cost",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_duration",
            field=models.IntegerField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type_legacy",
            field=models.CharField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="retroactive_finance",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="reviewed_mfs",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="revision_number",
            field=models.TextField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="source_file",
            field=models.CharField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="stage",
            field=models.IntegerField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="submission_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bilateral cooperation", "Bilateral cooperation"),
                    ("investment project", "Investment project"),
                    ("work programme amendment", "Work programme amendment"),
                    (
                        "other doc: cpg, policy paper, business plan",
                        "Other doc: CPG, policy paper, business plan",
                    ),
                ],
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                max_length=164,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="submission_comments",
            field=models.TextField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="submission_number",
            field=models.IntegerField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="substance_phasedout",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.CharField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_fund_approved",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_grant",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_psc_cost",
            field=models.FloatField(
                blank=True,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="umbrella_project",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="withdrawn",
            field=models.BooleanField(
                default=False,
                help_text="\n    Old field from the initial imported data/implementation of projects.\n    TBD if the information can be transferred to the new structure.\n",
            ),
        ),
    ]
