# Generated by Django 4.2.17 on 2025-09-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0240_remove_project_aggregated_consumption_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_first_disbursement",
                    models.DateField(
                        blank=True, null=True, verbose_name="First Disbursement Date"
                    ),
                ),
                (
                    "date_planned_completion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Planned Date of Completion"
                    ),
                ),
                (
                    "date_actual_completion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date completed (Actual)"
                    ),
                ),
                (
                    "date_financial_completion",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date of Financial Completion",
                    ),
                ),
                (
                    "consumption_phased_out_odp",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Consumption ODP/MT Phased Out",
                    ),
                ),
                (
                    "consumption_phased_out_co2",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Consumption Phased Out in CO2-eq Tonnes",
                    ),
                ),
                (
                    "production_phased_out_odp",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Production ODP/MT Phased Out",
                    ),
                ),
                (
                    "production_phased_out_co2",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Production Phased Out in CO2-eq Tonnes",
                    ),
                ),
                (
                    "funds_disbursed",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Funds Disbursed (US$)"
                    ),
                ),
                (
                    "funds_committed",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Funds Committed (US$)"
                    ),
                ),
                (
                    "estimated_disbursement_current_year",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Estimated Disbursement in Current Year (US$)",
                    ),
                ),
                (
                    "support_cost_disbursed",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Support Cost Disbursed (US$)",
                    ),
                ),
                (
                    "support_cost_committed",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Support Cost Committed (US$)",
                    ),
                ),
                (
                    "disbursements_made_to_final_beneficiaries",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Disbursements made to final beneficiaries from FECO/MEP",
                    ),
                ),
                (
                    "funds_advanced",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Funds advanced (US$)"
                    ),
                ),
                ("last_year_remarks", models.TextField(blank=True)),
                ("current_year_remarks", models.TextField(blank=True)),
                (
                    "gender_policy",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Gender Policy for All Projects Approved from 85th Mtg",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_reports",
                        to="core.project",
                        verbose_name="Project",
                    ),
                ),
            ],
        ),
    ]
