# Generated by Django 4.2.17 on 2025-10-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0241_annualprojectreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decision",
            name="description",
        ),
        migrations.AddField(
            model_name="decision",
            name="internal_api_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="decision",
            name="number",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
