# Generated by Django 4.2.17 on 2025-10-01 14:18

import core.models.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0242_remove_decision_description_decision_internal_api_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualAgencyProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        max_length=16,
                        verbose_name="Submission status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnualProgressReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Year of the report")),
                (
                    "date_endorsed",
                    models.DateField(
                        blank=True, null=True, verbose_name="Endorsement date"
                    ),
                ),
                (
                    "remarks_endorsed",
                    models.TextField(verbose_name="Endorsement remarks"),
                ),
                (
                    "endorsed",
                    models.BooleanField(
                        default=False,
                        verbose_name="The annual progress report is endorsed",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="AnnualProjectReportFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=core.models.utils.get_protected_storage,
                        upload_to="project_report_files/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=128, verbose_name="File name"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            (
                                "annual_progress_financial_report",
                                "Annual Progress & Financial Report",
                            ),
                            ("other_supporting_document", "Other supporting document"),
                        ],
                        max_length=64,
                        verbose_name="File type",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="annualprojectreportfile",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="core.annualagencyprojectreport",
                verbose_name="The report the files are uploaded in",
            ),
        ),
        migrations.AddField(
            model_name="annualprogressreport",
            name="meeting_endorsed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_reports",
                to="core.meeting",
                verbose_name="Endorsement meeting",
            ),
        ),
        migrations.AddField(
            model_name="annualagencyprojectreport",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_project_reports",
                to="core.agency",
                verbose_name="Agency responsible for the progress report",
            ),
        ),
        migrations.AddField(
            model_name="annualagencyprojectreport",
            name="progress_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agency_project_reports",
                to="core.annualprogressreport",
                verbose_name="Annual Progress Report",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="report",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_reports",
                to="core.annualagencyprojectreport",
                verbose_name="Agency report",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="annualprojectreport",
            constraint=models.UniqueConstraint(
                fields=("project", "report"), name="unique_together_project_report"
            ),
        ),
        migrations.AddConstraint(
            model_name="annualprojectreportfile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("file_type", "annual_progress_financial_report")),
                fields=("report",),
                name="unique_annual_progress_file_per_report",
            ),
        ),
        migrations.AddConstraint(
            model_name="annualprogressreport",
            constraint=models.UniqueConstraint(
                fields=("year",), name="unique_year_annual_progress_report"
            ),
        ),
        migrations.AddConstraint(
            model_name="annualagencyprojectreport",
            constraint=models.UniqueConstraint(
                fields=("progress_report", "agency"),
                name="unique_together_progress_report_agency",
            ),
        ),
    ]
