# Generated by Django 4.2.17 on 2025-10-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0243_annualagencyprojectreport_annualprogressreport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="number_of_enterprises_assisted",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number_of_enterprises_assisted_actual",
        ),
    ]
