# Generated by Django 4.2.17 on 2025-10-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0244_remove_project_number_of_enterprises_assisted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="aggregated_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Aggregated consumption",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="baseline",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Baseline",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cost_effectiveness",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ Kg) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cost_effectiveness_co2",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ CO2-eq) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_end_date",
            field=models.DateField(blank=True, help_text="End date (MYA)", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_phase_out_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase out (CO2-eq t) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_phase_out_mt",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase out (Mt) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_phase_out_odp_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase out (ODP t) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_project_funding",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Project Funding (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_start_date",
            field=models.DateField(blank=True, help_text="Start date (MYA)", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="mya_support_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Support Cost (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_enterprises",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises (MYA)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_enterprises_assisted",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises assisted", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of production lines assisted (MYA)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="starting_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Starting point",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="targets",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Targets",
                max_digits=30,
                null=True,
            ),
        ),
    ]
