# Generated by Django 4.2.17 on 2025-10-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0245_project_aggregated_consumption_project_baseline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_external_service",
            field=models.BooleanField(
                default=False,
                help_text="User is an external service that consumes our API - e.g. ekimetrics",
            ),
        ),
    ]
