# Generated by Django 4.2.17 on 2025-10-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0233_user_is_external_service"),
        ("core", "0245_project_aggregated_consumption_project_baseline_and_more"),
    ]

    operations = []
