# Generated by Django 4.2.17 on 2025-10-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0245_project_aggregated_consumption_project_baseline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="meeting_approved",
        ),
    ]
