# Generated by Django 4.2.17 on 2025-10-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0246_merge_20251021_0828"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="meeting_approved",
        ),
    ]
