# Generated by Django 4.2.17 on 2025-10-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0247_remove_project_meeting_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="baseline",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_phase_out_co2_eq_t",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_phase_out_mt",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_phase_out_odp_t",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_project_funding",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_start_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="mya_support_cost",
        ),
        migrations.RemoveField(
            model_name="project",
            name="starting_point",
        ),
        migrations.RemoveField(
            model_name="project",
            name="targets",
        ),
        migrations.AlterField(
            model_name="project",
            name="cost_effectiveness",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ Kg)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost_effectiveness_co2",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ CO2-eq)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_enterprises",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True, help_text="Number of production lines assisted", null=True
            ),
        ),
    ]
