# Generated by Django 4.2.17 on 2025-10-27 13:19

import os
from django.db import migrations, models
from django.db.models import Case, When, Value


def forward(apps, schema_editor):
    if os.getenv("PYTEST_CURRENT_TEST"):  # Skip if running pytest
        return

    Project = apps.get_model("core", "Project")

    Project.objects.update(
        blanket_or_individual_consideration=Case(
            When(
                individual_consideration=True,
                then=Value("individual"),
            ),
            When(
                individual_consideration=False,
                then=Value("blanket"),
            ),
        )
    )


def reverse(apps, schema_editor):
    if os.getenv("PYTEST_CURRENT_TEST"):  # Skip if running pytest
        return

    Project = apps.get_model("core", "Project")

    Project.objects.update(
        individual_consideration=Case(
            When(
                blanket_or_individual_consideration="individual",
                then=Value(True),
            ),
            When(
                blanket_or_individual_consideration="blanket",
                then=Value(False),
            ),
            default=Value(None),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0248_remove_project_baseline_remove_project_mya_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="blanket_or_individual_consideration",
            field=models.CharField(
                choices=[("blanket", "Blanket"), ("individual", "Individual")],
                help_text="\n            Blanket or Individual consideration.\n            This field is needed for analyses at the recommendation stage for QA unit.\n            And it is for MLFS users to select at the review stage.\n        ",
                max_length=256,
                null=True,
            ),
        ),
        migrations.RunPython(
            forward,
            reverse,
            atomic=False,
        ),
        migrations.RemoveField(
            model_name="project",
            name="individual_consideration",
        ),
    ]
