# Generated by Django 4.2.17 on 2025-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0249_annualagencyprojectreport_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualagencyprojectreport",
            name="is_unlocked",
            field=models.BooleanField(
                default=False,
                help_text="When True, agency can edit even when status is SUBMITTED",
            ),
        ),
    ]
