# Generated by Django 4.2.17 on 2025-10-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0249_remove_project_individual_consideration_and_more"),
        ("core", "0250_annualagencyprojectreport_is_unlocked"),
    ]

    operations = []
