# Generated by Django 4.2.17 on 2025-10-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0251_merge_20251029_0857"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metaproject",
            name="new_code",
        ),
        migrations.AddField(
            model_name="metaproject",
            name="umbrella_code",
            field=models.CharField(
                blank=True,
                help_text="\n            Code of the umbrella project (MetaProject model).\n            It is used to associate projects under the same umbrella.\n            Format: meta-/<country-3-letter-code>/<8-digit-unique-number>\n        ",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Multi-year agreement", "Multi-year agreement"),
                    ("Individual", "Individual"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="lead_agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead_projects",
                to="core.agency",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="metacode",
            field=models.CharField(
                blank=True,
                help_text="The metacode that is particular to each project. Initially filled from the MetaProject code.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Obsolete. Replaced by the metacode in Project model.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="blanket_or_individual_consideration",
            field=models.CharField(
                blank=True,
                choices=[("blanket", "Blanket"), ("individual", "Individual")],
                help_text="\n            Blanket or Individual consideration.\n            This field is needed for analyses at the recommendation stage for QA unit.\n            And it is for MLFS users to select at the review stage.\n        ",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meta_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="core.metaproject",
            ),
        ),
    ]
