# Generated by Django 4.2.17 on 2025-11-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0252_remove_metaproject_new_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfield",
            name="mlfs_only",
            field=models.BooleanField(
                default=False,
                help_text="If True, the field is only visible to MLFS users",
            ),
        ),
    ]
