# Generated by Django 4.2.17 on 2025-11-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0253_projectfield_mlfs_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectfile",
            name="type",
            field=models.CharField(
                choices=[
                    ("main_submission", "Main project submission"),
                    ("verification_report", "Verification report"),
                    ("endorsement_letter", "Endorsement letter from government"),
                    ("final_proposal", "Final project proposal"),
                    ("project_review_comments", "Project review comments"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
