# Generated by Django 4.2.17 on 2025-11-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0254_projectfile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualprojectreport",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Project status code for reporting year",
                max_length=10,
            ),
        ),
    ]
