# Generated by Django 4.2.17 on 2025-11-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0255_annualprojectreport_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="total_phase_out_co2_tonnes",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Total substance phase-out (CO2-eq tonnes). Filled during approval process.",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_phase_out_metric_tonnes",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Total substance phase-out (metric tonnes). Filled during approval process.",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_phase_out_odp_tonnes",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Total substance phase-out (ODP tonnes). Filled during approval process.",
                max_digits=30,
                null=True,
            ),
        ),
    ]
