# Generated by Django 4.2.17 on 2025-11-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0256_project_total_phase_out_co2_tonnes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfile",
            name="type",
            field=models.CharField(
                choices=[
                    ("main_submission", "Main project submission"),
                    ("verification_report", "Verification report"),
                    ("endorsement_letter", "Endorsement letter from government"),
                    ("final_proposal", "Final project proposal"),
                    ("project_review_comments", "Project review comments"),
                    ("transferred_project_proposal", "Transferred project proposal"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
