# Generated by Django 4.2.17 on 2025-11-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0257_alter_projectfile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaproject",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta_projects",
                to="core.projectcluster",
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meta_projects",
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="serial_number",
            field=models.IntegerField(
                blank=True,
                help_text="\n            Old field from the initial imported data/implementation of projects.\n            It is required in the generation of the project sub-code.\n            The serial number should be saved when the project is approved and\n            should not change afterwards. It should be used when re-generating the project sub-code.\n        ",
                null=True,
            ),
        ),
    ]
