# Generated by Django 4.2.17 on 2025-11-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0257_alter_projectfile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualprogressreport",
            name="remarks_endorsed",
            field=models.TextField(max_length=400, verbose_name="Endorsement remarks"),
        ),
    ]
