# Generated by Django 4.2.17 on 2025-11-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0258_metaproject_cluster_metaproject_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualprogressreport",
            name="remarks_endorsed",
            field=models.TextField(max_length=400, verbose_name="Endorsement remarks"),
        ),
    ]
