# Generated by Django 4.2.17 on 2025-11-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0258_metaproject_cluster_metaproject_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="transferred_from",
            field=models.ForeignKey(
                blank=True,
                help_text="If this project is a transferred project, this field will be set to the original project",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transferred_projects",
                to="core.project",
            ),
        ),
    ]
