# Generated by Django 4.2.17 on 2025-12-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0259_project_transferred_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcluster",
            name="annex_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="List of annex groups that this cluster belongs to. To be used for filtering substance lists.",
                related_name="project_clusters",
                to="core.group",
            ),
        ),
    ]
