# Generated by Django 4.2.17 on 2025-12-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0259_alter_annualprogressreport_remarks_endorsed"),
        ("core", "0260_projectcluster_annex_groups"),
    ]

    operations = []
