# Generated by Django 4.2.17 on 2025-12-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0261_merge_20251202_1319"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualprogressreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="annualprogressreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_progress_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User who initiated this APR",
            ),
        ),
    ]
