# Generated by Django 4.2.17 on 2025-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0262_annualprogressreport_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="aggregated_consumption_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Aggregated consumption (actual)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cost_effectiveness_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ Kg) actual",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cost_effectiveness_co2_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ CO2-eq) actual",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_enterprises_actual",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises (actual)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_enterprises_assisted_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of enterprises assisted (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_production_lines_assisted_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of production lines assisted (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="aggregated_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Aggregated consumption (planned)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost_effectiveness",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ Kg) (planned)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost_effectiveness_co2",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US$/ CO2-eq) (planned)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_enterprises",
            field=models.IntegerField(
                blank=True, help_text="Number of enterprises (planned)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_enterprises_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of enterprises assisted (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of production lines assisted (planned)",
                null=True,
            ),
        ),
    ]
