# Generated by Django 4.2.17 on 2025-12-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0263_project_aggregated_consumption_actual_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="agencies",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="projectenterpriseodsodp",
            name="ods_replacement",
        ),
        migrations.RemoveField(
            model_name="projectenterpriseodsodp",
            name="ods_replacement_phase_in",
        ),
        migrations.RemoveField(
            model_name="projectenterpriseodsodp",
            name="phase_out_mt",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="date_of_approval",
            field=models.DateField(
                blank=True,
                help_text="Month and year of meeting when project was approved",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="date_of_revision",
            field=models.DateField(
                blank=True,
                help_text="Date of the latest revision of the project",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting where the project was approved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enterprises",
                to="core.meeting",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                help_text="Sector related to the enterprise (e.g., aerosol, fire-fighting, foam, production,\n                    refrigeration, solvent)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enterprises",
                to="core.projectsector",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="stage",
            field=models.CharField(
                blank=True,
                help_text="Stage of the HPMP relating to the enterprise",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="subsector",
            field=models.ForeignKey(
                blank=True,
                help_text="Name of the sub-sector within each sector",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enterprises",
                to="core.projectsubsector",
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="actual_completion_date",
            field=models.DateField(
                blank=True,
                help_text="Actual date of completion of the project",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="agency",
            field=models.ForeignKey(
                default=29,
                help_text="Agency responsible for this project enterprise entry",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_enterprises",
                to="core.agency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="agency_remarks",
            field=models.TextField(
                blank=True,
                help_text="Text on remarks relating to the project by agency if any",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="capital_cost_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Capital cost disbursed to the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="co_financing_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Co-financing actual for the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="co_financing_planned",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Co-financing planned for the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="cost_effectiveness_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cost effectiveness actual (US $/kg)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="date_of_report",
            field=models.DateField(
                blank=True,
                help_text="Date of the latest report of the project",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="excom_provision",
            field=models.TextField(
                blank=True,
                help_text="Text on ExCom provision relating to the project if any",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="funds_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Funds approved/allocated for the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="funds_transferred",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Funds transferred from one agency to another (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="impact",
            field=models.TextField(
                blank=True, help_text="Total ODP tonnes phased out", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="operating_cost_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Operating cost disbursed to the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="planned_completion_date",
            field=models.DateField(
                blank=True,
                help_text="Expected date of completion of the project",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="project_duration",
            field=models.IntegerField(
                blank=True,
                help_text="Duration of project implementation from approval (in months)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="project_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of project (e.g., demonstration, investment, technical assistance)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_enterprises",
                to="core.projecttype",
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="secretariat_remarks",
            field=models.TextField(
                blank=True,
                help_text="Text on remarks relating to the project by secretariat if any",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterpriseodsodp",
            name="chemical_phased_in",
            field=models.FloatField(
                blank=True,
                help_text="\n            Amount of alternative being used in place of controlled chemical (mt)\n        ",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterpriseodsodp",
            name="consumption",
            field=models.FloatField(
                blank=True,
                help_text="\n        Amount of the controlled substance to be phased out (mt)\n    ",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterpriseodsodp",
            name="selected_alternative",
            field=models.CharField(
                blank=True,
                help_text="\n        Name of alternative technology or chemical\n        ",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="capital_cost_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Capital cost approved/allocated for the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="funds_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Funds disbursed to the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="operating_cost_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Operating cost approved/allocated for enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
    ]
