# Generated by Django 4.2.17 on 2025-12-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0263_project_aggregated_consumption_actual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualprojectreport",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Project status name for reporting year",
                max_length=255,
            ),
        ),
    ]
