# Generated by Django 4.2.17 on 2025-12-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0264_alter_annualprojectreport_status"),
        ("core", "0264_remove_enterprise_agencies_remove_enterprise_remarks_and_more"),
    ]

    operations = []
