# Generated by Django 4.2.17 on 2025-12-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0265_merge_20251215_1442"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="date_of_approval",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="meeting",
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="chemical_phased_out",
            field=models.FloatField(
                blank=True,
                help_text="Total quantity of chemical phased out (mt)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="date_of_approval",
            field=models.DateField(
                blank=True,
                help_text="Month and year of meeting when project was approved",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectenterprise",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Meeting where the project was approved",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enterprises",
                to="core.meeting",
            ),
        ),
    ]
