# Generated by Django 4.2.17 on 2025-12-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0266_remove_enterprise_date_of_approval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectenterprise",
            name="capital_cost_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Capital cost approved/allocated for the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="capital_cost_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Capital cost disbursed to the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="co_financing_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Co-financing actual for the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="co_financing_planned",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Co-financing planned for the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="cost_effectiveness_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Cost effectiveness actual (US $/kg)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="funds_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Funds approved/allocated for the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="funds_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Funds disbursed to the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="funds_transferred",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Funds transferred from one agency to another (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="operating_cost_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Operating cost approved/allocated for enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectenterprise",
            name="operating_cost_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Operating cost disbursed to the enterprise (US $)",
                max_digits=20,
                null=True,
            ),
        ),
    ]
