# Generated by Django 4.2.17 on 2025-12-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0267_alter_projectenterprise_capital_cost_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualprojectreport",
            name="adjustment_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Calculated adjustment from latest version vs version 3",
                null=True,
                verbose_name="Adjustment (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="agency_name_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.agency.name at time of reporting",
                max_length=255,
                null=True,
                verbose_name="Agency Name (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="approved_funding_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Snapshot of version 3 total_fund",
                null=True,
                verbose_name="Approved Funding (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="approved_funding_plus_adjustment_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Total approved funding including adjustments",
                null=True,
                verbose_name="Approved Funding + Adjustment (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="balance_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Calculated balance: approved_funding - funds_disbursed",
                null=True,
                verbose_name="Balance (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="cluster_name_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.cluster.name at time of reporting",
                max_length=255,
                null=True,
                verbose_name="Cluster Name (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="consumption_phased_out_co2_proposal_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Snapshot of version 3 consumption phase out CO2",
                null=True,
                verbose_name="Consumption CO2 Proposal (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="consumption_phased_out_odp_proposal_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Snapshot of version 3 consumption phase out ODP",
                null=True,
                verbose_name="Consumption ODP Proposal (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="country_name_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.country.name at time of reporting",
                max_length=255,
                null=True,
                verbose_name="Country Name (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="date_approved_denorm",
            field=models.DateField(
                blank=True,
                help_text="Snapshot of project version 3 approval date",
                null=True,
                verbose_name="Date Approved (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="date_completion_proposal_denorm",
            field=models.DateField(
                blank=True,
                help_text="Snapshot of project version 3 completion date",
                null=True,
                verbose_name="Date Completion Proposal (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="date_of_completion_per_agreement_or_decisions_denorm",
            field=models.DateField(
                blank=True,
                help_text="Latest version date_completion at time of reporting",
                null=True,
                verbose_name="Date Completion per Agreement (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="implementation_delays_status_report_decisions_denorm",
            field=models.CharField(
                blank=True,
                help_text="Implementation delays from status reports",
                max_length=500,
                null=True,
                verbose_name="Implementation Delays (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="legacy_code_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.legacy_code at time of reporting",
                max_length=128,
                null=True,
                verbose_name="Legacy Code (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="meta_code_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.metacode at time of reporting",
                max_length=255,
                null=True,
                verbose_name="Meta Code (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="pcr_due_denorm",
            field=models.BooleanField(
                blank=True,
                help_text="Whether PCR is due (ONG to COM/FIN transition)",
                null=True,
                verbose_name="PCR Due (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="per_cent_funds_disbursed_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Calculated percentage of funds disbursed",
                null=True,
                verbose_name="Percent Funds Disbursed (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="production_phased_out_co2_proposal_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Snapshot of version 3 production phase out CO2",
                null=True,
                verbose_name="Production CO2 Proposal (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="production_phased_out_odp_proposal_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Snapshot of version 3 production phase out ODP",
                null=True,
                verbose_name="Production ODP Proposal (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="project_code_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.code at time of reporting",
                max_length=128,
                null=True,
                verbose_name="Project Code (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="project_title_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.title at time of reporting",
                max_length=256,
                null=True,
                verbose_name="Project Title (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="region_name_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.country.parent.name at time of reporting",
                max_length=255,
                null=True,
                verbose_name="Region Name (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="sector_code_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.sector.code at time of reporting",
                max_length=10,
                null=True,
                verbose_name="Sector Code (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="support_cost_adjustment_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Calculated support cost adjustment from latest version",
                null=True,
                verbose_name="Support Cost Adjustment (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="support_cost_approved_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Snapshot of version 3 support_cost_psc",
                null=True,
                verbose_name="Support Cost Approved (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="support_cost_approved_plus_adjustment_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Total support cost including adjustments",
                null=True,
                verbose_name="Support Cost + Adjustment (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="support_cost_balance_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Calculated support cost balance",
                null=True,
                verbose_name="Support Cost Balance (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="type_code_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.project_type.code at time of reporting",
                max_length=10,
                null=True,
                verbose_name="Type Code (denormalized)",
            ),
        ),
    ]
