# Generated by Django 4.2.17 on 2026-01-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0234_module_country_modules"),
        ("core", "0267_alter_projectenterprise_capital_cost_approved_and_more"),
    ]

    operations = []
