# Generated by Django 4.2.17 on 2026-01-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0269_apr_denormalized_fields_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annualprojectreport",
            name="balance_denorm",
        ),
        migrations.RemoveField(
            model_name="annualprojectreport",
            name="per_cent_funds_disbursed_denorm",
        ),
        migrations.RemoveField(
            model_name="annualprojectreport",
            name="support_cost_balance_denorm",
        ),
    ]
