# Generated by Django 4.2.17 on 2026-02-04 00:42

import core.models.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0270_apr_denormalized_fields_data_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PCRCauseOfDelay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of causes and action taken (150-250 words suggested)"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Cause of Delay",
                "verbose_name_plural": "PCR Causes of Delay",
                "ordering": ["date_created"],
            },
        ),
        migrations.CreateModel(
            name="PCRGenderPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "PCR Gender Phase",
                "verbose_name_plural": "PCR Gender Phases",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PCRLessonLearned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of lesson learned (150-250 words suggested)"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Lesson Learned",
                "verbose_name_plural": "PCR Lessons Learned",
                "ordering": ["date_created"],
            },
        ),
        migrations.CreateModel(
            name="PCRProjectElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "PCR Project Element",
                "verbose_name_plural": "PCR Project Elements",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PCRSDG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., 'goal_1', 'goal_2'", max_length=20, unique=True
                    ),
                ),
                (
                    "number",
                    models.IntegerField(help_text="SDG number (1-17)", unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'No poverty', 'Zero hunger'", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SDG",
                "verbose_name_plural": "SDGs",
                "ordering": ["number"],
            },
        ),
        migrations.RenameModel(
            old_name="PCRActivity",
            new_name="PCRActivityLegacy",
        ),
        migrations.RenameModel(
            old_name="PCRDelayExplanation",
            new_name="PCRDelayExplanationLegacy",
        ),
        migrations.RenameModel(
            old_name="PCRLearnedLessons",
            new_name="PCRLearnedLessonsLegacy",
        ),
        migrations.AlterModelOptions(
            name="delaycategory",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name_plural": "Delay Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="learnedlessoncategory",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name_plural": "Learned Lesson Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="pcractivitylegacy",
            options={
                "verbose_name": "PCR Activity (Legacy)",
                "verbose_name_plural": "PCR Activities (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="pcrdelayexplanationlegacy",
            options={
                "verbose_name": "PCR Delay Explanation (Legacy)",
                "verbose_name_plural": "PCR Delay Explanations (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="pcrlearnedlessonslegacy",
            options={
                "verbose_name": "PCR Learned Lesson (Legacy)",
                "verbose_name_plural": "PCR Learned Lessons (Legacy)",
            },
        ),
        migrations.AddField(
            model_name="delaycategory",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique code",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="delaycategory",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the delay cause",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learnedlessoncategory",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Unique code for programmatic access",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="learnedlessoncategory",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of the lesson category",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="delaycategory",
            name="sort_order",
            field=models.FloatField(default=0, help_text="Display order in forms"),
        ),
        migrations.AlterField(
            model_name="learnedlessoncategory",
            name="sort_order",
            field=models.FloatField(default=0, help_text="Display order in forms"),
        ),
        migrations.AlterModelTable(
            name="pcractivitylegacy",
            table="core_pcractivity",
        ),
        migrations.AlterModelTable(
            name="pcrdelayexplanationlegacy",
            table="core_pcrdelayexplanation",
        ),
        migrations.AlterModelTable(
            name="pcrlearnedlessonslegacy",
            table="core_pcrlearnedlessons",
        ),
        migrations.CreateModel(
            name="ProjectCompletionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("submitted", "Submitted")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "first_submission_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date of first submission - never changes after first submit",
                        null=True,
                    ),
                ),
                (
                    "last_submission_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date of most recent submission - updated on each submit",
                        null=True,
                    ),
                ),
                (
                    "financial_figures_status",
                    models.CharField(
                        choices=[("provisional", "Provisional"), ("final", "Final")],
                        help_text="Indicate whether the financial figures are Provisional or Final",
                        max_length=20,
                    ),
                ),
                (
                    "financial_figures_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanations if needed (150-250 words suggested)",
                        null=True,
                    ),
                ),
                (
                    "enterprise_addresses",
                    models.TextField(
                        blank=True,
                        help_text="Address(es) of enterprise(s) and project site(s) (150-250 words suggested)",
                        null=True,
                    ),
                ),
                (
                    "all_goals_achieved",
                    models.BooleanField(
                        blank=True, help_text="All project goals achieved?", null=True
                    ),
                ),
                (
                    "goals_not_achieved_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Required if all goals not achieved (150-250 words suggested)",
                        null=True,
                    ),
                ),
                (
                    "overall_rating",
                    models.CharField(
                        choices=[
                            ("highly_satisfactory", "Highly satisfactory"),
                            ("satisfactory_planned", "Satisfactory as planned"),
                            (
                                "satisfactory_not_planned",
                                "Satisfactory but not as planned",
                            ),
                            ("unsatisfactory", "Unsatisfactory"),
                            ("other", "Other, please specify"),
                        ],
                        help_text="Choose the rating from the list",
                        max_length=50,
                    ),
                ),
                (
                    "overall_rating_other",
                    models.TextField(
                        blank=True, help_text="Specify if rating is 'Other'", null=True
                    ),
                ),
                (
                    "overall_rating_explanation",
                    models.TextField(
                        help_text="Please explain your rating (150-250 words suggested)"
                    ),
                ),
                (
                    "completion_report_done_by",
                    models.CharField(
                        choices=[
                            ("lead_agency", "Lead Agency"),
                            ("cooperating_agency", "Cooperating Agency"),
                            ("nou", "National coordinating agency/NOU"),
                            ("local_agency", "Local executing agency"),
                            ("other", "Other"),
                        ],
                        help_text="Completion report done by",
                        max_length=50,
                    ),
                ),
                (
                    "completion_report_done_by_other",
                    models.CharField(
                        blank=True,
                        help_text="Specify if 'Other'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "total_odp_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Aggregated from tranches - ODP phase-out (Approved)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "total_odp_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Aggregated from tranches - ODP phase-out (Actual)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "total_hfc_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Aggregated from tranches - HFCs phased-down CO2-eq tonnes (Approved)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "total_hfc_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Aggregated from tranches - HFCs phased-down CO2-eq tonnes (Actual)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "total_enterprises",
                    models.IntegerField(
                        blank=True,
                        help_text="Aggregated from tranches - Number of enterprises",
                        null=True,
                    ),
                ),
                (
                    "total_trainees",
                    models.IntegerField(
                        blank=True,
                        help_text="Aggregated from tranches - Total number of trainees",
                        null=True,
                    ),
                ),
                (
                    "total_funding_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Aggregated from tranches - Total MLF funding approved (US$)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "total_funding_disbursed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Aggregated from tranches - Total MLF funding disbursed (US$)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "total_funding_returned",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated: Approved - Disbursed",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the PCR",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pcrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meta_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="For MYA projects - PCR initiated at metacode level",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completion_reports",
                        to="core.metaproject",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="For IND projects - PCR initiated at project level",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completion_reports",
                        to="core.project",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who submitted the PCR",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_pcrs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Completion Report",
                "verbose_name_plural": "Project Completion Reports",
            },
        ),
        migrations.CreateModel(
            name="PCRTrancheData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_code", models.CharField(max_length=100)),
                (
                    "project_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("tranche_number", models.IntegerField(blank=True, null=True)),
                ("date_approved", models.DateField()),
                ("actual_date_completion", models.DateField(blank=True, null=True)),
                (
                    "funds_approved",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Funds approved (US$)",
                        max_digits=15,
                    ),
                ),
                (
                    "odp_phaseout_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="ODP phase-out approved",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "odp_phaseout_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="ODP phase-out actual",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "hfc_phasedown_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="HFCs phased-down CO2-eq tonnes approved",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "hfc_phasedown_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="HFCs phased-down CO2-eq tonnes actual",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "funds_disbursed",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Funds disbursed (US$)",
                        max_digits=15,
                    ),
                ),
                (
                    "planned_completion_date",
                    models.DateField(help_text="Planned date of completion"),
                ),
                (
                    "planned_duration_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Calculated: planned_completion_date - date_approved",
                        null=True,
                    ),
                ),
                (
                    "actual_duration_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Calculated: actual_date_completion - date_approved",
                        null=True,
                    ),
                ),
                (
                    "delay_months",
                    models.IntegerField(
                        blank=True,
                        help_text="Calculated: planned_completion_date - actual_date_completion",
                        null=True,
                    ),
                ),
                (
                    "number_of_enterprises",
                    models.IntegerField(
                        default=0, help_text="Total number of enterprises"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agency"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tranches",
                        to="core.projectcompletionreport",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The specific project/tranche this data represents",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Tranche Data",
                "verbose_name_plural": "PCR Tranche Data",
            },
        ),
        migrations.CreateModel(
            name="PCRTraineeCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                (
                    "count",
                    models.IntegerField(default=0, help_text="Number of trainees"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tranche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainees",
                        to="core.pcrtranchedata",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Trainee Count",
                "verbose_name_plural": "PCR Trainee Counts",
            },
        ),
        migrations.CreateModel(
            name="PCRSupportingEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload document, photo, or file",
                        null=True,
                        storage=core.models.utils.get_protected_storage,
                        upload_to="pcr_evidence/",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Or provide link to website/repository",
                        null=True,
                    ),
                ),
                (
                    "related_section",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("project_results", "Project results"),
                            ("causes_delay", "Causes of delay"),
                            ("lessons_learned", "Lessons learned"),
                            ("gender", "Gender mainstreaming"),
                            ("sdgs", "SDGs contribution"),
                            (
                                "summary_data",
                                "Summary of key data on project and implementation delay",
                            ),
                        ],
                        help_text="PCR section this evidence relates to",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the evidence", null=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_evidence",
                        to="core.projectcompletionreport",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Supporting Evidence",
                "verbose_name_plural": "PCR Supporting Evidence",
                "ordering": ["related_section", "date_created"],
            },
        ),
        migrations.CreateModel(
            name="PCRSDGContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of contribution to this SDG (150-250 words suggested)"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdg_contributions",
                        to="core.projectcompletionreport",
                    ),
                ),
                (
                    "sdg",
                    models.ForeignKey(
                        help_text="SDG goal",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pcrsdg",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR SDG Contribution",
                "verbose_name_plural": "PCR SDG Contributions",
                "ordering": ["sdg__number"],
            },
        ),
        migrations.CreateModel(
            name="PCRRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_text",
                    models.TextField(
                        help_text="Recommendations for future project design and implementation (150-250 words suggested)"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="core.projectcompletionreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Recommendation",
                "verbose_name_plural": "PCR Recommendations",
                "ordering": ["date_created"],
            },
        ),
        migrations.CreateModel(
            name="PCRProjectActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "activity_type",
                    models.TextField(
                        help_text="Type of activity (150-250 words suggested)"
                    ),
                ),
                (
                    "planned_outputs",
                    models.TextField(
                        help_text="Planned output(s) (150-250 words suggested)"
                    ),
                ),
                (
                    "actual_outputs",
                    models.TextField(
                        help_text="Actual activity output(s) (150-250 words suggested)"
                    ),
                ),
                (
                    "additional_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Additional remarks (150-250 words suggested)",
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.projectcompletionreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Project Activity",
                "verbose_name_plural": "PCR Project Activities",
                "ordering": ["date_created"],
            },
        ),
        migrations.CreateModel(
            name="PCROverallAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("highly_satisfactory", "Highly satisfactory"),
                            ("satisfactory_planned", "Satisfactory as planned"),
                            (
                                "satisfactory_not_planned",
                                "Satisfactory but not as planned",
                            ),
                            ("unsatisfactory", "Unsatisfactory"),
                            ("other", "Other, please specify"),
                        ],
                        help_text="Choose the rating from the list",
                        max_length=50,
                    ),
                ),
                (
                    "rating_other",
                    models.TextField(
                        blank=True, help_text="Specify if rating is 'Other'", null=True
                    ),
                ),
                (
                    "rating_explanation",
                    models.TextField(
                        help_text="Please explain your rating (150-250 words suggested)"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overall_assessments",
                        to="core.projectcompletionreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Overall Assessment",
                "verbose_name_plural": "PCR Overall Assessments",
            },
        ),
        migrations.CreateModel(
            name="PCRLessonLearnedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_description",
                    models.TextField(
                        blank=True,
                        help_text="Description specific to this lesson category",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.learnedlessoncategory",
                    ),
                ),
                (
                    "lesson_learned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="core.pcrlessonlearned",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Lesson Learned Category",
                "verbose_name_plural": "PCR Lesson Learned Categories",
            },
        ),
        migrations.AddField(
            model_name="pcrlessonlearned",
            name="pcr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_learned",
                to="core.projectcompletionreport",
            ),
        ),
        migrations.AddField(
            model_name="pcrlessonlearned",
            name="project_element",
            field=models.ForeignKey(
                help_text="Project element/component for this lesson",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.pcrprojectelement",
            ),
        ),
        migrations.CreateModel(
            name="PCRGenderMainstreaming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_met",
                    models.BooleanField(
                        help_text="Yes/No indicator from progress report"
                    ),
                ),
                (
                    "qualitative_description",
                    models.TextField(
                        help_text="Qualitative description (150-250 words suggested)"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gender_mainstreaming",
                        to="core.projectcompletionreport",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        help_text="Gender mainstreaming phase",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pcrgenderphase",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Gender Mainstreaming",
                "verbose_name_plural": "PCR Gender Mainstreaming",
            },
        ),
        migrations.CreateModel(
            name="PCREquipmentDisposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_name",
                    models.CharField(
                        help_text="Name of equipment rendered unusable", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description (150-250 words suggested)"),
                ),
                (
                    "disposal_type",
                    models.CharField(help_text="Disposal method", max_length=100),
                ),
                ("disposal_date", models.DateField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tranche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_disposals",
                        to="core.pcrtranchedata",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Equipment Disposal",
                "verbose_name_plural": "PCR Equipment Disposals",
            },
        ),
        migrations.CreateModel(
            name="PCREnterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.TextField(help_text="Enterprise address and details"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tranche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprises",
                        to="core.pcrtranchedata",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Enterprise",
                "verbose_name_plural": "PCR Enterprises",
            },
        ),
        migrations.CreateModel(
            name="PCRComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("overview", "Overview"),
                            ("project_results", "Project results"),
                            ("causes_delay", "Causes of delay"),
                            ("lessons_learned", "Lessons learned"),
                            ("gender", "Gender mainstreaming"),
                            ("sdgs", "SDGs contribution"),
                            ("summary_data", "Summary of key data"),
                        ],
                        help_text="Section this comment relates to",
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("lead_agency", "Lead agency"),
                            ("cooperating_agency", "Cooperating agency"),
                            ("government_nou", "Government/NOU"),
                            ("enterprises", "Enterprises"),
                            ("consultants", "Consultants"),
                            (
                                "secretariat",
                                "Project management officers in the Multilateral Fund Secretariat",
                            ),
                            ("other", "Other, please specify"),
                        ],
                        help_text="Entity providing the comment",
                        max_length=50,
                    ),
                ),
                (
                    "entity_type_other",
                    models.CharField(
                        blank=True,
                        help_text="Specify if entity type is 'Other'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "comment_text",
                    models.TextField(
                        help_text="Comment text (150-250 words suggested)"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.projectcompletionreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Comment",
                "verbose_name_plural": "PCR Comments",
                "ordering": ["section", "date_created"],
            },
        ),
        migrations.CreateModel(
            name="PCRCauseOfDelayCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_description",
                    models.TextField(
                        blank=True,
                        help_text="Description specific to this delay category",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.delaycategory",
                    ),
                ),
                (
                    "cause_of_delay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="core.pcrcauseofdelay",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Cause of Delay Category",
                "verbose_name_plural": "PCR Cause of Delay Categories",
            },
        ),
        migrations.AddField(
            model_name="pcrcauseofdelay",
            name="pcr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="causes_of_delay",
                to="core.projectcompletionreport",
            ),
        ),
        migrations.AddField(
            model_name="pcrcauseofdelay",
            name="project_element",
            field=models.ForeignKey(
                help_text="Project element/component experiencing delays",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.pcrprojectelement",
            ),
        ),
        migrations.CreateModel(
            name="PCRAlternativeTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "substance_from",
                    models.ForeignKey(
                        help_text="Substance converted from",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pcr_conversion_from",
                        to="core.substance",
                    ),
                ),
                (
                    "substance_to",
                    models.ForeignKey(
                        help_text="Substance converted to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pcr_conversion_to",
                        to="core.substance",
                    ),
                ),
                (
                    "tranche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technologies",
                        to="core.pcrtranchedata",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCR Alternative Technology",
                "verbose_name_plural": "PCR Alternative Technologies",
            },
        ),
        migrations.AddConstraint(
            model_name="projectcompletionreport",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("meta_project__isnull", False), ("project__isnull", True)
                    ),
                    models.Q(
                        ("meta_project__isnull", True), ("project__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="pcr_either_meta_project_or_project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pcrtranchedata",
            unique_together={("pcr", "project")},
        ),
        migrations.AlterUniqueTogether(
            name="pcrtraineecount",
            unique_together={("tranche", "gender")},
        ),
        migrations.AlterUniqueTogether(
            name="pcrlessonlearnedcategory",
            unique_together={("lesson_learned", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="pcrgendermainstreaming",
            unique_together={("pcr", "phase")},
        ),
        migrations.AlterUniqueTogether(
            name="pcrcauseofdelaycategory",
            unique_together={("cause_of_delay", "category")},
        ),
    ]
