# Generated by Django 4.2.17 on 2026-02-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0270_apr_denormalized_fields_data_migration"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="unique_legacy_code_when_latest_project_is_none",
        ),
    ]
