# Generated by Django 4.2.17 on 2026-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0271_pcrcauseofdelay_pcrgenderphase_pcrlessonlearned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcompletionreport",
            name="is_unlocked",
            field=models.BooleanField(
                default=False,
                help_text="When True, agency can edit even when status is SUBMITTED",
            ),
        ),
    ]
