# Generated by Django 4.2.17 on 2026-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0271_remove_project_unique_legacy_code_when_latest_project_is_none"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metaproject",
            name="aggregated_consumption",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="baseline",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_aggregated_consumption",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_baseline",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_number_of_enterprises",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_number_of_enterprises_assisted",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_starting_point",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_targets",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="number_of_enterprises",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="number_of_enterprises_assisted",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="starting_point",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="targets",
        ),
        migrations.RemoveField(
            model_name="project",
            name="aggregated_consumption",
        ),
        migrations.RemoveField(
            model_name="project",
            name="aggregated_consumption_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="ban_of_equipment",
        ),
        migrations.RemoveField(
            model_name="project",
            name="ban_of_equipment_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="ban_of_substances",
        ),
        migrations.RemoveField(
            model_name="project",
            name="ban_of_substances_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="certification_system_for_technicians",
        ),
        migrations.RemoveField(
            model_name="project",
            name="certification_system_for_technicians_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="checklist_regulations",
        ),
        migrations.RemoveField(
            model_name="project",
            name="checklist_regulations_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="establishment_of_imp_exp_licensing",
        ),
        migrations.RemoveField(
            model_name="project",
            name="establishment_of_imp_exp_licensing_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="establishment_of_quota_systems",
        ),
        migrations.RemoveField(
            model_name="project",
            name="establishment_of_quota_systems_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_lvc",
        ),
        migrations.RemoveField(
            model_name="project",
            name="is_sme",
        ),
        migrations.RemoveField(
            model_name="project",
            name="kwh_year_saved",
        ),
        migrations.RemoveField(
            model_name="project",
            name="kwh_year_saved_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number_of_enterprises",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number_of_enterprises_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number_of_enterprises_assisted",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number_of_enterprises_assisted_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number_of_tools_sets_distributed",
        ),
        migrations.RemoveField(
            model_name="project",
            name="number_of_tools_sets_distributed_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="operation_of_reclamation_scheme",
        ),
        migrations.RemoveField(
            model_name="project",
            name="operation_of_reclamation_scheme_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="operation_of_recovery_and_recycling_scheme",
        ),
        migrations.RemoveField(
            model_name="project",
            name="operation_of_recovery_and_recycling_scheme_actual",
        ),
        migrations.RemoveField(
            model_name="project",
            name="quantity_hfc_23_by_product_generation_rate",
        ),
        migrations.RemoveField(
            model_name="project",
            name="quantity_hfc_23_by_product_generation_rate_actual",
        ),
        migrations.AddField(
            model_name="metaproject",
            name="baseline_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Baseline (CO2-eq tonnes)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="baseline_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Baseline (ODP tonnes)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_baseline_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Baseline (CO2-eq tonnes)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_baseline_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Baseline (ODP tonnes)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_number_of_both_sme_non_sme_not_directly_funded",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Number of both SMEs and non-SMEs included in the project but not directly funded (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_number_of_non_sme_directly_funded",
            field=models.IntegerField(
                blank=True,
                help_text="Number of non-SMEs directly funded (draft)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_number_of_smes_directly_funded",
            field=models.IntegerField(
                blank=True,
                help_text="Number of SMEs directly funded (draft)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_phase_out_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase out (CO2-eq tonnes) (MYA) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_project_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="MYA Total agreed costs in principle (US $) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_starting_point_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Starting point for aggregate reductions in consumption or production (CO2-eq tonnes) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_starting_point_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Starting point for aggregate reductions in consumption or production (ODP tonnes) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_target_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Target in the last year (CO2-eq tonnes) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_target_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Target in the last year (ODP tonnes) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="draft_target_reduction",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Target in the last year (reduction in %) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="number_of_both_sme_non_sme_not_directly_funded",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Number of both SMEs and non-SMEs included in the project but not directly funded",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="number_of_non_sme_directly_funded",
            field=models.IntegerField(
                blank=True, help_text="Number of non-SMEs directly funded", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="number_of_smes_directly_funded",
            field=models.IntegerField(
                blank=True, help_text="Number of SMEs directly funded", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="phase_out_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase out (CO2-eq tonnes) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="project_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="MYA Total agreed costs in principle (US $)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="starting_point_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Starting point for aggregate reductions in consumption or production (CO2-eq tonnes)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="starting_point_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Starting point for aggregate reductions in consumption or production (ODP tonnes)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="target_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Target in the last year (CO2-eq tonnes)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="target_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Target in the last year (ODP tonnes)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="target_reduction",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Target in the last year (reduction in %)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="consumption_level_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LVC", "LVC"),
                    ("Non-LVC", "Non-LVC"),
                    ("Not applicable", "Not applicable"),
                ],
                help_text="The field to be derived but with the option change the value for the KIP (As an example).",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="end_users",
            field=models.IntegerField(blank=True, help_text="End users", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="end_users_actual",
            field=models.IntegerField(
                blank=True, help_text="End users (actual)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="energy_savings",
            field=models.FloatField(
                blank=True, help_text="Energy savings - planned (kWh/year)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="energy_savings_actual",
            field=models.FloatField(
                blank=True, help_text="Energy savings - actual (kWh/year)", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_reclamation_scheme",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of reclamation scheme - planned",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_reclamation_scheme_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of reclamation scheme - actual",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_recovery_and_recycling_scheme",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of recovery and recycling scheme - planned",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_recovery_and_recycling_scheme_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of recovery and recycling scheme - actual",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_technician_certification",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of technician certification system - planned",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="establishment_of_technician_certification_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Establishment or upgrade of technician certification system - actual",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="hfc_23_by_product_generation_rate",
            field=models.FloatField(
                blank=True,
                help_text="HFC-23 by-product generation rate (%) (planned)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="hfc_23_by_product_generation_rate_actual",
            field=models.FloatField(
                blank=True,
                help_text="HFC-23 by-product generation rate (%) (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_bans_on_equipment",
            field=models.IntegerField(
                blank=True, help_text="Number of bans on equipment - planned", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_bans_on_equipment_actual",
            field=models.IntegerField(
                blank=True, help_text="Number of bans on equipment - actual", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_bans_on_substances",
            field=models.IntegerField(
                blank=True,
                help_text="Number of bans on substances - planned",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_bans_on_substances_actual",
            field=models.IntegerField(
                blank=True, help_text="Number of bans on substances - actual", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_both_sme_non_sme_not_directly_funded",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Number of both SMEs and non-SMEs included in the project but not directly funded (planned)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_both_sme_non_sme_not_directly_funded_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Number of both SMEs and non-SMEs included in the project but not directly funded (actual)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_non_sme_directly_funded",
            field=models.IntegerField(
                blank=True,
                help_text="Number of non-SMEs directly funded (planned)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_non_sme_directly_funded_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of non-SMEs directly funded (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_smes_directly_funded",
            field=models.IntegerField(
                blank=True,
                help_text="Number of SMEs directly funded (planned)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_smes_directly_funded_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of SMEs directly funded (actual)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_toolkits_and_equipment_distributed",
            field=models.IntegerField(
                blank=True,
                help_text="Number of toolkits and equipment distributed - planned",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="number_of_toolkits_and_equipment_distributed_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of toolkits and equipment distributed - actual",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="upgrade_of_imp_exp_licensing",
            field=models.BooleanField(
                blank=True,
                help_text="Upgrade of import/export licensing system - planned",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="upgrade_of_imp_exp_licensing_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Upgrade of import/export licensing system - actual",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="upgrade_of_quota_system",
            field=models.BooleanField(
                blank=True, help_text="Upgrade of quota system - planned", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="upgrade_of_quota_system_actual",
            field=models.BooleanField(
                blank=True, help_text="Upgrade of quota system - actual", null=True
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="cost_effectiveness_co2",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US $/CO2-eq tonnes) ",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="cost_effectiveness_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US $/kg)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="draft_cost_effectiveness_co2",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US $/CO2-eq tonnes)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="draft_cost_effectiveness_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US $/kg)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="draft_number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Production sector: number of production lines assisted",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="draft_phase_out_mt",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase-out (metric tonnes) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="draft_phase_out_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase-out (ODP tonnes) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="draft_project_funding",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="MYA Total agreed funding in principle (US $) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="draft_support_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="MYA Total support costs in principle (US $) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Production sector: number of production lines assisted",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="phase_out_mt",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase-out (metric tonnes) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="phase_out_odp",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase-out (ODP tonnes) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="project_funding",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="MYA Total agreed funding in principle (US $)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="support_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="MYA Total support costs in principle (US $)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost_effectiveness",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US $/kg) (planned)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost_effectiveness_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Cost effectiveness (US $/kg) actual",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="destruction_technology",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="ee_demonstration_project",
            field=models.BooleanField(
                blank=True,
                help_text="Energy-efficiency demonstration project included (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="ee_demonstration_project_actual",
            field=models.BooleanField(
                blank=True,
                help_text="Energy-efficiency demonstration project included (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_commercial_ac",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS or equivalent standard to be developed/enhanced for commercial AC (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_commercial_ac_actual",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS or equivalent standard to be developed/enhanced for commercial AC (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_commercial_refrigeration",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS or equivalent standard to be developed/enhanced for commercial refrigeration (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_commercial_refrigeration_actual",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS or equivalent standard to be developed/enhanced for commercial refrigeration (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_domestic_refrigeration",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS to be developed/enhanced for domestic refrigeration (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_domestic_refrigeration_actual",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS to be developed/enhanced for domestic refrigeration (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_residential_ac",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS to be developed/enhanced for residential AC (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="meps_developed_residential_ac_actual",
            field=models.BooleanField(
                blank=True,
                help_text="MEPS to be developed/enhanced for residential AC (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_customs_officers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female customs officers trained - planned",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_customs_officers_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female customs officers trained - actual",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_technicians_certified",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians certified - planned",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_technicians_certified_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians certified - actual",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_technicians_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians trained - planned",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_technicians_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female technicians trained - actual",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_trainers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female trainers trained - planned",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_female_trainers_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of female trainers trained - actual",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_production_lines_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Production sector: number of production lines assisted (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_production_lines_assisted_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Production sector: number of production lines assisted (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_training_institutions_newly_assisted",
            field=models.IntegerField(
                blank=True,
                help_text="Number of training institutions newly assisted - planned",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_training_institutions_newly_assisted_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of training institutions newly assisted - actual",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="production_control_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reduction", "Reduction"),
                    ("closure", "Closure"),
                    (
                        "switch_to_production_for_feedstock_uses",
                        "Switch to production for feedstock uses",
                    ),
                    (
                        "conversion_to_non_controlled_substance",
                        "Conversion to non-controlled substance",
                    ),
                    ("other", "Other"),
                ],
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_duration",
            field=models.IntegerField(
                blank=True, help_text="Duration of project (months)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_mt",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (metric tonnes) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_controlled_substances_destroyed_mt_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of controlled substances destroyed (metric tonnes) (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_destroyed",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product destroyed (metric tonnes) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_destroyed_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product destroyed (metric tonnes) (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_emitted",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product emitted (metric tonnes) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_emitted_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product emitted (metric tonnes) (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_generated",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product generated (metric tonnes) (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quantity_hfc_23_by_product_generated_actual",
            field=models.FloatField(
                blank=True,
                help_text="Quantity of HFC-23 by-product generated (metric tonnes) (actual)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_customs_officers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of customs officers trained - planned",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_customs_officers_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of customs officers trained - actual",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_technicians_certified",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of technicians certified - planned",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_technicians_certified_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of technicians certified - actual",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_technicians_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of technicians trained - planned",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_technicians_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of technicians trained - actual",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_trainers_trained",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of trainers trained - planned",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="total_number_of_trainers_trained_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of trainers trained - actual",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="co2_mt",
            field=models.FloatField(
                blank=True, help_text="Phase-out (CO2-eq tonnes)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="odp",
            field=models.FloatField(
                blank=True, help_text="Phase-out (ODP tonnes)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="ods_replacement",
            field=models.CharField(
                blank=True,
                help_text="Replacement technologies",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="phase_out_mt",
            field=models.FloatField(
                blank=True, help_text="Phase-out (metric tonnes)", null=True
            ),
        ),
    ]
