# Generated by Django 4.2.17 on 2026-02-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0271_pcragencyreport_pcrcauseofdelay_pcrgenderphase_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectcompletionreport",
            name="submission_date",
        ),
    ]
