# Generated by Django 4.2.17 on 2026-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0272_remove_metaproject_aggregated_consumption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="number_of_both_sme_non_sme_not_directly_funded",
            field=models.IntegerField(
                blank=True,
                help_text="Number of both SMEs and non-SMEs included in the project but not directly funded (planned)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number_of_both_sme_non_sme_not_directly_funded_actual",
            field=models.IntegerField(
                blank=True,
                help_text="Number of both SMEs and non-SMEs included in the project but not directly funded (actual)",
                null=True,
            ),
        ),
    ]
