# Generated by Django 4.2.17 on 2026-03-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0273_alter_project_number_of_both_sme_non_sme_not_directly_funded_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="metaproject",
            name="draft_phase_out_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase-out (CO2-eq tonnes) (MYA) (draft)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="phase_out_co2_eq_t",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Phase-out (CO2-eq tonnes) (MYA)",
                max_digits=30,
                null=True,
            ),
        ),
    ]
