# Generated by Django 4.2.17 on 2026-03-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0274_alter_metaproject_draft_phase_out_co2_eq_t_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualprojectreport",
            name="consumption_phased_out_mt",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Consumption Phased Out in Metric Tonnes",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="consumption_phased_out_mt_proposal_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Snapshot of version 3 consumption phase out metric tonnes",
                null=True,
                verbose_name="Consumption MT Proposal (denormalized)",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="production_phased_out_mt",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Production Phased Out in Metric Tonnes",
            ),
        ),
        migrations.AddField(
            model_name="annualprojectreport",
            name="production_phased_out_mt_proposal_denorm",
            field=models.FloatField(
                blank=True,
                help_text="Snapshot of version 3 production phase out metric tonnes",
                null=True,
                verbose_name="Production MT Proposal (denormalized)",
            ),
        ),
    ]
