# Generated by Django 4.2.17 on 2026-03-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0275_annualprojectreport_consumption_phased_out_mt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaproject",
            name="draft_project_duration",
            field=models.IntegerField(
                blank=True, help_text="Project duration (months) (draft)", null=True
            ),
        ),
        migrations.AddField(
            model_name="metaproject",
            name="project_duration",
            field=models.IntegerField(
                blank=True, help_text="Project duration (months)", null=True
            ),
        ),
    ]
