# Generated by Django 4.2.17 on 2026-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0276_metaproject_draft_project_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metaproject",
            name="draft_number_of_both_sme_non_sme_not_directly_funded",
            field=models.IntegerField(
                blank=True,
                help_text="Number of both SMEs and non-SMEs included in the project but not directly funded (draft)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="number_of_both_sme_non_sme_not_directly_funded",
            field=models.IntegerField(
                blank=True,
                help_text="Number of both SMEs and non-SMEs included in the project but not directly funded",
                null=True,
            ),
        ),
    ]
