# Generated by Django 4.2.17 on 2026-03-11 09:28

from django.db import migrations, models


def update_obsolete_file_types(apps, schema_editor):
    ProjectFile = apps.get_model("core", "ProjectFile")
    obsolete_types = ["main_submission", "final_proposal"]
    ProjectFile.objects.filter(type__in=obsolete_types).update(type="other")


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0277_alter_metaproject_draft_number_of_both_sme_non_sme_not_directly_funded_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfile",
            name="type",
            field=models.CharField(
                choices=[
                    ("project_proposal", "Project proposal"),
                    (
                        "endorsement_letter",
                        "Endorsement/transmittal letter from government",
                    ),
                    ("verification_report", "Verification report"),
                    ("project_review_comments", "Project review comments"),
                    ("transferred_project_proposal", "Transferred project proposal"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.RunPython(
            update_obsolete_file_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
