# Generated by Django 4.2.17 on 2026-03-11 12:35

from django.db import migrations, models


def update_consumption_level_status(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    Project.objects.filter(consumption_level_status="Not applicable").update(
        consumption_level_status="N/A"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0278_alter_projectfile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="consumption_level_status",
            field=models.CharField(
                blank=True,
                choices=[("LVC", "LVC"), ("Non-LVC", "Non-LVC"), ("N/A", "N/A")],
                help_text="The field to be derived but with the option change the value for the KIP (As an example).",
                max_length=256,
                null=True,
            ),
        ),
        migrations.RunPython(
            update_consumption_level_status, reverse_code=migrations.RunPython.noop
        ),
    ]
