# Generated by Django 4.2.17 on 2026-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0279_alter_project_consumption_level_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternativeTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
