# Generated by Django 4.2.17 on 2026-03-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0280_alternativetechnology"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alternativetechnology",
            options={"verbose_name_plural": "Alternative technologies"},
        ),
    ]
