# Generated by Django 4.2.17 on 2026-03-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0281_alter_alternativetechnology_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectodsodp",
            old_name="ods_replacement",
            new_name="ods_replacement_text",
        ),
        migrations.AlterField(
            model_name="projectodsodp",
            name="ods_replacement_text",
            field=models.CharField(
                blank=True,
                help_text="Replacement technologies text for custom values",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectodsodp",
            name="ods_replacement",
            field=models.ForeignKey(
                blank=True,
                help_text="Replacement technologies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_ods_replacements",
                to="core.alternativetechnology",
            ),
        ),
    ]
