# Generated by Django 4.2.17 on 2026-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0282_projectodsodp_ods_replacement_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="api_changed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="pseudo_content_preview",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="decision",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
