# Generated by Django 4.2.17 on 2026-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0283_decision_api_changed_decision_pseudo_content_preview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaproject",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="\n            True if the MetaProject is created for a project that is not yet approved.\n            When the project is approved, the MetaProject will be converted to a final\n            MetaProject and the is_draft field will be set to False.\n        ",
            ),
        ),
    ]
