# Generated by Django 4.2.17 on 2026-03-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0284_metaproject_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="adjustment",
            field=models.BooleanField(
                default=False,
                help_text="Marked as true on a post excom update if the update resulted in a fund adjustment.",
            ),
        ),
    ]
