# Generated by Django 4.2.17 on 2026-03-31 10:48

from django.db import migrations, models
import django.db.models.deletion


def clear_funding_window(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    Project.objects.all().update(funding_window=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0285_project_adjustment_project_interest"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Funding Window Description", null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=15,
                        help_text="Funding Window Amount (US$)",
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, help_text="Remarks", null=True),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        help_text="Decision Number",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.decision",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        help_text="Meeting number",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.meeting",
                    ),
                ),
            ],
        ),
        migrations.RunPython(clear_funding_window, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="project",
            name="funding_window",
            field=models.ForeignKey(
                blank=True,
                help_text="Funding window",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.fundingwindow",
            ),
        ),
    ]
