# Generated by Django 4.2.17 on 2026-04-02 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0286_fundingwindow_alter_project_funding_window"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="funding_window",
            field=models.ForeignKey(
                blank=True,
                help_text="Funding window",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="core.fundingwindow",
            ),
        ),
    ]
