# Generated by Django 4.2.17 on 2026-04-27 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0287_alter_project_funding_window"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectEnterprise",
        ),
        migrations.DeleteModel(
            name="ProjectEnterpriseOdsOdp",
        ),
        migrations.DeleteModel(
            name="Enterprise",
        ),
        migrations.CreateModel(
            name="EnterpriseStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_code",
                    models.CharField(
                        blank=True,
                        help_text="Legacy code from the previous system, if any",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="System-generated set of letters and numbers identifying the enterprise",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the enterprise", max_length=256
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True,
                        help_text="Name of the city where the enterprise is located",
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Name of the city where the enterprise is located",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        help_text="Stage of the HPMP relating to the enterprise",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="Name of applications",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "planned_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected date of completion of the project",
                        null=True,
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual date of completion of the project",
                        null=True,
                    ),
                ),
                (
                    "project_duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of project implementation from approval (in months)",
                        null=True,
                    ),
                ),
                (
                    "local_ownership",
                    models.CharField(
                        blank=True,
                        help_text="Percentage of Article 5 ownership of the enterprise",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "export_to_non_a5",
                    models.CharField(
                        blank=True,
                        help_text="Percentage of produce exported to non-A5 countries",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "revision_number",
                    models.IntegerField(
                        blank=True, help_text="Revision number", null=True
                    ),
                ),
                (
                    "date_of_approval",
                    models.DateField(
                        blank=True,
                        help_text="Month and year of meeting when project was approved",
                        null=True,
                    ),
                ),
                (
                    "chemical_phased_out",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Total quantity of chemical phased out (mt)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "impact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Total ODP tonnes phased out",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "funds_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Funds approved/allocated for the enterprise (US $)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "capital_cost_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Capital cost approved/allocated for the enterprise (US $)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "operating_cost_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Operating cost approved/allocated for enterprise (US $)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "cost_effectiveness_approved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Cost effectiveness approved (US $/kg)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "funds_disbursed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Funds disbursed to the enterprise (US $)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "capital_cost_disbursed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Capital cost disbursed to the enterprise (US $)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "operating_cost_disbursed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Operating cost disbursed to the enterprise (US $)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "cost_effectiveness_actual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Actual cost effectiveness (US $)/kg",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "co_financing_planned",
                    models.CharField(
                        blank=True,
                        help_text="Co-financing by the enterprise (planned) (US $)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "co_financing_actual",
                    models.CharField(
                        blank=True,
                        help_text="Co-financing by the enterprise (actual) (US $)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "funds_transferred",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Funds transferred from one agency to another (US $)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "agency_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Text on remarks relating to the project by agency if any",
                        null=True,
                    ),
                ),
                (
                    "secretariat_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Text on remarks relating to the project by secretariat if any",
                        null=True,
                    ),
                ),
                (
                    "excom_provision",
                    models.TextField(
                        blank=True,
                        help_text="Text on ExCom provision relating to the project if any",
                        null=True,
                    ),
                ),
                (
                    "date_of_report",
                    models.DateField(
                        blank=True,
                        help_text="Date of recording of disbursement to the enterprise",
                        null=True,
                    ),
                ),
                (
                    "date_of_revision",
                    models.DateField(
                        blank=True,
                        help_text="Date when records related to the enterprise are introduced",
                        null=True,
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        help_text="Name of agency",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enterprises",
                        to="core.agency",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Name of the country",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enterprises",
                        to="core.country",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        help_text="Meeting where the project was approved",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enterprises",
                        to="core.meeting",
                    ),
                ),
                (
                    "project_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of project (e.g., demonstration, investment, technical assistance)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enterprises",
                        to="core.projecttype",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sector related to the enterprise (e.g., aerosol, fire-fighting, foam, production,\n                    refrigeration, solvent)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enterprises",
                        to="core.projectsector",
                    ),
                ),
                (
                    "subsector",
                    models.ForeignKey(
                        blank=True,
                        help_text="Name of the sub-sector within each sector",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enterprises",
                        to="core.projectsubsector",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        help_text="Progress status (e.g., new, on-going, closed, transferred)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enterprises",
                        to="core.enterprisestatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnterpriseOdsOdp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consumption",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount of the controlled substance to be phased out (mt)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "selected_alternative",
                    models.CharField(
                        blank=True,
                        help_text="\n        Name of alternative technology or chemical\n        ",
                        max_length=128,
                    ),
                ),
                (
                    "chemical_phased_in_mt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="\n            Amount of alternative being used in place of controlled chemical\n        ",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        help_text="Enterprise linked to this ODS/ODP entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ods_odp",
                        to="core.enterprise",
                    ),
                ),
                (
                    "ods_blend",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projectenterprise_ods",
                        to="core.blend",
                    ),
                ),
                (
                    "ods_substance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Substance - baseline technology",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projectenterprise_ods",
                        to="core.substance",
                    ),
                ),
            ],
        ),
    ]
