# Generated by Django 4.2.17 on 2026-04-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0288_enterpriseodsodp_enterprisestatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                help_text="Name of agency",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enterprises",
                to="core.agency",
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseodsodp",
            name="ods_blend",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enterprise_ods",
                to="core.blend",
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseodsodp",
            name="ods_substance",
            field=models.ForeignKey(
                blank=True,
                help_text="Substance - baseline technology",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enterprise_ods",
                to="core.substance",
            ),
        ),
    ]
