# Generated by Django 4.2.17 on 2026-04-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0289_alter_enterprise_agency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterpriseodsodp",
            name="ods_display_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
