# Generated by Django 4.2.17 on 2026-05-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0290_enterpriseodsodp_ods_display_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="capital_cost_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Capital cost approved/allocated for the enterprise (US $)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="capital_cost_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Capital cost disbursed to the enterprise (US $)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="chemical_phased_out",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Total quantity of chemical phased out (mt)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="cost_effectiveness_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Actual cost effectiveness (US $)/kg",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="cost_effectiveness_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Cost effectiveness approved (US $/kg)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="funds_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Funds approved/allocated for the enterprise (US $)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="funds_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Funds disbursed to the enterprise (US $)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="impact",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Total ODP tonnes phased out",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="operating_cost_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Operating cost approved/allocated for enterprise (US $)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="operating_cost_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Operating cost disbursed to the enterprise (US $)",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseodsodp",
            name="chemical_phased_in_mt",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="\n            Amount of alternative being used in place of controlled chemical\n        ",
                max_digits=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseodsodp",
            name="consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Amount of the controlled substance to be phased out (mt)",
                max_digits=25,
                null=True,
            ),
        ),
    ]
