# Generated by Django 4.2.17 on 2026-05-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0291_alter_enterprise_capital_cost_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="funds_transferred",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Funds transferred from one agency to another (US $)",
                max_digits=25,
                null=True,
            ),
        ),
    ]
