# Generated by Django 4.2.17 on 2026-05-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0292_alter_enterprise_funds_transferred"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency_inputter", "Agency inputter"),
                    ("agency_submitter", "Agency submitter"),
                    ("country_user", "Country user"),
                    ("country_submitter", "Country submitter"),
                    ("secretariat", "Secretariat"),
                    ("viewer", "Viewer"),
                    ("stakeholder", "Stakeholder"),
                    ("treasurer", "Treasurer"),
                    ("cp_viewer", "Country Programme Viewer"),
                    ("secretariat_viewer", "Secretariat Viewer"),
                    (
                        "secretariat_recommender_edit_access",
                        "Secretariat Recommender Edit Access",
                    ),
                    (
                        "secretariat_approver_edit_access_user",
                        "Secretariat Approver Edit Access",
                    ),
                    (
                        "secretariat_production_recommender_edit_access",
                        "Secretariat Production Recommender Edit Access",
                    ),
                    (
                        "secretariat_production_approver_edit_access",
                        "Secretariat Production Approver Edit Access",
                    ),
                    ("bp_viewer", "Business Plan Viewer"),
                    ("bp_editor", "Business Plan Editor"),
                ],
                max_length=50,
            ),
        ),
    ]
