# Generated by Django 4.2.17 on 2026-05-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0294_rename_implementation_delays_denorm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualprojectreport",
            name="implementation_delays_status_report_decisions",
            field=models.CharField(
                blank=True,
                help_text="User-entered implementation delays or status report decisions",
                max_length=500,
                null=True,
                verbose_name="Implementation Delays/Status Report Decisions",
            ),
        ),
    ]
