# Generated by Django 4.2.17 on 2026-05-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0295_alter_annualprojectreport_implementation_delays_status_report_decisions",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="annualprojectreport",
            name="main_region",
            field=models.ForeignKey(
                blank=True,
                help_text="FK to the main (top-level) Region Country for this project, used in APR reporting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.country",
                verbose_name="Main Region (FK)",
            ),
        ),
        migrations.AlterField(
            model_name="annualprojectreport",
            name="region_name_denorm",
            field=models.CharField(
                blank=True,
                help_text="Snapshot of project.country.parent.name at time of reporting (subregion; kept for reference)",
                max_length=255,
                null=True,
                verbose_name="Region Name (denormalized)",
            ),
        ),
    ]
