# Generated by Django 4.2.17 on 2026-06-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0300_alter_country_abbr_for_apr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="substance_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CFC", "CFC"),
                    ("CFC, CTC", "CFC, CTC"),
                    ("CFC, CTC, Methyl Bromide", "CFC, CTC, Methyl Bromide"),
                    ("CFC, CTC, TCA", "CFC, CTC, TCA"),
                    ("CFC, Halon", "CFC, Halon"),
                    ("CFC, Halon, CTC", "CFC, Halon, CTC"),
                    ("CFC, Halon, TCA", "CFC, Halon, TCA"),
                    ("CFC, Methyl Bromide", "CFC, Methyl Bromide"),
                    ("CFC, TCA", "CFC, TCA"),
                    ("CTC", "CTC"),
                    ("CTC, TCA", "CTC, TCA"),
                    ("Halon", "Halon"),
                    ("HFC", "HFC"),
                    ("Methyl Bromide", "Methyl Bromide"),
                    ("HCFC", "HCFC"),
                    ("N/A", "N/A"),
                    ("ODS", "ODS"),
                    ("TCA", "TCA"),
                    ("BOTH", "Both"),
                    ("HFC_Plus", "HFC_Plus"),
                ],
                help_text="\n            Old field from the initial imported data/implementation of projects.\n            TBD if the information can be transferred to the new structure.\n            Still in use in the export.\n        ",
                max_length=256,
                null=True,
            ),
        ),
    ]
