# Generated by Django 4.2.17 on 2026-06-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0300_alter_country_abbr_for_apr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualprojectreport',
            name='gender_policy',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gender Policy for All Projects Approved from 85th Mtg'),
        ),
    ]
