# Generated by Django 4.2.17 on 2026-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0302_alter_annualprojectreport_gender_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_baseline_co2_eq_t",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_baseline_odp",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_cost_effectiveness_co2",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_cost_effectiveness_kg",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_end_date",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_number_of_both_sme_non_sme_not_directly_funded",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_number_of_non_sme_directly_funded",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_number_of_production_lines_assisted",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_number_of_smes_directly_funded",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_phase_out_co2_eq_t",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_phase_out_mt",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_phase_out_odp",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_project_cost",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_project_duration",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_project_funding",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_start_date",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_starting_point_co2_eq_t",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_starting_point_odp",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_support_cost",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_target_co2_eq_t",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_target_odp",
        ),
        migrations.RemoveField(
            model_name="metaproject",
            name="draft_target_reduction",
        ),
        migrations.AddField(
            model_name="metaproject",
            name="extended_date_of_completion",
            field=models.DateTimeField(
                blank=True, help_text="Extended date of completion", null=True
            ),
        ),
    ]
