# Generated by Django 4.2.17 on 2026-06-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0303_remove_metaproject_draft_baseline_co2_eq_t_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decision",
            options={
                "ordering": ("meeting__number", "number"),
                "verbose_name_plural": "Decisions",
            },
        ),
        migrations.AlterModelOptions(
            name="meeting",
            options={"ordering": ("number",), "verbose_name_plural": "Meetings"},
        ),
    ]
