# Generated by Django 4.2.17 on 2026-06-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0305_projectspecificfields_obsolete"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPCRRequiredExclusionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clusters",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="core.projectcluster"
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="core.projectsector"
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="core.projecttype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project PCR required exclusion rule",
                "verbose_name_plural": "Project PCR required exclusion rules",
                "ordering": ("name",),
            },
        ),
    ]
