# Generated by Django 4.2.17 on 2026-06-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0306_seed_project_pcr_exclusion_rules"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DelayCategory",
            new_name="OLD_DelayCategory",
        ),
        migrations.RenameModel(
            old_name="LearnedLessonCategory",
            new_name="OLD_LearnedLessonCategory",
        ),
        migrations.RenameModel(
            old_name="PCRActivity",
            new_name="OLD_PCRActivity",
        ),
        migrations.RenameModel(
            old_name="PCRDelayExplanation",
            new_name="OLD_PCRDelayExplanation",
        ),
        migrations.RenameModel(
            old_name="PCRLearnedLessons",
            new_name="OLD_PCRLearnedLessons",
        ),
        migrations.RenameModel(
            old_name="PCRSector",
            new_name="OLD_PCRSector",
        ),
        migrations.AlterModelOptions(
            name="old_pcractivity",
            options={"verbose_name_plural": "OLD PCR activities"},
        ),
    ]
