# Generated by Django 4.2.17 on 2026-07-02 13:20

import core.models.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0307_rename_delaycategory_old_delaycategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "latest_pcr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="previous_versions",
                        to="core.pcr",
                    ),
                ),
                (
                    "meta_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.metaproject",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR",
            },
        ),
        migrations.CreateModel(
            name="PCRAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agency"
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agencies",
                        to="core.pcr",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR agencies",
                "unique_together": {("pcr", "agency")},
            },
        ),
        migrations.CreateModel(
            name="PCRDelayCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                ("obsolete", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "PCR delay categories",
            },
        ),
        migrations.CreateModel(
            name="PCRGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("sort_order", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "PCR goals",
            },
        ),
        migrations.CreateModel(
            name="PCRLearnedLessonCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                ("obsolete", models.BooleanField()),
            ],
            options={
                "verbose_name_plural": "PCR learned lesson categories",
            },
        ),
        migrations.CreateModel(
            name="PCRProjectComponentOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                ("obsolete", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "PCR project component options",
            },
        ),
        migrations.CreateModel(
            name="PCRSupportingEvidenceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("sort_order", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "PCR supporting evidence sections",
            },
        ),
        migrations.CreateModel(
            name="PCRSustainableDevelopmentGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "PCR sustainable development goals",
            },
        ),
        migrations.AlterModelOptions(
            name="old_delaycategory",
            options={"verbose_name_plural": "OLD Delay categories"},
        ),
        migrations.AlterModelOptions(
            name="old_learnedlessoncategory",
            options={"verbose_name_plural": "OLD Learned lesson categories"},
        ),
        migrations.AlterModelOptions(
            name="old_pcrdelayexplanation",
            options={"verbose_name_plural": "OLD PCR Delay categories"},
        ),
        migrations.AlterModelOptions(
            name="old_pcrlearnedlessons",
            options={"verbose_name_plural": "OLD PCR Learned lessons"},
        ),
        migrations.AlterModelOptions(
            name="old_pcrsector",
            options={"verbose_name_plural": "OLD PCR Sector"},
        ),
        migrations.AddField(
            model_name="old_pcrdelayexplanation",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="old_pcrdelayexplanation",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PCRSustainableDevelopmentGoalDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pcrgoal"
                    ),
                ),
                (
                    "sgr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pcrsustainabledevelopmentgoal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pcrsustainabledevelopmentgoal",
            name="goals",
            field=models.ManyToManyField(
                related_name="sustainable_development_goals",
                through="core.PCRSustainableDevelopmentGoalDescription",
                to="core.pcrgoal",
            ),
        ),
        migrations.AddField(
            model_name="pcrsustainabledevelopmentgoal",
            name="pcr_agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sustainable_development_goals",
                to="core.pcragency",
            ),
        ),
        migrations.CreateModel(
            name="PCRSupportingEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=core.models.utils.get_protected_storage,
                        upload_to="pcr_files/",
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                ("link", models.URLField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "pcr_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supporting_evidences",
                        to="core.pcragency",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supporting_evidences",
                        to="core.pcrsupportingevidencesection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR supporting evidences",
            },
        ),
        migrations.CreateModel(
            name="PCRProjectComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "pcr_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="core.pcragency",
                    ),
                ),
                (
                    "project_component_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pcrprojectcomponentoption",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR project components",
            },
        ),
        migrations.CreateModel(
            name="PCRProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_figures_status",
                    models.CharField(
                        choices=[("Provisional", "Provisional"), ("Final", "Final")],
                        help_text="Indicate whether the financial figures are provisional or final",
                        max_length=32,
                    ),
                ),
                (
                    "financial_figures_status_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanations if needed ( sub-section of row above)",
                        null=True,
                    ),
                ),
                (
                    "addresses",
                    models.TextField(
                        blank=True,
                        help_text="Address(es) of enterprise(s) and project site(s), if applicable.",
                        null=True,
                    ),
                ),
                (
                    "project_goal_achieved",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "N/A")],
                        help_text="Indicate whether the financial figures are provisional or final",
                        max_length=16,
                    ),
                ),
                (
                    "project_goal_achieved_explanation",
                    models.TextField(
                        blank=True,
                        help_text="If project goal achieved is No, this field provides a brief explanation",
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("Highly satisfactory", "Highly satisfactory"),
                            ("Satisfactory as planned", "Satisfactory as planned"),
                            (
                                "Satisfactory but not as planned",
                                "Satisfactory but not as planned",
                            ),
                            ("Unsatisfactory", "Unsatisfactory"),
                            ("Other, please specify", "Other, please specify"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "rating_explaination",
                    models.TextField(
                        blank=True,
                        help_text="Should be filled if rating has the value 'Other, please specify' ",
                        null=True,
                    ),
                ),
                (
                    "completed_by",
                    models.CharField(
                        choices=[
                            ("Lead Agency", "Lead Agency"),
                            ("Cooperating Agency", "Cooperating Agency"),
                            (
                                "National coordinating agency/NOU",
                                "National coordinating agency/NOU",
                            ),
                            ("Local executing agency", "Local executing agency"),
                            ("Other", "Other"),
                        ],
                        help_text="Completion report done by...",
                        max_length=64,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="core.pcr",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pcr_projects",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR projects",
            },
        ),
        migrations.CreateModel(
            name="PCRLearnedLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the causes of delay selected ",
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pcrlearnedlessoncategory",
                    ),
                ),
                (
                    "pcr_project_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learned_lessons",
                        to="core.pcrprojectcomponent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR learned lessons",
            },
        ),
        migrations.CreateModel(
            name="PCRGenderMainstreaming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_preparation",
                    models.CharField(
                        choices=[
                            ("Project preparation", "Project preparation"),
                            ("Planning/Formulation", "Planning/Formulation"),
                            ("Implementation", "Implementation"),
                            ("Monitoring and Reporting", "Monitoring and Reporting"),
                        ],
                        max_length=32,
                    ),
                ),
                ("prefilled", models.BooleanField()),
                ("qualitative_description", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "pcr_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gender_mainstreamings",
                        to="core.pcragency",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR gender mainstreamings",
            },
        ),
        migrations.CreateModel(
            name="PCRDelayCause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Planned output(s)", null=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "delay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pcrdelaycategory",
                    ),
                ),
                (
                    "pcr_project_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delay_causes",
                        to="core.pcrprojectcomponent",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR delay causes",
            },
        ),
        migrations.CreateModel(
            name="PCRAdditionalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[
                            ("Cooperating agency", "Cooperating agency"),
                            ("Government/NOU", "Government/NOU"),
                            ("Enterprises", "Enterprises"),
                            ("Consultants", "Consultants"),
                            (
                                "Project management officers in the Multilateral Fund Secretariat",
                                "Project management officers in the Multilateral Fund Secretariat",
                            ),
                            ("Other, please specify", "Other, please specify"),
                        ],
                        help_text="Indicate whether the financial figures are provisional or final",
                        max_length=64,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "pcr_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="additional_comments",
                        to="core.pcrproject",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR additional comments",
            },
        ),
        migrations.CreateModel(
            name="PCRActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_activity",
                    models.TextField(
                        blank=True, help_text="Type of activity", null=True
                    ),
                ),
                (
                    "planned_output",
                    models.TextField(
                        blank=True, help_text="Planned output(s)", null=True
                    ),
                ),
                (
                    "actual_activity_output",
                    models.TextField(
                        blank=True, help_text="Actual activity output(s)", null=True
                    ),
                ),
                (
                    "additional_remarks",
                    models.TextField(
                        blank=True, help_text="Additional remarks", null=True
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="core.pcr",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR activities",
            },
        ),
    ]
