# Generated by Django 4.2.17 on 2026-06-30 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0307_rename_delaycategory_old_delaycategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelayCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                ("obsolete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("sort_order", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LessonsLearnedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                ("obsolete", models.BooleanField()),
            ],
            options={
                "verbose_name_plural": "Learned lesson categories",
            },
        ),
        migrations.CreateModel(
            name="PCR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.metaproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PCRAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.agency"
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agencies",
                        to="core.pcr",
                    ),
                ),
            ],
            options={
                "unique_together": {("pcr", "agency")},
            },
        ),
        migrations.CreateModel(
            name="ProjectComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("sort_order", models.FloatField(blank=True, null=True)),
                ("obsolete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SustainableDevelopmentGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SustainableDevelopmentGoalDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.goal"
                    ),
                ),
                (
                    "sgr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.sustainabledevelopmentgoal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sustainabledevelopmentgoal",
            name="goals",
            field=models.ManyToManyField(
                through="core.SustainableDevelopmentGoalDescription", to="core.goal"
            ),
        ),
        migrations.AddField(
            model_name="sustainabledevelopmentgoal",
            name="pcr_agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sustainable_development_goals",
                to="core.pcragency",
            ),
        ),
        migrations.CreateModel(
            name="PCRProjectComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pcr_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="core.pcragency",
                    ),
                ),
                (
                    "project_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.projectcomponent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PCRProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_figures_status",
                    models.CharField(
                        choices=[("Provisional", "Provisional"), ("Final", "Final")],
                        help_text="Indicate whether the financial figures are provisional or final",
                        max_length=32,
                    ),
                ),
                (
                    "financial_figures_status_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanations if needed ( sub-section of row above)",
                        null=True,
                    ),
                ),
                (
                    "addresses",
                    models.TextField(
                        blank=True,
                        help_text="Address(es) of enterprise(s) and project site(s), if applicable.",
                        null=True,
                    ),
                ),
                (
                    "project_goal_achieved",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "N/A")],
                        help_text="Indicate whether the financial figures are provisional or final",
                        max_length=16,
                    ),
                ),
                (
                    "project_goal_achieved_explanation",
                    models.TextField(
                        blank=True,
                        help_text="If project goal achieved is No, this field provides a brief explanation",
                        null=True,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("Highly satisfactory", "Highly satisfactory"),
                            ("Satisfactory as planned", "Satisfactory as planned"),
                            (
                                "Satisfactory but not as planned",
                                "Satisfactory but not as planned",
                            ),
                            ("Unsatisfactory", "Unsatisfactory"),
                            ("Other, please specify", "Other, please specify"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "rating_explaination",
                    models.TextField(
                        blank=True,
                        help_text="Should be filled if rating has the value 'Other, please specify' ",
                        null=True,
                    ),
                ),
                (
                    "completed_by",
                    models.CharField(
                        choices=[
                            ("Lead Agency", "Lead Agency"),
                            ("Cooperating Agency", "Cooperating Agency"),
                            (
                                "National coordinating agency/NOU",
                                "National coordinating agency/NOU",
                            ),
                            ("Local executing agency", "Local executing agency"),
                            ("Other", "Other"),
                        ],
                        help_text="Completion report done by...",
                        max_length=64,
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pcr"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PCRAdditionalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[
                            ("Cooperating agency", "Cooperating agency"),
                            ("Government/NOU", "Government/NOU"),
                            ("Enterprises", "Enterprises"),
                            ("Consultants", "Consultants"),
                            (
                                "Project management officers in the Multilateral Fund Secretariat",
                                "Project management officers in the Multilateral Fund Secretariat",
                            ),
                            ("Other, please specify", "Other, please specify"),
                        ],
                        help_text="Indicate whether the financial figures are provisional or final",
                        max_length=64,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "pcr_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pcrproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PCRActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_activity",
                    models.TextField(
                        blank=True, help_text="Type of activity", null=True
                    ),
                ),
                (
                    "planned_output",
                    models.TextField(
                        blank=True, help_text="Planned output(s)", null=True
                    ),
                ),
                (
                    "actual_activity_output",
                    models.TextField(
                        blank=True, help_text="Actual activity output(s)", null=True
                    ),
                ),
                (
                    "additional_remarks",
                    models.TextField(
                        blank=True, help_text="Additional remarks", null=True
                    ),
                ),
                (
                    "pcr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pcr"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonsLearned",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the causes of delay selected ",
                        null=True,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.lessonslearnedcategory",
                    ),
                ),
                (
                    "pcr_project_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pcrprojectcomponent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenderMainstreaming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_preparation",
                    models.CharField(
                        choices=[
                            ("Project preparation", "Project preparation"),
                            ("Planning/Formulation", "Planning/Formulation"),
                            ("Implementation", "Implementation"),
                            ("Monitoring and Reporting", "Monitoring and Reporting"),
                        ],
                        max_length=32,
                    ),
                ),
                ("prefilled", models.BooleanField()),
                ("qualitative_description", models.TextField()),
                (
                    "pcr_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gender_mainstreamings",
                        to="core.pcragency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DelayCause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Planned output(s)", null=True
                    ),
                ),
                (
                    "delay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.delaycategory",
                    ),
                ),
                (
                    "pcr_project_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.pcrprojectcomponent",
                    ),
                ),
            ],
        ),
    ]
