# Generated by Django 4.2.17 on 2026-07-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0308_pcr_pcragency_pcrdelaycategory_pcrgoal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcr",
            name="submission_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pcrproject",
            name="pcr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pcr_projects",
                to="core.pcr",
            ),
        ),
        migrations.AlterField(
            model_name="pcrproject",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pcr_project",
                to="core.project",
            ),
        ),
    ]
