# Generated by Django 4.2.17 on 2026-07-31 12:59

from datetime import timedelta
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0309_pcr_submission_date_alter_pcrproject_pcr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True,
            ),
        ),
    ]
