# Generated by Codex on 2026-07-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0309_pcr_submission_date_alter_pcrproject_pcr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcrproject",
            name="funds_disbursed",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="Funds disbursed entered in the PCR summary of key data.",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcrproject",
            name="planned_date_of_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PCRProjectAlternativeTechnology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pcr_project",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="alternative_technologies",
                        to="core.pcrproject",
                    ),
                ),
                (
                    "substance_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.PROTECT,
                        related_name="+",
                        to="core.substance",
                    ),
                ),
                (
                    "substance_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.PROTECT,
                        related_name="+",
                        to="core.substance",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR project alternative technologies",
            },
        ),
        migrations.CreateModel(
            name="PCRProjectEnterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("address", models.TextField(blank=True)),
                (
                    "pcr_project",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="enterprises",
                        to="core.pcrproject",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR project enterprises",
            },
        ),
        migrations.CreateModel(
            name="PCRProjectEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "disposal_type",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("disposal_date", models.DateField(blank=True, null=True)),
                (
                    "pcr_project",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="equipments",
                        to="core.pcrproject",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PCR project equipment",
            },
        ),
    ]
