# Generated by Django 4.2.17 on 2026-08-06 12:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0310_project_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalallocation",
            name="wmo",
            field=models.DecimalField(
                decimal_places=15, default=Decimal("0"), max_digits=30
            ),
        ),
    ]
