# Generated by Django 4.2.17 on 2026-07-20 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0310_pcrproject_summary_of_key_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcr",
            name="decisions",
            field=models.ManyToManyField(
                help_text="Executive Commitee meeting",
                related_name="pcrs",
                to="core.decision",
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="phase_out_co2_eq_t_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="HFCs PHASED-DOWN (CO2 eq-tonnes) (Actual)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="phase_out_co2_eq_t_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="HFCs PHASED-DOWN (CO2 eq-tonnes) (Approved)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="phase_out_ods_actual",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="ODP phase out (Actual)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="phase_out_ods_approved",
            field=models.DecimalField(
                blank=True,
                decimal_places=15,
                help_text="ODP phase-out (Approved)",
                max_digits=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="project_date_approved",
            field=models.DateField(
                blank=True, help_text="Date of approval of the project", null=True
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="project_date_completion",
            field=models.DateField(
                blank=True, help_text="Date of completion of the project", null=True
            ),
        ),
        migrations.AddField(
            model_name="pcrprojectalternativetechnology",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pcrprojectalternativetechnology",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pcrprojectenterprise",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pcrprojectenterprise",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pcrprojectequipment",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pcrprojectequipment",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
