# Generated by Django 4.2.17 on 2026-07-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0311_pcr_decisions_pcr_phase_out_co2_eq_t_actual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcractivity",
            name="activity_title",
            field=models.TextField(blank=True, help_text="Type of activity", null=True),
        ),
        migrations.AddField(
            model_name="pcractivity",
            name="agency",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="core.agency"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pcractivity",
            name="type_of_sector",
            field=models.TextField(blank=True, help_text="Type of sector", null=True),
        ),
    ]
