# Generated by Django 4.2.17 on 2026-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0312_pcractivity_activity_title_pcractivity_agency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pcrproject",
            name="addresses",
        ),
        migrations.RemoveField(
            model_name="pcrproject",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="pcrproject",
            name="financial_figures_status",
        ),
        migrations.RemoveField(
            model_name="pcrproject",
            name="financial_figures_status_explanation",
        ),
        migrations.RemoveField(
            model_name="pcrproject",
            name="project_goal_achieved",
        ),
        migrations.RemoveField(
            model_name="pcrproject",
            name="project_goal_achieved_explanation",
        ),
        migrations.RemoveField(
            model_name="pcrproject",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="pcrproject",
            name="rating_explaination",
        ),
        migrations.AddField(
            model_name="pcr",
            name="addresses",
            field=models.TextField(
                blank=True,
                help_text="Address(es) of enterprise(s) and project site(s), if applicable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="completed_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lead Agency", "Lead Agency"),
                    ("Cooperating Agency", "Cooperating Agency"),
                    (
                        "National coordinating agency/NOU",
                        "National coordinating agency/NOU",
                    ),
                    ("Local executing agency", "Local executing agency"),
                    ("Other", "Other"),
                ],
                help_text="Completion report done by...",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="financial_figures_status",
            field=models.CharField(
                blank=True,
                choices=[("Provisional", "Provisional"), ("Final", "Final")],
                help_text="Indicate whether the financial figures are provisional or final",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="financial_figures_status_explanation",
            field=models.TextField(
                blank=True,
                help_text="Explanations if needed ( sub-section of row above)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="project_goal_achieved",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "N/A")],
                help_text="Indicate whether the financial figures are provisional or final",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="project_goal_achieved_explanation",
            field=models.TextField(
                blank=True,
                help_text="If project goal achieved is No, this field provides a brief explanation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Highly satisfactory", "Highly satisfactory"),
                    ("Satisfactory as planned", "Satisfactory as planned"),
                    (
                        "Satisfactory but not as planned",
                        "Satisfactory but not as planned",
                    ),
                    ("Unsatisfactory", "Unsatisfactory"),
                    ("Other, please specify", "Other, please specify"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="rating_explanation",
            field=models.TextField(
                blank=True,
                help_text="Please explain your rating ( sub-section of row above) ",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pcr",
            name="rating_explanation_other",
            field=models.TextField(
                blank=True,
                help_text="Should be filled if rating has the value 'Other, please specify' ",
                null=True,
            ),
        ),
    ]
