# Generated by Django 4.2.17 on 2026-07-29 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0315_remove_pcradditionalcomment_pcr_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcr",
            name="version_created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User who created this PCR version",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_pcrs_version",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agency_inputter", "Agency inputter"),
                    ("agency_submitter", "Agency submitter"),
                    ("country_user", "Country user"),
                    ("country_submitter", "Country submitter"),
                    ("secretariat", "Secretariat"),
                    ("viewer", "Viewer"),
                    ("stakeholder", "Stakeholder"),
                    ("treasurer", "Treasurer"),
                    ("cp_viewer", "Country Programme Viewer"),
                    ("secretariat_viewer", "Secretariat Viewer"),
                    (
                        "secretariat_recommender_edit_access",
                        "Secretariat Recommender Edit Access",
                    ),
                    (
                        "secretariat_approver_edit_access_user",
                        "Secretariat Approver Edit Access",
                    ),
                    (
                        "secretariat_production_recommender_edit_access",
                        "Secretariat Production Recommender Edit Access",
                    ),
                    (
                        "secretariat_production_approver_edit_access",
                        "Secretariat Production Approver Edit Access",
                    ),
                    ("bp_viewer", "Business Plan Viewer"),
                    ("bp_editor", "Business Plan Editor"),
                ],
                max_length=50,
            ),
        ),
    ]
