# Generated by Django 4.2.17 on 2026-07-29 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0316_pcr_version_created_by_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcrproject",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pcr_project",
                to="core.project",
            ),
        ),
    ]
