# Generated by Django 4.2.17 on 2026-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0317_alter_pcrproject_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcrsupportingevidence",
            name="filename",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
