# Generated by Django 4.2.17 on 2026-08-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0311_add_wmo_external_allocation"),
        (
            "core",
            "0319_merge_0310_project_date_updated_0318_alter_pcrsupportingevidence_filename",
        ),
    ]

    operations = []
