# Generated by Django 4.2.17 on 2026-08-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0320_merge_20260827_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="has_override_extended_date",
            field=models.BooleanField(
                default=False,
                help_text="Used in the inventory report. Overrides the Extended date (MYA)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="override_extended_date",
            field=models.DateField(
                blank=True, help_text="Extended date value override.", null=True
            ),
        ),
    ]
