# Generated by Django 4.2.17 on 2026-09-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0321_project_has_override_extended_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="hfc_licensing",
            field=models.BooleanField(
                default=False, verbose_name="HFC-specific licensing system exists"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="hfc_quota",
            field=models.BooleanField(
                default=False, verbose_name="HFC-specific quota system exists"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="ods_licensing",
            field=models.BooleanField(
                default=False, verbose_name="ODS import/export licensing system exists"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="ods_quota",
            field=models.BooleanField(
                default=False, verbose_name="ODS quota system exist"
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="ozone_unit_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
