# Generated by Django 4.2.17 on 2026-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0322_country_hfc_licensing_country_hfc_quota_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metaproject",
            name="end_date",
            field=models.DateField(blank=True, help_text="End date (MYA)", null=True),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="extended_date_of_completion",
            field=models.DateField(
                blank=True, help_text="Extended date of completion", null=True
            ),
        ),
        migrations.AlterField(
            model_name="metaproject",
            name="start_date",
            field=models.DateField(blank=True, help_text="Start date (MYA)", null=True),
        ),
    ]
