# Generated by Django 4.2.17 on 2026-09-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0323_alter_metaproject_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="competence_certification_system",
            field=models.BooleanField(
                default=False,
                verbose_name="Competence Certification System Established",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="meps",
            field=models.BooleanField(
                default=False,
                verbose_name="MEPS (Estabslished/Improved/Enforced) from Funded Projects",
            ),
        ),
    ]
