export type ProjectType = {
  agency: string
  agency_id: number
  agency_remarks: any
  application: any
  approval_meeting: number
  approval_meeting_id: number
  capital_cost: number
  cluster: any
  cluster_id: number
  code: string
  code_legacy: string
  comments: {
    agency_response: string
    id: number
    meeting_of_report: number
    meeting_of_report_id: number
    project_id: number
    secretariat_comment: string
  }[]
  compliance: any
  contingency_cost: any
  coop_agencies: []
  correspondance_no: any
  country: string
  country_id: number
  date_actual: string
  date_approved: any
  date_comp_revised: any
  date_completion: string
  date_of_revision: any
  date_per_agreement: any
  date_per_decision: any
  date_received: any
  description: any
  effectiveness_cost: any
  excom_provision: string
  export_to: number
  fund_disbursed: any
  fund_disbursed_psc: number
  funds: {
    amount: number
    date: string
    fund_type: string
    id: number
    interest: any
    meeting: number
    meeting_id: number
    project_id: number
    sort_order: number
    support_psc: number
  }[]
  funds_allocated: any
  hcfc_stage: any
  id: number
  impact: number
  impact_co2mt: number
  impact_prod_co2mt: number
  impact_production: number
  incomplete: boolean
  intersessional_approval: boolean
  issue: boolean
  issue_description: any
  latest_file: any
  loan: boolean
  local_ownership: number
  meeting_transf: any
  meeting_transf_id: any
  metaproject_category: string
  metaproject_code: string
  mya_code: string
  mya_subsector: string
  national_agency: any
  ods_odp: {
    co2_mt: number
    id: number
    odp: number
    ods_blend_id: any
    ods_display_name: string
    ods_replacement: any
    ods_substance_id: number
    ods_type: string
    project_id: number
    sort_order: number
  }[]
  ods_phasedout_co2mt: any
  operating_cost: number
  plan: any
  plus: boolean
  products_manufactured: any
  programme_officer: any
  project_cost: any
  project_duration: any
  project_type: any
  project_type_id: 4
  project_type_legacy: string
  rbm_measures: any[]
  remarks: string
  retroactive_finance: boolean
  reviewed_mfs: boolean
  revision_number: any
  sector: any
  sector_id: number
  sector_legacy: string
  serial_number: number
  stage: number
  status: string
  status_id: number
  submission_amounts: any[]
  submission_category: any
  submission_comments: any
  submission_number: any
  subsector: string
  subsector_id: number
  subsector_legacy: string
  substance_category: string
  substance_name: string
  substance_phasedout: number
  substance_type: string
  support_cost_psc: any
  technology: any
  title: string
  total_fund_approved: any
  total_fund_transferred: any
  total_grant: any
  total_psc_cost: any
  total_psc_transferred: any
  tranche: any
  umbrella_project: boolean
  withdrawn: boolean
}
