from django.urls import path, re_path
from rest_framework import routers, permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from core.api.views import MetaProjectClusterListView
from core.api.views import MetaProjectLeadAgencyListView
from core.api.views import (
    ProjectFundViewSet,
    ReplenishmentCountriesViewSet,
    ReplenishmentCountriesSOAViewSet,
    ReplenishmentAsOfDateViewSet,
    ReplenishmentBudgetYearsViewSet,
    ReplenishmentViewSet,
    AnnualStatusOfContributionsView,
    ScaleOfAssessmentViewSet,
    ReplenishmentScaleOfAssessmentVersionFileDownloadView,
    TriennialStatusOfContributionsView,
    SummaryStatusOfContributionsView,
    ReplenishmentDashboardView,
    ReplenishmentExternalAllocationViewSet,
    ReplenishmentExternalIncomeAnnualViewSet,
    ReplenishmentInvoiceViewSet,
    ReplenishmentInvoiceFileDownloadView,
    ReplenishmentPaymentViewSet,
    ReplenishmentPaymentFileDownloadView,
    DisputedContributionViewSet,
    BilateralAssistanceViewSet,
    ReplenishmentDashboardExportView,
    SummaryStatusOfContributionsExportView,
    TriennialStatusOfContributionsExportView,
    StatisticsStatusOfContributionsExportView,
    AnnualStatusOfContributionsExportView,
    StatusOfContributionsExportView,
    StatisticsExportView,
    StatisticsStatusOfContributionsView,
    StatusOfTheFundFileViewSet,
    ConsolidatedInputDataExportView,
    UserPermissionsView,
)
from core.api.views.agency import AgencyListView, BusinessPlanAgencyListView
from core.api.views.blanket_approval_details import BlanketApprovalDetailsViewset
from core.api.views.bp_export import BPActivityExportView
from core.api.views.business_plan import (
    BPChemicalTypeListView,
    BPFileDownloadView,
    BPFileView,
    BPActivityViewSet,
    BPImportValidateView,
    BPImportView,
    BusinessPlanViewSet,
)
from core.api.views.chemicals import (
    BlendCreateView,
    BlendNextCustNameView,
    BlendsListView,
    GroupListView,
    SimilarBlendsListView,
    SubstancesListView,
)
from core.api.views.cp_archive import (
    CPRecordArchiveExportView,
    CPRecordArchivePrintView,
    CPRecordsArchiveListView,
    CPReportVersionsListView,
)
from core.api.views.project_approval_summary import ProjectApprovalSummaryViewSet
from core.api.views.projects_compare_versions import ProjectsCompareVersionsViewset
from core.api.views.projects_metadata import (
    ProjectClusterTypeSectorAssociationView,
    ProjectFieldView,
)
from core.api.views.cp_emissions_generations import DashboardsCPEmissionsView
from core.api.views.cp_files import CPFilesDownloadView, CPFilesView
from core.api.views.cp_prices import DashboardsCPPricesView, CPPricesView
from core.api.views.cp_records_export import (
    CPCalculatedAmountExportView,
    CPDataExtractionAllExport,
    CPEmptyExportView,
    CPHCFCExportView,
    CPHFCExportView,
    CPReportListExportView,
    CPCalculatedAmountPrintView,
    CPRecordPrintView,
    CPRecordExportView,
)
from core.api.views.cp_reports import (
    CPReportStatusUpdateView,
    CPReportView,
    CPReportGroupByYearView,
    CPReportGroupByCountryView,
    CPReportCommentsView,
)
from core.api.views.cp_records import (
    DashboardsCPRecordView,
    CPRecordListByReportView,
    CPRecordListDiffView,
)
from core.api.views.cp_report_empty_form import EmptyFormView
from core.api.views.cp_resources import CPResourcesView
from core.api.views.meetings import DecisionListView, MeetingListView
from core.api.views.projects import (
    MetaProjectListView,
    MetaProjectCountryListView,
    MetaProjectMyaListView,
    MetaProjectMyaDetailsViewSet,
    ProjectClusterListView,
    ProjectSpecificFieldsListView,
    ProjectOdsOdpViewSet,
    ProjectRbmMeasureViewSet,
    ProjectStatisticsView,
    ProjectSubmissionAmountViewSet,
    ProjectViewSet,
    ProjectStatusListView,
    ProjectSubmissionStatusListView,
    ProjectTypeListView,
    ProjectCommentViewSet,
    ProjectFileView,
)
from core.api.views.project_enterprise import (
    EnterpriseViewSet,
    ProjectEnterpriseStatusView,
    ProjectEnterpriseViewSet,
)
from core.api.views.projects_v2 import (
    ProjectDestructionTechnologyView,
    ProjectProductionControlTypeView,
    ProjectOdsOdpTypeView,
    ProjectV2ViewSet,
)
from core.api.views.project_v2_files import (
    FileTypeView,
    ProjectFileV2ViewSet,
    ProjectFilesValidationView,
)
from core.api.views.project_associations import ProjectAssociationViewSet
from core.api.views.rbm_measures import RBMMeasureListView
from core.api.views.sector_subsector import ProjectSectorView, ProjectSubSectorView
from core.api.views.settings import (
    ProjectSettingsView,
    SettingsView,
)
from core.api.views.summary_of_projects import SummaryOfProjectsViewSet
from core.api.views.usages import UsageListView
from core.api.views.countries import CountryListView, BusinessPlanCountryListView
from core.api.views.annual_project_report import (
    APRCurrentYearView,
    APRWorkspaceView,
    APRBulkUpdateView,
    APRFileUploadView,
    APRFileDownloadView,
    APRFileDeleteView,
    APRFilesDownloadAllView,
    APRStatusView,
    APRExportView,
    APRSummaryTablesExportView,
    APRGlobalViewSet,
    APRToggleLockView,
    APREndorseView,
    APRMLFSBulkUpdateView,
    APRKickStartView,
    APRMLFSExportView,
)
from core.api.views.project_completion_report import (
    PCRAgencyReportDetailView,
    PCRAgencyReportStatusUpdateView,
    PCRCauseOfDelayView,
    PCRCommentCreateView,
    PCRCommentUpdateView,
    PCRDetailView,
    PCRGenderMainstreamingView,
    PCRLessonLearnedView,
    PCRListView,
    PCROverallAssessmentUpdateView,
    PCRProjectActivityCreateView,
    PCRProjectActivityUpdateView,
    PCRRecommendationCreateView,
    PCRRecommendationUpdateView,
    PCRReferenceDataView,
    PCRSDGContributionView,
    PCRSupportingEvidenceDeleteView,
    PCRSupportingEvidenceUploadView,
    PCRSubmitView,
    PCRToggleLockView,
    PCRTrancheDataUpdateView,
    PCRUpdateView,
    PCRWorkspaceView,
)

router = routers.SimpleRouter()
router.register(
    "projects-approval-summary",
    ProjectApprovalSummaryViewSet,
    basename="projects-approval-summary",
)
router.register(
    "summary-of-projects",
    SummaryOfProjectsViewSet,
    basename="summary-of-projects",
)
router.register(
    "blanket-approval-details",
    BlanketApprovalDetailsViewset,
    basename="blanket-approval-details",
)
router.register(
    "compare-versions",
    ProjectsCompareVersionsViewset,
    basename="compare-versions",
)
router.register("projects/v2", ProjectV2ViewSet, basename="project-v2")
router.register(
    r"projects/v2/(?P<project_id>\d+)/project-files",
    ProjectFileV2ViewSet,
    basename="project-file-v2",
)
router.register("projects", ProjectViewSet, basename="project")
router.register(
    "project-association", ProjectAssociationViewSet, basename="project-association"
)
router.register("enterprises", EnterpriseViewSet, basename="enterprise")
router.register(
    "project-enterprise", ProjectEnterpriseViewSet, basename="project-enterprise"
)
router.register("project-fund", ProjectFundViewSet)
router.register("project-ods-odp", ProjectOdsOdpViewSet)
router.register("project-comment", ProjectCommentViewSet)
router.register("project-rbm-measure", ProjectRbmMeasureViewSet)
router.register("project-sector", ProjectSectorView)
router.register("project-subsector", ProjectSubSectorView)
router.register("submission-amount", ProjectSubmissionAmountViewSet)
router.register("business-plan", BusinessPlanViewSet, basename="businessplan")
router.register("business-plan-activity", BPActivityViewSet, basename="bpactivity")
router.register(
    "replenishment/countries",
    ReplenishmentCountriesViewSet,
    basename="replenishment-countries",
)
router.register(
    "replenishment/countries-soa",
    ReplenishmentCountriesSOAViewSet,
    basename="replenishment-countries-soa",
)
router.register(
    "replenishment/as-of-date",
    ReplenishmentAsOfDateViewSet,
    basename="replenishment-as-of-date",
)
router.register(
    "replenishment/budget-years",
    ReplenishmentBudgetYearsViewSet,
    basename="replenishment-budget-years",
)
router.register(
    "replenishment/replenishments",
    ReplenishmentViewSet,
    basename="replenishment-replenishments",
)
router.register(
    "replenishment/disputed-contributions",
    DisputedContributionViewSet,
    basename="replenishment-disputed-contributions",
)
router.register(
    "replenishment/bilateral-assistance",
    BilateralAssistanceViewSet,
    basename="replenishment-bilateral-assistance",
)
router.register(
    "replenishment/scales-of-assessment",
    ScaleOfAssessmentViewSet,
    basename="replenishment-scales-of-assessment",
)
router.register(
    "replenishment/external-allocations",
    ReplenishmentExternalAllocationViewSet,
    basename="replenishment-external-allocations",
)
router.register(
    "replenishment/external-income",
    ReplenishmentExternalIncomeAnnualViewSet,
    basename="replenishment-external-income",
)
router.register(
    "replenishment/invoices",
    ReplenishmentInvoiceViewSet,
    basename="replenishment-invoices",
)
router.register(
    "replenishment/payments",
    ReplenishmentPaymentViewSet,
    basename="replenishment-payments",
)
router.register(
    "replenishment/status-files",
    StatusOfTheFundFileViewSet,
    basename="replenishment-status-files",
)
router.register(
    r"annual-project-report/mlfs/(?P<year>\d+)/agencies",
    APRGlobalViewSet,
    basename="apr-mlfs",
)

schema_view = get_schema_view(
    openapi.Info(
        title="Multilateral Fund API",
        default_version="v1",
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(
        r"^docs(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^docs/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "settings/",
        SettingsView.as_view(),
        name="settings",
    ),
    path(
        "project-settings/",
        ProjectSettingsView.as_view(),
        name="project-settings",
    ),
    path(
        "agencies/",
        AgencyListView.as_view(),
        name="agency-list",
    ),
    path(
        "usages/",
        UsageListView.as_view(),
        name="usages-list",
    ),
    path(
        "groups/",
        GroupListView.as_view(),
        name="group-list",
    ),
    path(
        "substances/",
        SubstancesListView.as_view(),
        name="substances-list",
    ),
    path(
        "project-fields/",
        ProjectFieldView.as_view(),
        name="project-fields",
    ),
    path(
        "project-cluster-types-sectors/",
        ProjectClusterTypeSectorAssociationView.as_view(),
        name="project-cluster-type-sector-association",
    ),
    path("blends/", BlendsListView.as_view(), name="blends-list"),
    path("blends/similar/", SimilarBlendsListView.as_view(), name="blends-similar"),
    path("blends/create/", BlendCreateView.as_view(), name="blends-create"),
    path(
        "blends/next-cust-mix-name/",
        BlendNextCustNameView.as_view(),
        name="blends-next-cust-mix-name",
    ),
    path(
        "country-programme/reports/",
        CPReportView.as_view(),
        name="country-programme-reports",
    ),
    path(
        "country-programme/reports/<int:id>/",
        CPReportView.as_view(),
        name="country-programme-reports-update",
    ),
    path(
        "country-programme/report/<int:id>/status-update/",
        CPReportStatusUpdateView.as_view(),
        name="country-programme-report-status",
    ),
    path(
        "country-programme/report/<int:id>/comments/",
        CPReportCommentsView.as_view(),
        name="country-programme-report-comments",
    ),
    path(
        "country-programme/reports-by-year/",
        CPReportGroupByYearView.as_view(),
        name="country-programme-reports-by-year",
    ),
    path(
        "country-programme/reports-by-country/",
        CPReportGroupByCountryView.as_view(),
        name="country-programme-reports-by-country",
    ),
    path(
        "country-programme/records/",
        CPRecordListByReportView.as_view(),
        name="country-programme-record-list",
    ),
    path(
        "country-programme/records/diff/",
        CPRecordListDiffView.as_view(),
        name="country-programme-record-diff",
    ),
    path(
        "country-programme/prices/",
        CPPricesView.as_view(),
        name="country-programme-price-list",
    ),
    path(
        "country-programme/dashboards/records/",
        DashboardsCPRecordView.as_view(),
        name="country-programme-dashboards-record",
    ),
    path(
        "country-programme/dashboards/prices/",
        DashboardsCPPricesView.as_view(),
        name="country-programme-dashboards-price-list",
    ),
    path(
        "country-programme/dashboards/emissions/",
        DashboardsCPEmissionsView.as_view(),
        name="country-programme-dashboards-emissions-list",
    ),
    path(
        "country-programme/export/",
        CPRecordExportView.as_view(),
        name="country-programme-export",
    ),
    path(
        "country-programme/reports/export/",
        CPReportListExportView.as_view(),
        name="country-programme-reports-export",
    ),
    path(
        "country-programme/hfc/export/",
        CPHFCExportView.as_view(),
        name="country-programme-hfc-export",
    ),
    path(
        "country-programme/hcfc/export/",
        CPHCFCExportView.as_view(),
        name="country-programme-hcfc-export",
    ),
    path(
        "country-programme/data-extraction-all/export/",
        CPDataExtractionAllExport.as_view(),
        name="country-programme-extraction-all-export",
    ),
    path(
        "country-programme/calculated-amount/export/",
        CPCalculatedAmountExportView.as_view(),
        name="country-programme-calculated-amount-export",
    ),
    path(
        "country-programme/calculated-amount/print/",
        CPCalculatedAmountPrintView.as_view(),
        name="country-programme-calculated-amount-print",
    ),
    path(
        "country-programme/export-empty/",
        CPEmptyExportView.as_view(),
        name="country-programme-export-empty",
    ),
    path(
        "country-programme/print/",
        CPRecordPrintView.as_view(),
        name="country-programme-print",
    ),
    path(
        "country-programme/empty-form/",
        EmptyFormView.as_view(),
        name="empty-form",
    ),
    path(
        "country-programme/versions/",
        CPReportVersionsListView.as_view(),
        name="country-programme-versions",
    ),
    path(
        "country-programme/files/",
        CPFilesView.as_view(),
        name="country-programme-files",
    ),
    path(
        "country-programme/files/<int:id>/download/",
        CPFilesDownloadView.as_view(),
        name="country-programme-files-download",
    ),
    path(
        "country-programme/resources/",
        CPResourcesView.as_view(),
        name="country-programme-resources",
    ),
    path(
        "country-programme-archive/records/",
        CPRecordsArchiveListView.as_view(),
        name="country-programme-archive-record-list",
    ),
    path(
        "country-programme-archive/export/",
        CPRecordArchiveExportView.as_view(),
        name="country-programme-archive-export",
    ),
    path(
        "country-programme-archive/print/",
        CPRecordArchivePrintView.as_view(),
        name="country-programme-archive-print",
    ),
    path(
        "countries/",
        CountryListView.as_view(),
        name="countries-list",
    ),
    path(
        "file-types/",
        FileTypeView.as_view(),
        name="file-type-list",
    ),
    path(
        "meta-projects/",
        MetaProjectListView.as_view(),
        name="meta-project-list",
    ),
    path(
        "meta-projects/countries/",
        MetaProjectCountryListView.as_view(),
        name="meta-project-country-list",
    ),
    path(
        "meta-projects/clusters/",
        MetaProjectClusterListView.as_view(),
        name="meta-project-cluster-list",
    ),
    path(
        "meta-projects/lead-agencies/",
        MetaProjectLeadAgencyListView.as_view(),
        name="meta-project-lead-agency-list",
    ),
    path(
        "meta-projects-for-mya-update/",
        MetaProjectMyaListView.as_view(),
        name="meta-projects-for-mya-update",
    ),
    path(
        "meta-projects/<int:pk>/",
        MetaProjectMyaDetailsViewSet.as_view({"get": "retrieve", "put": "update"}),
        name="meta-project-view",
    ),
    path(
        "project-statuses/",
        ProjectStatusListView.as_view(),
        name="project-status-list",
    ),
    path(
        "project-submission-statuses/",
        ProjectSubmissionStatusListView.as_view(),
        name="project-submission-status-list",
    ),
    path(
        "project-types/",
        ProjectTypeListView.as_view(),
        name="project-type-list",
    ),
    path(
        "projects-statistics/",
        ProjectStatisticsView.as_view(),
        name="project-statistics",
    ),
    path(
        "meetings/",
        MeetingListView.as_view(),
        name="meeting-list",
    ),
    path(
        "decisions/",
        DecisionListView.as_view(),
        name="decision-list",
    ),
    path(
        "project-destruction-technology/",
        ProjectDestructionTechnologyView.as_view(),
        name="project-destruction-technology",
    ),
    path(
        "project-enterprise-status/",
        ProjectEnterpriseStatusView.as_view(),
        name="project-enterprise-status",
    ),
    path(
        "project-production-control-type/",
        ProjectProductionControlTypeView.as_view(),
        name="project-production-control-type",
    ),
    path(
        "project-ods-odp-type/",
        ProjectOdsOdpTypeView.as_view(),
        name="project-ods-odp-type",
    ),
    path(
        "project-clusters/",
        ProjectClusterListView.as_view(),
        name="project-cluster-list",
    ),
    path(
        "project-cluster/<int:cluster_id>/type/<int:type_id>/sector/<int:sector_id>/fields/",
        ProjectSpecificFieldsListView.as_view(),
        name="project-specific-fields",
    ),
    path(
        "rbm-measures/",
        RBMMeasureListView.as_view(),
        name="rbm-measure-list",
    ),
    re_path(
        "^project-files/(?P<pk>[^/]+)/$",
        ProjectFileView.as_view(),
        name="project-files",
    ),
    path(
        "project/files/validate/",
        ProjectFilesValidationView.as_view(),
        name="project-files-validation",
    ),
    path(
        "business-plan/upload/validate/",
        BPImportValidateView.as_view(),
        name="bp-upload-validate",
    ),
    path(
        "business-plan/upload/",
        BPImportView.as_view(),
        name="bp-upload",
    ),
    path(
        "business-plan/agencies/",
        BusinessPlanAgencyListView.as_view(),
        name="bp-agencies-list",
    ),
    path(
        "business-plan/countries/",
        BusinessPlanCountryListView.as_view(),
        name="business-plan-countries-list",
    ),
    path(
        "business-plan/bp-chemical-types/",
        BPChemicalTypeListView.as_view(),
        name="bp-chemical-type-list",
    ),
    path(
        "business-plan-activity/export/",
        BPActivityExportView.as_view(),
        name="bpactivity-export",
    ),
    path(
        "business-plan/files/",
        BPFileView.as_view(),
        name="business-plan-files",
    ),
    path(
        "business-plan/files/<int:id>/download/",
        BPFileDownloadView.as_view(),
        name="business-plan-file-download",
    ),
    path(
        "replenishment/dashboard/",
        ReplenishmentDashboardView.as_view(),
        name="replenishment-dashboard",
    ),
    path(
        "replenishment/dashboard/export/",
        ReplenishmentDashboardExportView.as_view(),
        name="replenishment-dashboard-export",
    ),
    path(
        "replenishment/status-of-contributions/statistics/",
        StatisticsStatusOfContributionsView.as_view(),
        name="replenishment-status-of-contributions-statistics",
    ),
    path(
        "replenishment/status-of-contributions/statistics-export/",
        StatisticsStatusOfContributionsExportView.as_view(),
        name="replenishment-status-of-contributions-statistics-export",
    ),
    path(
        "replenishment/status-of-contributions/summary/export/",
        SummaryStatusOfContributionsExportView.as_view(),
        name="replenishment-status-of-contributions-summary-export",
    ),
    path(
        "replenishment/status-of-contributions/summary/",
        SummaryStatusOfContributionsView.as_view(),
        name="replenishment-status-of-contributions-summary",
    ),
    path(
        "replenishment/status-of-contributions/<int:start_year>/<int:end_year>/export/",
        TriennialStatusOfContributionsExportView.as_view(),
        name="replenishment-status-of-contributions-triennial-export",
    ),
    path(
        "replenishment/status-of-contributions/export/",
        StatusOfContributionsExportView.as_view(),
        name="replenishment-status-of-contributions-export",
    ),
    path(
        "replenishment/status-of-contributions/<int:start_year>/<int:end_year>/",
        TriennialStatusOfContributionsView.as_view(),
        name="replenishment-status-of-contributions-triennial",
    ),
    path(
        "replenishment/status-of-contributions/<int:year>/export/",
        AnnualStatusOfContributionsExportView.as_view(),
        name="replenishment-status-of-contributions-annual-export",
    ),
    path(
        "replenishment/statistics/export/",
        StatisticsExportView.as_view(),
        name="replenishment-statistics-export",
    ),
    path(
        "replenishment/status-of-contributions/<int:year>/",
        AnnualStatusOfContributionsView.as_view(),
        name="replenishment-status-of-contributions-annual",
    ),
    path(
        "replenishment/invoice-file/<int:id>/download/",
        ReplenishmentInvoiceFileDownloadView.as_view(),
        name="replenishment-invoice-file-download",
    ),
    path(
        "replenishment/payment-file/<int:id>/download/",
        ReplenishmentPaymentFileDownloadView.as_view(),
        name="replenishment-payment-file-download",
    ),
    path(
        "replenishment/scale-of-assessment-version/<int:id>/file/download/",
        ReplenishmentScaleOfAssessmentVersionFileDownloadView.as_view(),
        name="scale-of-assessment-version-file-download",
    ),
    path(
        "replenishment/input-data/export/",
        ConsolidatedInputDataExportView.as_view(),
        name="replenishment-input-data-export",
    ),
    # Annual Project Reports
    path(
        "annual-project-report/current-year/",
        APRCurrentYearView.as_view(),
        name="apr-current-year",
    ),
    path(
        "annual-project-report/<int:year>/workspace/",
        APRWorkspaceView.as_view(),
        name="apr-workspace",
    ),
    path(
        "annual-project-report/<int:year>/agency/<int:agency_id>/export/",
        APRExportView.as_view(),
        name="apr-export",
    ),
    path(
        "annual-project-report/summary-tables/export/",
        APRSummaryTablesExportView.as_view(),
        name="apr-summary-tables-export",
    ),
    path(
        "annual-project-report/<int:year>/agency/<int:agency_id>/update/",
        APRBulkUpdateView.as_view(),
        name="apr-update",
    ),
    path(
        "annual-project-report/mlfs/<int:year>/bulk-update/",
        APRMLFSBulkUpdateView.as_view(),
        name="apr-mlfs-bulk-update",
    ),
    path(
        "annual-project-report/<int:year>/agency/<int:agency_id>/upload/",
        APRFileUploadView.as_view(),
        name="apr-file-upload",
    ),
    path(
        "annual-project-report/<int:year>/agency/<int:agency_id>/files/<int:pk>/download/",
        APRFileDownloadView.as_view(),
        name="apr-file-download",
    ),
    path(
        "annual-project-report/<int:year>/agency/<int:agency_id>/files/<int:pk>/",
        APRFileDeleteView.as_view(),
        name="apr-file-delete",
    ),
    path(
        "annual-project-report/<int:year>/agency/<int:agency_id>/files/download-all/",
        APRFilesDownloadAllView.as_view(),
        name="apr-files-download-all",
    ),
    path(
        "annual-project-report/<int:year>/agency/<int:agency_id>/status/",
        APRStatusView.as_view(),
        name="apr-status",
    ),
    path(
        "annual-project-report/<int:year>/agency/<int:agency_id>/toggle-lock/",
        APRToggleLockView.as_view(),
        name="apr-toggle-lock",
    ),
    path(
        "annual-project-report/<int:year>/endorse/",
        APREndorseView.as_view(),
        name="apr-endorse",
    ),
    path(
        "annual-project-report/kick-start/",
        APRKickStartView.as_view(),
        name="apr-kick-start",
    ),
    path(
        "annual-project-report/mlfs/<int:year>/export/",
        APRMLFSExportView.as_view(),
        name="apr-mlfs-export",
    ),
    # Project Completion Reports (PCR)
    path(
        "project-completion-report/reference-data/",
        PCRReferenceDataView.as_view(),
        name="pcr-reference-data",
    ),
    path(
        "project-completion-report/workspace/",
        PCRWorkspaceView.as_view(),
        name="pcr-workspace",
    ),
    path(
        "project-completion-report/list/",
        PCRListView.as_view(),
        name="pcr-list",
    ),
    path(
        "project-completion-report/<int:pk>/",
        PCRDetailView.as_view(),
        name="pcr-detail",
    ),
    path(
        "project-completion-report/<int:pk>/update/",
        PCRUpdateView.as_view(),
        name="pcr-update",
    ),
    path(
        "project-completion-report/<int:pk>/submit/",
        PCRSubmitView.as_view(),
        name="pcr-submit",
    ),
    # Agency Report endpoints
    path(
        "project-completion-report/agency-report/<int:pk>/",
        PCRAgencyReportDetailView.as_view(),
        name="pcr-agency-report-detail",
    ),
    path(
        "project-completion-report/agency-report/<int:pk>/status/",
        PCRAgencyReportStatusUpdateView.as_view(),
        name="pcr-agency-report-status",
    ),
    path(
        "project-completion-report/agency-report/<int:pk>/toggle-lock/",
        PCRToggleLockView.as_view(),
        name="pcr-agency-report-toggle-lock",
    ),
    # Section 2: Project Activities
    path(
        "project-completion-report/agency-report/<int:agency_report_id>/activities/",
        PCRProjectActivityCreateView.as_view(),
        name="pcr-activity-create",
    ),
    path(
        "project-completion-report/activity/<int:pk>/",
        PCRProjectActivityUpdateView.as_view(),
        name="pcr-activity-update",
    ),
    # Section 2: Overall Assessment
    path(
        "project-completion-report/agency-report/<int:agency_report_id>/overall-assessment/",
        PCROverallAssessmentUpdateView.as_view(),
        name="pcr-overall-assessment-update",
    ),
    # Comments (can be on agency report or PCR)
    path(
        "project-completion-report/comments/",
        PCRCommentCreateView.as_view(),
        name="pcr-comment-create",
    ),
    path(
        "project-completion-report/comment/<int:pk>/",
        PCRCommentUpdateView.as_view(),
        name="pcr-comment-update",
    ),
    # Section 3: Causes of Delay
    path(
        "project-completion-report/agency-report/<int:agency_report_id>/causes-of-delay/",
        PCRCauseOfDelayView.as_view(),
        name="pcr-cause-of-delay-create",
    ),
    path(
        "project-completion-report/cause-of-delay/<int:pk>/",
        PCRCauseOfDelayView.as_view(),
        name="pcr-cause-of-delay-update",
    ),
    # Section 4: Lessons Learned
    path(
        "project-completion-report/agency-report/<int:agency_report_id>/lessons-learned/",
        PCRLessonLearnedView.as_view(),
        name="pcr-lesson-learned-create",
    ),
    path(
        "project-completion-report/lesson-learned/<int:pk>/",
        PCRLessonLearnedView.as_view(),
        name="pcr-lesson-learned-update",
    ),
    # Section 4: Recommendations (can be on agency report or PCR)
    path(
        "project-completion-report/recommendations/",
        PCRRecommendationCreateView.as_view(),
        name="pcr-recommendation-create",
    ),
    path(
        "project-completion-report/recommendation/<int:pk>/",
        PCRRecommendationUpdateView.as_view(),
        name="pcr-recommendation-update",
    ),
    # Section 5: Gender Mainstreaming
    path(
        "project-completion-report/agency-report/<int:agency_report_id>/gender-mainstreaming/",
        PCRGenderMainstreamingView.as_view(),
        name="pcr-gender-mainstreaming-create",
    ),
    path(
        "project-completion-report/gender-mainstreaming/<int:pk>/",
        PCRGenderMainstreamingView.as_view(),
        name="pcr-gender-mainstreaming-update",
    ),
    # Section 6: SDG Contributions
    path(
        "project-completion-report/agency-report/<int:agency_report_id>/sdg-contributions/",
        PCRSDGContributionView.as_view(),
        name="pcr-sdg-contribution-create",
    ),
    path(
        "project-completion-report/sdg-contribution/<int:pk>/",
        PCRSDGContributionView.as_view(),
        name="pcr-sdg-contribution-update",
    ),
    # Section 7: Tranche Data
    path(
        "project-completion-report/tranche-data/<int:pk>/",
        PCRTrancheDataUpdateView.as_view(),
        name="pcr-tranche-data-update",
    ),
    # Section 8: Supporting Evidence
    path(
        "project-completion-report/supporting-evidence/upload/",
        PCRSupportingEvidenceUploadView.as_view(),
        name="pcr-supporting-evidence-upload",
    ),
    path(
        "project-completion-report/supporting-evidence/<int:pk>/",
        PCRSupportingEvidenceDeleteView.as_view(),
        name="pcr-supporting-evidence-delete",
    ),
    # User permissions
    path(
        "user/permissions/",
        UserPermissionsView.as_view(),
        name="user-permissions",
    ),
    *router.urls,
]
