# Generated by Django 4.1.7 on 2023-03-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend_name', models.CharField(max_length=100)),
                ('blend_description', models.TextField()),
                ('blend_odp', models.FloatField()),
                ('blend_gwp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance_name', models.CharField(max_length=100)),
                ('substance_description', models.TextField()),
                ('substance_formula', models.CharField(max_length=100)),
                ('substance_isomers', models.IntegerField()),
                ('substance_odp', models.FloatField()),
                ('substance_gwp', models.FloatField()),
                ('substance_polyol', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BlendSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('blend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterDB.blend')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterDB.substance')),
            ],
        ),
        migrations.AddField(
            model_name='blend',
            name='blend_substances',
            field=models.ManyToManyField(through='MasterDB.BlendSubstance', to='MasterDB.substance'),
        ),
    ]
