# Generated by Django 4.1.7 on 2023-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='substance_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='substance_formula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='substance_gwp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='substance_isomers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='substance_odp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='substance_polyol',
            field=models.BooleanField(default=False),
        ),
    ]
