# Generated by Django 4.1.7 on 2023-03-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDB', '0002_alter_substance_substance_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blend',
            name='blend_gwp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blend',
            name='blend_odp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
