# Generated by Django 4.1.7 on 2023-03-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDB', '0003_alter_blend_blend_gwp_alter_blend_blend_odp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendsubstance',
            name='blend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blend', to='MasterDB.blend'),
        ),
        migrations.AlterField(
            model_name='blendsubstance',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance', to='MasterDB.substance'),
        ),
    ]
