const COUNTRIES = [
  {
    id: 421,
    abbr: 'AD',
    has_cp_report: false,
    is_a2: false,
    iso3: 'AND',
    name: 'Andorra',
    name_alt: 'Andorra',
  },
  {
    id: 426,
    abbr: 'AU',
    has_cp_report: false,
    is_a2: false,
    iso3: 'AUS',
    name: 'Australia',
    name_alt: 'Australia',
  },
  {
    id: 427,
    abbr: 'AT',
    has_cp_report: false,
    is_a2: false,
    iso3: 'AUT',
    name: 'Austria',
    name_alt: 'Austria',
  },
  {
    id: 428,
    abbr: 'AZ',
    has_cp_report: false,
    is_a2: false,
    iso3: 'AZE',
    name: 'Azerbaijan',
    name_alt: 'Azerbaijan',
  },
  {
    id: 433,
    abbr: 'BY',
    has_cp_report: false,
    is_a2: false,
    iso3: 'BLR',
    name: 'Belarus',
    name_alt: 'Belarus',
  },
  {
    id: 434,
    abbr: 'BE',
    has_cp_report: false,
    is_a2: false,
    iso3: 'BEL',
    name: 'Belgium',
    name_alt: 'Belgium',
  },
  {
    id: 4341,
    abbr: 'BG',
    has_cp_report: false,
    is_a2: false,
    iso3: 'BGR',
    name: 'Bulgaria',
    name_alt: 'Bulgaria',
  },
  {
    id: 4342,
    abbr: 'CA',
    has_cp_report: false,
    is_a2: false,
    iso3: 'CAN',
    name: 'Canada',
    name_alt: 'Canada',
  },
  {
    id: 43421,
    abbr: 'HR',
    has_cp_report: false,
    is_a2: false,
    iso3: 'HRV',
    name: 'Croatia',
    name_alt: 'Croatia',
  },
  {
    id: 462,
    abbr: 'CY',
    has_cp_report: false,
    is_a2: false,
    iso3: 'CYP',
    name: 'Cyprus',
    name_alt: 'Cyprus',
  },
  {
    id: 463,
    abbr: 'CZ',
    has_cp_report: false,
    is_a2: false,
    iso3: 'CZE',
    name: 'Czechia',
    name_alt: 'Czechia',
  },
  {
    id: 466,
    abbr: 'DK',
    has_cp_report: false,
    is_a2: false,
    iso3: 'DNK',
    name: 'Denmark',
    name_alt: 'Denmark',
  },
  {
    id: 4631,
    abbr: 'EE',
    has_cp_report: false,
    is_a2: false,
    iso3: 'EST',
    name: 'Estonia',
    name_alt: 'Estonia',
  },
  {
    id: 480,
    abbr: 'FI',
    has_cp_report: false,
    is_a2: false,
    iso3: 'FIN',
    name: 'Finland',
    name_alt: 'Finland',
  },
  {
    id: 4801,
    abbr: 'FR',
    has_cp_report: false,
    is_a2: false,
    iso3: 'FRA',
    name: 'France',
    name_alt: 'France',
  },
  {
    id: 485,
    abbr: 'DE',
    has_cp_report: false,
    is_a2: false,
    iso3: 'DEU',
    name: 'Germany',
    name_alt: 'Germany',
  },
  {
    id: 487,
    abbr: 'GR',
    has_cp_report: false,
    is_a2: false,
    iso3: 'GRC',
    name: 'Greece',
    name_alt: 'Greece',
  },
  {
    id: 494,
    abbr: 'VA',
    has_cp_report: false,
    is_a2: false,
    iso3: 'VAT',
    name: 'Holy See',
    name_alt: 'Holy See',
  },
  {
    id: 496,
    abbr: 'HU',
    has_cp_report: false,
    is_a2: false,
    iso3: 'HUN',
    name: 'Hungary',
    name_alt: 'Hungary',
  },
  {
    id: 497,
    abbr: 'IS',
    has_cp_report: false,
    is_a2: false,
    iso3: 'ISL',
    name: 'Iceland',
    name_alt: 'Iceland',
  },
  {
    id: 502,
    abbr: 'IE',
    has_cp_report: false,
    is_a2: false,
    iso3: 'IRL',
    name: 'Ireland',
    name_alt: 'Ireland',
  },
  {
    id: 503,
    abbr: 'IL',
    has_cp_report: false,
    is_a2: false,
    iso3: 'ISR',
    name: 'Israel',
    name_alt: 'Israel',
  },
  {
    id: 504,
    abbr: 'IT',
    has_cp_report: false,
    is_a2: false,
    iso3: 'ITA',
    name: 'Italy',
    name_alt: 'Italy',
  },
  {
    id: 506,
    abbr: 'JP',
    has_cp_report: false,
    is_a2: false,
    iso3: 'JPN',
    name: 'Japan',
    name_alt: 'Japan',
  },
  {
    id: 5061,
    abbr: 'KZ',
    has_cp_report: false,
    is_a2: false,
    iso3: 'KAZ',
    name: 'Kazakhstan',
    name_alt: 'Kazakhstan',
  },
  {
    id: 514,
    abbr: 'LV',
    has_cp_report: false,
    is_a2: false,
    iso3: 'LVA',
    name: 'Latvia',
    name_alt: 'Latvia',
  },
  {
    id: 519,
    abbr: 'LI',
    has_cp_report: false,
    is_a2: false,
    iso3: 'LIE',
    name: 'Liechtenstein',
    name_alt: 'Liechtenstein',
  },
  {
    id: 520,
    abbr: 'LT',
    has_cp_report: false,
    is_a2: false,
    iso3: 'LTU',
    name: 'Lithuania',
    name_alt: 'Lithuania',
  },
  {
    id: 521,
    abbr: 'LU',
    has_cp_report: false,
    is_a2: false,
    iso3: 'LUX',
    name: 'Luxembourg',
    name_alt: 'Luxembourg',
  },
  {
    id: 527,
    abbr: 'MT',
    has_cp_report: false,
    is_a2: false,
    iso3: 'MLT',
    name: 'Malta',
    name_alt: 'Malta',
  },
  {
    id: 533,
    abbr: 'MC',
    has_cp_report: false,
    is_a2: false,
    iso3: 'MCO',
    name: 'Monaco',
    name_alt: 'Monaco',
  },
  {
    id: 542,
    abbr: 'NL',
    has_cp_report: false,
    is_a2: false,
    iso3: 'NLD',
    name: 'Netherlands (Kingdom of the)',
    name_alt: 'Netherlands',
  },
  {
    id: 543,
    abbr: 'NZ',
    has_cp_report: false,
    is_a2: false,
    iso3: 'NZL',
    name: 'New Zealand',
    name_alt: 'New Zealand',
  },
  {
    id: 549,
    abbr: 'NO',
    has_cp_report: false,
    is_a2: false,
    iso3: 'NOR',
    name: 'Norway',
    name_alt: 'Norway',
  },
  {
    id: 558,
    abbr: 'PL',
    has_cp_report: false,
    is_a2: false,
    iso3: 'POL',
    name: 'Poland',
    name_alt: 'Poland',
  },
  {
    id: 559,
    abbr: 'PT',
    has_cp_report: false,
    is_a2: false,
    iso3: 'PRT',
    name: 'Portugal',
    name_alt: 'Portugal',
  },
  {
    id: 559,
    abbr: 'RO',
    has_cp_report: false,
    is_a2: false,
    iso3: 'ROU',
    name: 'Romania',
    name_alt: 'Romania',
  },
  {
    id: 564,
    abbr: 'RU',
    has_cp_report: false,
    is_a2: false,
    iso3: 'RUS',
    name: 'Russian Federation',
    name_alt: 'Russian Federation',
  },
  {
    id: 570,
    abbr: 'SM',
    has_cp_report: false,
    is_a2: false,
    iso3: 'SMR',
    name: 'San Marino',
    name_alt: 'San Marino',
  },
  {
    id: 578,
    abbr: 'SK',
    has_cp_report: false,
    is_a2: false,
    iso3: 'SVK',
    name: 'Slovakia',
    name_alt: 'Slovakia',
  },
  {
    id: 579,
    abbr: 'SI',
    has_cp_report: false,
    is_a2: false,
    iso3: 'SVN',
    name: 'Slovenia',
    name_alt: 'Slovenia',
  },
  {
    id: 584,
    abbr: 'ES',
    has_cp_report: false,
    is_a2: false,
    iso3: 'ESP',
    name: 'Spain',
    name_alt: 'Spain',
  },
  {
    id: 589,
    abbr: 'SE',
    has_cp_report: false,
    is_a2: false,
    iso3: 'SWE',
    name: 'Sweden',
    name_alt: 'Sweden',
  },
  {
    id: 590,
    abbr: 'CH',
    has_cp_report: false,
    is_a2: false,
    iso3: 'CHE',
    name: 'Switzerland',
    name_alt: 'Switzerland',
  },
  {
    id: 592,
    abbr: 'TJ',
    has_cp_report: false,
    is_a2: false,
    iso3: 'TJK',
    name: 'Tajikistan',
    name_alt: 'Tajikistan',
  },
  {
    id: 6051,
    abbr: 'UA',
    has_cp_report: false,
    is_a2: false,
    iso3: 'UKR',
    name: 'Ukraine',
    name_alt: 'Ukraine',
  },
  {
    id: 605,
    abbr: 'GB',
    has_cp_report: false,
    is_a2: false,
    iso3: 'GBR',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    name_alt: 'United Kingdom',
  },
  {
    id: 999,
    abbr: 'US',
    has_cp_report: false,
    is_a2: false,
    iso3: 'USA',
    name: 'United States of America',
    name_alt: 'United States of America',
  },
  {
    id: 609,
    abbr: 'UZ',
    has_cp_report: false,
    is_a2: false,
    iso3: 'UZB',
    name: 'Uzbekistan',
    name_alt: 'Uzbekistan',
  },
]

export default COUNTRIES
