name: Deploy Production

# Ensure that only one job works on this at a time
concurrency: prod_deployment

on:
  workflow_call:

jobs:
  deploy:
    runs-on:
      - self-hosted
      - ors-prod
    steps:
      - uses: actions/checkout@v3
      - name: Update docker-compose.yml
        run: |
          cp docker-compose.yml /home/ors/
      - name: Update services
        run: |
          cd /home/ors/
          docker compose pull
          docker compose up -d --remove-orphans
          docker compose top
