name: Create and publish Docker Images

on:
  workflow_call:
    inputs:
      SENTRY_DSN:
        required: false
        type: string
        default: ""
      SENTRY_ENVIRONMENT:
        required: false
        type: string
        default: "production"

      build_app:
        required: false
        type: boolean
        default: false

      build_nextjs:
        required: false
        type: boolean
        default: false

      build_nginx:
        required: false
        type: boolean
        default: false

      build_celery:
        required: false
        type: boolean
        default: false

    secrets:
      VITE_FRONTEND_CLIENT_ID:
        required: false
      VITE_TENANT_ID:
        required: false
      VITE_APPLICATION_ID_URI:
        required: false

    outputs:
      images_built:
        value: ${{ jobs.result.outputs.images_built }}


jobs:
  changes:
    uses: ./.github/workflows/detect-changes.yml

  build-app:
    needs: changes
    if: needs.changes.outputs.app == 'true' || inputs.build_app
    uses: ./.github/workflows/build-image.yml
    with:
      name: app
      dockerfile: ./docker/app.docker
      image: ghcr.io/multilateralfund/multilateralfund-app
      SENTRY_DSN: ${{ inputs.SENTRY_DSN }}
      SENTRY_ENVIRONMENT: ${{ inputs.SENTRY_ENVIRONMENT }}
    secrets:
      VITE_TENANT_ID: ${{ secrets.VITE_TENANT_ID }}
      VITE_FRONTEND_CLIENT_ID: ${{ secrets.VITE_FRONTEND_CLIENT_ID }}
      VITE_APPLICATION_ID_URI: ${{ secrets.VITE_APPLICATION_ID_URI }}

  build-nextjs:
    needs: changes
    if: needs.changes.outputs.nextjs == 'true' || inputs.build_nextjs
    uses: ./.github/workflows/build-image.yml
    with:
      name: nextjs
      dockerfile: ./docker/nextjs.docker
      image: ghcr.io/multilateralfund/multilateralfund-nextjs
      SENTRY_DSN: ${{ inputs.SENTRY_DSN }}
      SENTRY_ENVIRONMENT: ${{ inputs.SENTRY_ENVIRONMENT }}
    secrets:
      VITE_TENANT_ID: ${{ secrets.VITE_TENANT_ID }}
      VITE_FRONTEND_CLIENT_ID: ${{ secrets.VITE_FRONTEND_CLIENT_ID }}
      VITE_APPLICATION_ID_URI: ${{ secrets.VITE_APPLICATION_ID_URI }}

  build-nginx:
    needs: changes
    if: needs.changes.outputs.nginx == 'true' || inputs.build_nginx
    uses: ./.github/workflows/build-image.yml
    with:
      name: nginx
      dockerfile: ./docker/nginx.docker
      image: ghcr.io/multilateralfund/multilateralfund-nginx

  build-celery:
    needs: changes
    if: needs.changes.outputs.celery == 'true' || inputs.build_celery
    uses: ./.github/workflows/build-image.yml
    with:
      name: celery
      dockerfile: ./docker/celery.docker
      image: ghcr.io/multilateralfund/multilateralfund-celery

  result:
    needs:
      - build-app
      - build-nextjs
      - build-nginx
      - build-celery
    if: always()
    runs-on: ubuntu-latest

    outputs:
      images_built: ${{ steps.result.outputs.images_built }}

    steps:
      - id: result
        run: |
          echo "images_built=${{
            needs.build-app.outputs.built == 'true' ||
            needs.build-nextjs.outputs.built == 'true' ||
            needs.build-nginx.outputs.built == 'true' ||
            needs.build-celery.outputs.built == 'true'
          }}" >> "$GITHUB_OUTPUT"
