name: "Check backend code style"

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: "Install requirements"
        run: |
          pip install -r requirements-dev.txt
      - name: "Lint backend code"
        run: |
          cp .env.test.example .env
          pylint --django-settings-module=multilateralfund.settings --rcfile ./.pylintrc "**/*.py"
