name: "CI-prod"

on:
  workflow_dispatch:
    inputs:
      build_app:
        description: "Build app image"
        type: boolean
        default: true

      build_nextjs:
        description: "Build nextjs image"
        type: boolean
        default: true

      build_nginx:
        description: "Build nginx image"
        type: boolean
        default: false

jobs:
  docker-build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker-build.yml
    with:
      SENTRY_DSN: ${{ vars.PROD_SENTRY_DSN }}
      SENTRY_ENVIRONMENT: ${{ vars.PROD_SENTRY_ENVIRONMENT }}

      build_app: ${{ inputs.build_app }}
      build_nextjs: ${{ inputs.build_nextjs }}
      build_nginx: ${{ inputs.build_nginx }}

    secrets:
      VITE_TENANT_ID: ${{ secrets.PROD_VITE_TENANT_ID || '' }}
      VITE_FRONTEND_CLIENT_ID: ${{ secrets.PROD_VITE_FRONTEND_CLIENT_ID || '' }}
      VITE_APPLICATION_ID_URI: ${{ secrets.PROD_VITE_APPLICATION_ID_URI || '' }}

  deploy-prod:
    needs: docker-build
    if: needs.docker-build.outputs.images_built == 'true'
    uses: ./.github/workflows/deploy-prod.yml
