name: "CI-azure"

on:
  workflow_dispatch:
    inputs:
      build_app:
        description: "Build app image"
        type: boolean
        default: true

      build_nextjs:
        description: "Build nextjs image"
        type: boolean
        default: true

      build_nginx:
        description: "Build nginx image"
        type: boolean
        default: false

      build_celery:
        description: "Build celery image"
        type: boolean
        default: false

      build_libreoffice:
        description: "Build LibreOffice image"
        type: boolean
        default: false

jobs:
  docker-build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker-build.yml
    with:
      build_app: ${{ inputs.build_app }}
      build_nextjs: ${{ inputs.build_nextjs }}
      build_nginx: ${{ inputs.build_nginx }}
      build_celery: ${{ inputs.build_celery }}
      build_libreoffice: ${{ inputs.build_libreoffice }}
      # SENTRY_DSN: ${{ vars.PROD_SENTRY_DSN }}
      # SENTRY_ENVIRONMENT: ${{ vars.PROD_SENTRY_ENVIRONMENT }}

  deploy-azure:
    needs: docker-build
    if: needs.docker-build.outputs.images_built == 'true'
    uses: ./.github/workflows/deploy-azure.yml
    secrets:
      AZURE_SSH_USER: ${{ secrets.AZURE_SSH_USER }}
      AZURE_SSH_HOST: ${{ secrets.AZURE_SSH_HOST }}
      AZURE_SSH_KEY: ${{ secrets.AZURE_SSH_KEY }}
