name: "Test Suite"

on:
  workflow_call:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  changes:
    uses: ./.github/workflows/detect-changes.yml

  suite:
    needs: changes
    if: needs.changes.outputs.app == 'true' || needs.changes.outputs.nextjs == 'true'

    # runs-on: ubuntu-latest
    runs-on: docker-ors-2 # see https://helpdesk.eaudeweb.ro/issues/38046

    env:
      COMPOSE_FILE: docker-compose.tests.yml

    steps:
      - uses: actions/checkout@v6

      - name: "Remove leftovers"
        run: docker compose down -v --remove-orphans || true

      - name: "Frontend tests"
        if: needs.changes.outputs.nextjs == 'true'
        run: |
          docker compose build --pull nextjs
          docker compose run --rm --no-deps nextjs npm test

      - name: "Backend tests"
        if: needs.changes.outputs.app == 'true'
        run: |
          docker compose build --pull app
          docker compose up -d --wait postgres
          docker compose run --rm --no-deps app \
            sh -c 'python manage.py makemigrations --check && pytest -vv'

      - name: "Display logs if tests fail"
        if: failure()
        run: docker compose logs

      - name: "Tear down"
        if: always()
        run: docker compose down -v --remove-orphans
