"""
The 48 fund-wide metric declarations.
"""

from core.api.dashboard_metrics.registry import (
    Disposition,
    Kind,
    Metric,
    Unit,
    index_metrics,
)

FUND_METRICS: tuple[Metric, ...] = (
    Metric(
        metric_id="ods_avoided_emissions",
        label="Total avoided emissions from ODS",
        section="From protecting the ozone layer to safeguarding climate and health",
        kind=Kind.SCALAR,
        unit=Unit.ODP_TONNES,
        disposition=Disposition.COMPUTE,
        formula="manual admin field",
        db_source="MANUAL-CONSTANCE",
        src_model_field="constance config TOTAL_AVOIDED_EMISSIONS_OF_ODS_IN_ODP_TONNES",
        compute=None,
    ),
    Metric(
        metric_id="controlled_substances_avoided_emissions",
        label="Total avoided emissions from controlled substances",
        section="From protecting the ozone layer to safeguarding climate and health",
        kind=Kind.SCALAR,
        unit=Unit.CO2EQ_TONNES,
        disposition=Disposition.COMPUTE,
        formula="manual admin field",
        db_source="MANUAL-CONSTANCE",
        src_model_field=(
            "constance "
            "TOTAL_AVOIDED_EMISSIONS_OF_CONTROLLED_SUBSTANCES_IN_CO2_EQ_TONNES "
            "(+EXPECTED_AVOIDED_EMISSIONS_FROM_HFCS_IN_CO2_EQ_TONNES)"
        ),
        compute=None,
    ),
    Metric(
        metric_id="hfc_expected_avoided_emissions",
        label="Expected avoided emissions from HFCs",
        section="From protecting the ozone layer to safeguarding climate and health",
        kind=Kind.SCALAR,
        unit=Unit.CO2EQ_TONNES,
        disposition=Disposition.COMPUTE,
        formula="manual admin field",
        db_source="MANUAL-CONSTANCE",
        src_model_field=(
            "constance "
            "TOTAL_AVOIDED_EMISSIONS_OF_CONTROLLED_SUBSTANCES_IN_CO2_EQ_TONNES "
            "(+EXPECTED_AVOIDED_EMISSIONS_FROM_HFCS_IN_CO2_EQ_TONNES)"
        ),
        compute=None,
    ),
    Metric(
        metric_id="savings_to_society",
        label="Total savings to society",
        section="From protecting the ozone layer to safeguarding climate and health",
        kind=Kind.SCALAR,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula="manual admin field",
        db_source="MANUAL-CONSTANCE",
        src_model_field="constance TOTAL_SAVINGS_TO_SOCIETY_IN_US_DOLLAR",
        compute=None,
    ),
    Metric(
        metric_id="grant_funding_pledged",
        label="Grant funding pledged",
        section="Empowering the transition",
        kind=Kind.SCALAR,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula="external pledged contributions",
        db_source="EXTERNAL",
        src_model_field="none (pledged contributions)",
        compute=None,
    ),
    Metric(
        metric_id="ods_cost_per_odp_tonne",
        label="Cost to the Fund to remove one ODP tonne of ODS",
        section="Maximum impact minimum cost",
        kind=Kind.SCALAR,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula="manual admin field",
        db_source="MANUAL-CONSTANCE",
        src_model_field="constance COST_TO_THE_FUND_TO_REMOVE_1_ODP_TONNE_FROM_ODS",
        compute=None,
    ),
    Metric(
        metric_id="controlled_substances_cost_per_co2eq_tonne",
        label="Cost to the Fund to remove one CO2-eq tonne of controlled substances",
        section="Maximum impact minimum cost",
        kind=Kind.SCALAR,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula="manual admin field",
        db_source="MANUAL-CONSTANCE",
        src_model_field=(
            "constance "
            "COST_TO_THE_FUND_TO_REMOVE_1_CO2_EQ_TONNE_FROM_CONTROLLED_SUBSTANCES"
        ),
        compute=None,
    ),
    Metric(
        metric_id="hfc_expected_cost_per_co2eq_tonne",
        label="Expected cost to the Fund to remove one CO2-eq tonne of HFCs",
        section="Maximum impact minimum cost",
        kind=Kind.SCALAR,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula="manual admin field",
        db_source="MANUAL-CONSTANCE",
        src_model_field=(
            "constance EXPECTED_COST_TO_THE_FUND_TO_REMOVE_1_CO2_EQ_TONNE_FROM_HFCS"
        ),
        compute=None,
    ),
    Metric(
        metric_id="ods_phased_out",
        label="ODS phased out",
        section="Real reductions lasting results",
        kind=Kind.SCALAR,
        unit=Unit.ODP_TONNES,
        disposition=Disposition.COMPUTE,
        formula=(
            "sum(Total phase-out (ODP tonnes)) over is_ods projects (dashboard "
            "export; incl. production)"
        ),
        db_source="DB-COMPUTABLE",
        src_model_field="Project.total_phase_out_odp_tonnes",
        compute=None,
    ),
    Metric(
        metric_id="ods_funding_approved",
        label="Grant funding behind ODS phase-out",
        section="Real reductions lasting results",
        kind=Kind.SCALAR,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula=(
            "Sum approved funding over is_ods AND Type not in {Preparation; "
            "Institutional strengthening}"
        ),
        db_source="DB-COMPUTABLE",
        src_model_field="Project.total_fund + support_cost_psc, filtered is_ods",
        compute=None,
    ),
    Metric(
        metric_id="hfc_phased_out",
        label="HFCs phased out",
        section="Real reductions lasting results",
        kind=Kind.SCALAR,
        unit=Unit.CO2EQ_TONNES,
        disposition=Disposition.COMPUTE,
        formula=(
            "sum(Total phase-out (CO2-eq tonnes)) over is_hfc projects (dashboard "
            "export; incl. production)"
        ),
        db_source="DB-COMPUTABLE",
        src_model_field="Project.total_phase_out_co2_tonnes",
        compute=None,
    ),
    Metric(
        metric_id="hfc_funding_approved",
        label="Grant funding behind HFC phase-out",
        section="Real reductions lasting results",
        kind=Kind.SCALAR,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula="Sum approved funding over is_hfc projects",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.total_fund + support_cost_psc, filtered is_hfc",
        compute=None,
    ),
    Metric(
        metric_id="baseline_phased_out_by_substance",
        label="Baseline consumption phased out, by substance",
        section="Percentage of baseline consumption phased out by substance (%)",
        kind=Kind.TABLE,
        unit=Unit.PERCENT,
        disposition=Disposition.NOT_AVAILABLE,
        formula="phased_out / baseline; non HFC/HCFC families forced to 100%",
        db_source="EXTERNAL",
        src_model_field=(
            "numerator ProjectOdsOdp.odp by family; denominator "
            "MetaProject.baseline_odp/baseline_co2_eq_t"
        ),
        compute=None,
        unavailable_reason=(
            "Numerator is computable from ProjectOdsOdp.odp, but the baseline "
            "denominator is per-agreement and external to ORS."
        ),
    ),
    Metric(
        metric_id="pct_countries_met",
        label="Countries meeting their targets",
        section="National implementation and reach",
        kind=Kind.SCALAR,
        unit=Unit.PERCENT,
        disposition=Disposition.STATIC,
        formula="hardcoded",
        db_source="MANUAL",
        src_model_field="none",
        compute=None,
    ),
    Metric(
        metric_id="countries_capacity",
        label="Countries receiving capacity-building support",
        section="Building capacity strengthening compliance",
        kind=Kind.SCALAR,
        unit=Unit.COUNT,
        disposition=Disposition.STATIC,
        formula="hardcoded",
        db_source="MANUAL",
        src_model_field="none",
        compute=None,
    ),
    Metric(
        metric_id="countries_assisted",
        label="Countries assisted",
        section="National implementation and reach",
        kind=Kind.SCALAR,
        unit=Unit.COUNT,
        disposition=Disposition.STATIC,
        formula="hardcoded",
        db_source="DB-COMPUTABLE",
        src_model_field=(
            "distinct Project.country where Country.location_type='Country'"
        ),
        compute=None,
    ),
    Metric(
        metric_id="funds_approved",
        label="Funds approved",
        section="Targeted support for developing countries",
        kind=Kind.BREAKDOWN,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula="Sum (funds approved + PSC) over latest codes",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.total_fund + support_cost_psc",
        compute=None,
    ),
    Metric(
        metric_id="funds_lvc_split",
        label="Funds approved by LVC status",
        section="Targeted support for developing countries",
        kind=Kind.BREAKDOWN,
        unit=Unit.USD,
        disposition=Disposition.NOT_AVAILABLE,
        formula="Sum (funds+PSC) grouped by Consumption level status",
        db_source="DB-COMPUTABLE",
        src_model_field=(
            "Country.is_lvc (authoritative) NOT Project.consumption_level_status"
        ),
        compute=None,
        unavailable_reason=(
            "Pending a stakeholder decision on a second LVC status for HFCs. "
            "Country.is_lvc itself is fully populated in the database - the ~99%-null "
            "observation was an export artifact."
        ),
    ),
    Metric(
        metric_id="funds_disbursed",
        label="Funds disbursed",
        section="Targeted support for developing countries",
        kind=Kind.BREAKDOWN,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula=(
            "sum(Funds Disbursed (US$)) over the full APR export (status= → all "
            "statuses); active-cycle = ONG+COM subset"
        ),
        db_source="NEEDS-APR",
        src_model_field="AnnualProjectReport.funds_disbursed",
        compute=None,
    ),
    Metric(
        metric_id="projects_approved_total",
        label="Total number of projects",
        section="Total number of projects",
        kind=Kind.BREAKDOWN,
        unit=Unit.COUNT,
        disposition=Disposition.COMPUTE,
        formula="count(distinct code) where status not in {Transferred; Closed}",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.code, Project.status",
        compute=None,
    ),
    Metric(
        metric_id="completed_count",
        label="Completed projects",
        section="Completed projects and amount of funds approved",
        kind=Kind.SCALAR,
        unit=Unit.COUNT,
        disposition=Disposition.COMPUTE,
        formula="count(code) where status in {Completed; Financially completed}",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.code, Project.status",
        compute=None,
    ),
    Metric(
        metric_id="completed_funding",
        label="Funding approved for completed projects",
        section="Completed projects and amount of funds approved",
        kind=Kind.SCALAR,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula="Sum funding over the #22 completed set",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.total_fund+psc filtered completed",
        compute=None,
    ),
    Metric(
        metric_id="completed_end_year",
        label="Most recent reporting year",
        section="Completed projects and amount of funds approved",
        kind=Kind.SCALAR,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="latest endorsed APR year",
        db_source="NEEDS-APR",
        src_model_field="AnnualProgressReport.year (max)",
        compute=None,
    ),
    Metric(
        metric_id="ongoing_count",
        label="Ongoing projects",
        section="Ongoing projects and amount of funds approved",
        kind=Kind.SCALAR,
        unit=Unit.COUNT,
        disposition=Disposition.COMPUTE,
        formula="count(code) where status == Ongoing",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.code, Project.status",
        compute=None,
    ),
    Metric(
        metric_id="ongoing_funding",
        label="Funding approved for ongoing projects",
        section="Ongoing projects and amount of funds approved",
        kind=Kind.SCALAR,
        unit=Unit.USD,
        disposition=Disposition.COMPUTE,
        formula="Sum funding over ongoing set",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.total_fund+psc filtered ongoing",
        compute=None,
    ),
    Metric(
        metric_id="by_agency",
        label="Projects and funding by agency",
        section="Global partnerships for project delivery",
        kind=Kind.TABLE,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="groupby per-component 'Agency'; count codes + Sum funding",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.agency (per-component) -> Agency.name",
        compute=None,
    ),
    Metric(
        metric_id="investment_timeline",
        label="Investment project timeline",
        section="Timeline for investment projects",
        kind=Kind.BREAKDOWN,
        unit=Unit.MONTHS,
        disposition=Disposition.COMPUTE,
        formula=(
            "avg(first disbursement - approved) & avg completion duration; "
            "Type=Investment"
        ),
        db_source="NEEDS-APR",
        src_model_field=(
            "AnnualProjectReport.date_first_disbursement + date_approved_denorm "
            "(computed avg)"
        ),
        compute=None,
    ),
    Metric(
        metric_id="inv_months_first_disb",
        label="Months to first disbursement, investment projects",
        section="Timeline for investment projects",
        kind=Kind.SCALAR,
        unit=Unit.MONTHS,
        disposition=Disposition.COMPUTE,
        formula="avg(first disbursement - approved) Type=Investment",
        db_source="NEEDS-APR",
        src_model_field="AnnualProjectReport.date_first_disbursement",
        compute=None,
    ),
    Metric(
        metric_id="inv_months_completion",
        label="Months to completion, investment projects",
        section="Timeline for investment projects",
        kind=Kind.SCALAR,
        unit=Unit.MONTHS,
        disposition=Disposition.COMPUTE,
        formula="avg completion duration from inventory Type=Investment",
        db_source="NEEDS-APR",
        src_model_field=(
            "AnnualProjectReport.date_actual_completion / date_approved_denorm"
        ),
        compute=None,
    ),
    Metric(
        metric_id="noninv_first_disbursement_scope",
        label=(
            "Months to first disbursement, non-investment projects with at "
            "least one disbursement"
        ),
        section="Timeline for non-investment projects",
        kind=Kind.SCALAR,
        unit=Unit.MONTHS,
        disposition=Disposition.COMPUTE,
        formula=(
            "avg(first disbursement - approved); non-Investment; >=1 disbursement "
            "only"
        ),
        db_source="NEEDS-APR",
        src_model_field="AnnualProjectReport.funds_disbursed + date_first_disbursement",
        compute=None,
    ),
    Metric(
        metric_id="noninv_months_first_disb",
        label="Months to first disbursement, non-investment projects",
        section="Timeline for non-investment projects",
        kind=Kind.SCALAR,
        unit=Unit.MONTHS,
        disposition=Disposition.COMPUTE,
        formula="avg(first disbursement - approved) non-Investment",
        db_source="NEEDS-APR",
        src_model_field="AnnualProjectReport.date_first_disbursement",
        compute=None,
    ),
    Metric(
        metric_id="noninv_months_completion",
        label="Months to completion, non-investment projects",
        section="Timeline for non-investment projects",
        kind=Kind.SCALAR,
        unit=Unit.MONTHS,
        disposition=Disposition.COMPUTE,
        formula="avg(end date - start date) non-Investment",
        db_source="DB-COMPUTABLE-SPARSE",
        src_model_field="Project.project_start_date / project_end_date",
        compute=None,
    ),
    Metric(
        metric_id="portfolio_projects",
        label="Projects in the portfolio",
        section="Our project portfolio",
        kind=Kind.SCALAR,
        unit=Unit.COUNT,
        disposition=Disposition.COMPUTE,
        formula="same source as #37",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.code (all)",
        compute=None,
    ),
    Metric(
        metric_id="countries_portfolio",
        label="Developing countries in the portfolio",
        section="Our project portfolio",
        kind=Kind.SCALAR,
        unit=Unit.COUNT,
        disposition=Disposition.STATIC,
        formula="hardcoded",
        db_source="MANUAL",
        src_model_field="none",
        compute=None,
    ),
    Metric(
        metric_id="portfolio_projects_rounded",
        label="Portfolio total, rounded down to the nearest thousand",
        section="10K+ TOTAL NUMBER OF PROJECTS",
        kind=Kind.SCALAR,
        unit=Unit.COUNT,
        disposition=Disposition.COMPUTE,
        formula="count(distinct LATEST code) floor to nearest 1000 append '+'",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.code (latest)",
        compute=None,
    ),
    Metric(
        metric_id="by_region",
        label="Projects and funding by region",
        section="From global commitments to regional action",
        kind=Kind.TABLE,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="count codes by region + Sum funding",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.code by Region (Country.parent chain)",
        compute=None,
    ),
    Metric(
        metric_id="theme_consumption",
        label="Consumption projects",
        section="Consumption projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="residual theme (first-match-wins; Consumption last)",
        db_source="DB-COMPUTABLE-MESSY",
        src_model_field="Project classification (residual)",
        compute=None,
    ),
    Metric(
        metric_id="theme_production",
        label="Production projects",
        section="Production projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="Production flag",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.production / cluster / sector",
        compute=None,
    ),
    Metric(
        metric_id="theme_ee",
        label="Energy efficiency projects",
        section="Energy efficiency projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="EE cluster OR funding window in {89/6;91/65;94/60;95/87}",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.cluster / Funding window",
        compute=None,
    ),
    Metric(
        metric_id="theme_disposal",
        label="Disposal projects",
        section="Disposal projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="Disposal type/cluster OR funding window 91/66",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.cluster/sector / Funding window",
        compute=None,
    ),
    Metric(
        metric_id="theme_hfc23",
        label="HFC-23 projects",
        section="HFC-23 projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="Emission Control cluster",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.cluster (Emission Control)",
        compute=None,
    ),
    Metric(
        metric_id="theme_is",
        label="Institutional strengthening projects",
        section="Institutional strengthening projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="Type == Institutional strengthening",
        db_source="DB-COMPUTABLE",
        src_model_field="Project.project_type (IS)",
        compute=None,
    ),
    Metric(
        metric_id="sector_ac",
        label="Air-conditioning projects",
        section="Air-conditioning projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="count + Sum approved funding by sector=AC; disbursed NOT AVAILABLE",
        db_source="DB-COMPUTABLE+NEEDS-APR",
        src_model_field=(
            "approved: Project.total_fund by sector; disbursed: "
            "AnnualProjectReport.funds_disbursed by project.sector"
        ),
        compute=None,
    ),
    Metric(
        metric_id="sector_ref",
        label="Refrigeration projects",
        section="Refrigeration projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="count + Sum approved funding; disbursed NOT AVAILABLE",
        db_source="DB-COMPUTABLE+NEEDS-APR",
        src_model_field="(same as #47)",
        compute=None,
    ),
    Metric(
        metric_id="sector_srv",
        label="Servicing projects",
        section="Servicing projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="count + Sum approved funding; disbursed NOT AVAILABLE",
        db_source="DB-COMPUTABLE+NEEDS-APR",
        src_model_field="(same as #47)",
        compute=None,
    ),
    Metric(
        metric_id="sector_foam",
        label="Foam projects",
        section="Foam projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="count + Sum approved funding; disbursed NOT AVAILABLE",
        db_source="DB-COMPUTABLE+NEEDS-APR",
        src_model_field="(same as #47)",
        compute=None,
    ),
    Metric(
        metric_id="sector_aerosol",
        label="Aerosol projects",
        section="Aerosol projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="count + Sum approved funding; disbursed NOT AVAILABLE",
        db_source="DB-COMPUTABLE+NEEDS-APR",
        src_model_field="(same as #47)",
        compute=None,
    ),
    Metric(
        metric_id="sector_solvent",
        label="Solvent projects",
        section="Solvent projects",
        kind=Kind.BREAKDOWN,
        unit=None,
        disposition=Disposition.COMPUTE,
        formula="count + Sum approved funding; disbursed NOT AVAILABLE",
        db_source="DB-COMPUTABLE+NEEDS-APR",
        src_model_field="(same as #47)",
        compute=None,
    ),
)

FUND_METRICS_BY_ID = index_metrics(FUND_METRICS, "FUND_METRICS")
